### ISSUE TITLE
🍷 功能需求：如何增加统计收藏网址，访客的点击的次数，以及给访客手动点赞的按键？

### ISSUE THREAD

**Issue by setdiaoyong** [xjh22222228/nav#101]
参考https://ionego.net/sites/79.html

![image](https://user-images.githubusercontent.com/62551864/108614799-c1012380-7438-11eb-8572-e44444ae4482.png)

**Comment by xjh22222228** [comment]
实现不了。

**Comment by setdiaoyong** [comment]
好的，主要是Server Less，基于github issue的评论系统倒是不错，不知道能不能从github issue中添加表情的功能着手，想法留在这，备查，我再查查资料

**Comment by aiyou9** [comment]
这个单独开一个github库，将这个库的issue用作评论，issue里反馈的时候可以添加表情图片，每个访问用户点击一次，就增加1，不知道这个功能，github有没有提供API，不知道能否实现？
