### ISSUE TITLE
🍷 功能需求：访问加载画面，自定义背景图片

### ISSUE THREAD

**Issue by setdiaoyong** [xjh22222228/nav#102]
访问加载画面，自定义背景图片，这样如果默认黑暗模式，可以选择黑暗点的图片，跳转过度自然一些，也放imge分支，走CDN？
![image](https://user-images.githubusercontent.com/62551864/108619874-c2474600-7462-11eb-9e59-a94cf27bda9a.png)

**Comment by xjh22222228** [comment]
不行的，loading 不能太大，  不然渲染完了图片还没出来。

**Comment by setdiaoyong** [comment]
是的，对图片的加载要求高，第一次加载是以部署者默认的，然后是否可以根据当前访问者设置的黑暗或明亮模式，使用对应的加载页背景，访问者如果设置为黑暗，刷新加载页就是黑暗的，访问者设置的是明亮，刷新加载页就是明亮的

**Comment by aiyou9** [comment]
用bing或其他的速度快的图片供应商的API，每日一图，也比较快
