### ISSUE TITLE
🍷 功能需求：网址图标的上传方式，可以支持直接复制粘贴图片，上传吗

### ISSUE THREAD

**Issue by setdiaoyong** [xjh22222228/nav#103]
主要是从浏览的网页中，复制图片，直接粘贴网址条目的 编辑对话框中，这是直接复制的图片，还是图片的网址，下载上传，我去找找案例

**Comment by xjh22222228** [comment]
有没有现成案例，参考一下。

**Comment by setdiaoyong** [comment]
（持续收集中……）
https://github.com/quilljs/quill
https://github.com/yuezhongxin/paste-upload-image.js
https://github.com/shuangaids/image-compress
http://demo.deanhan.cn/paste-upload/

1、可能要处理图片来源不同
a、网页上的
https://clipboardjs.com/
https://blog.csdn.net/weixin_45285641/article/details/103889501
https://segmentfault.com/a/1190000011897832
https://www.deanhan.cn/js-paste-upload.html
b、window文件
https://www.jb51.net/article/201747.htm

c、截图工具

2、粘贴的具体内容不同
a、img64

b、文件

3、粘贴后处理不同
a、直接上传

b、同时前端展示

c、后端保存

**Comment by setdiaoyong** [comment]
已测试，功能无问题
