### ISSUE TITLE
🍷 功能需求：每个网址增加内页，有助于SEO，每个内页上增加基于github issue 的评论系统

### ISSUE THREAD

**Issue by setdiaoyong** [xjh22222228/nav#105]
场景描述：
如果在主页面使用，精简型网址标签页，是否可以实现每个网址收集标签页即可直接跳转，也给一个按钮跳转到内页，在每个内页上增加基于github issue的评论系统，在主页面的标签页上展示，当前评论的数量，点击可以跳转到评论的位置。

优点：
1、增加网址标签页的内页，可精简主页面的网址标签页；
2、增加网址标签页的内页，可增强SEO；
3、增加网址标签页的内页，可对每一个网址标签页，添加评论系统。

参考资料
1、精简型网址标签页+内页系统的参考网站： https://ionego.net/
2、基于github issue的评论系统：1、https://github.com/imsun/gitment 
3、对历史页面可以使用批量工具，增加gitment到历史页面。

**Comment by setdiaoyong** [comment]
这个样式感觉也不错，
1、小图标的展示页
2、内页或编辑页
3、背景图片自动加载，加一层调暗的蒙版，做背景
![image](https://user-images.githubusercontent.com/62551864/109820823-53db6280-7c70-11eb-8b36-33ca0a3fbbcf.png)

**Comment by setdiaoyong** [comment]
> 场景描述：
> 如果在主页面使用，精简型网址标签页，是否可以实现每个网址收集标签页即可直接跳转，也给一个按钮跳转到内页，在每个内页上增加基于github issue的评论系统，在主页面的标签页上展示，当前评论的数量，点击可以跳转到评论的位置。
> 
> 优点：
> 1、增加网址标签页的内页，可精简主页面的网址标签页；
> 2、增加网址标签页的内页，可增强SEO；
> 3、增加网址标签页的内页，可对每一个网址标签页，添加评论系统。
> 
> 参考资料
> 1、精简型网址标签页+内页系统的参考网站： https://ionego.net/
> 2、基于github issue的评论系统：1、https://github.com/imsun/gitment
> 3、对历史页面可以使用批量工具，增加gitment到历史页面。

这个基于github的blog也不错，值的参考
https://axetroy.xyz/

**Comment by aifact** [comment]
创建一个新的库，把这个新创建库的issue用作评论，每个网址标签页增加一个评论按钮，还有如果能用issue里添加表情的功能，就能实现统计给网址打星标的用户数，我去看看github有没有issue里添加表情的API
