### ISSUE TITLE
功能需求：直接从浏览器当前打开的标签页，添加到nav导航

### ISSUE THREAD

**Issue by aifact** [xjh22222228/nav#108]

**Comment by xjh22222228** [comment]
这怎么实现。。。

**Comment by aifact** [comment]
> 这怎么实现。。。

我去查查浏览器内核的API，看到www.meetsidekick.com 搞得新款浏览器内置插件可以实现从当前标签页添加到云端后台。

**Comment by xjh22222228** [comment]
浏览器插件不一样了，目前浏览器没有提供这种API。

**Comment by setdiaoyong** [comment]
> 浏览器插件不一样了，目前浏览器没有提供这种API。

不通过插件，仅用js，是不可能的了 参见
https://bbs.csdn.net/topics/391984481

浏览器扩展程序才能获取，参见
https://blog.csdn.net/weixin_34081595/article/details/93817369

预计实现的路径，是要先开发个浏览器插件，获取后，传递给js。

**Comment by aifact** [comment]
论坛里帖子https://superuser.com/questions/117754/is-there-a-way-to-copy-urls-from-all-open-tabs-in-a-google-chrome-or-other-brow
相关复制，导出当前所有浏览tab的插件
1、https://chrome.google.com/webstore/detail/tabcopy/micdllihgoppmejpecmkilggmaagfdmb?hl=en-US
2、https://chrome.google.com/webstore/detail/list-all-tabs/iklkoalaepbjckknpnklbipmplnipcid?hl=en
https://github.com/lior99/see-all-tabs/blob/master/CHANGELOG.MD
提供源代码 Github Repo: https://github.com/lior99/see-all-tabs
3、https://tabler.one/
4、https://chrome.google.com/webstore/detail/tab-snap/ajjloplcjllkammemhenacfjcccockde
5、https://www.makeuseof.com/tag/10-extensions-chrome-tab-management/
浏览器插件有API？
参见 https://developer.chrome.com/docs/extensions/reference/windows/#method-getCurrent

国外大佬们的解决方案https://stackoverflow.com/questions/11114395/get-urls-of-all-open-tabs-in-chrome-and-send-it-to-a-web-service
XMLHttp 被取消了？

只能从浏览器扩展获取后，传给网页
