### ISSUE TITLE
手机浏览器如何进入后台

### ISSUE THREAD

**Issue by PhoebeCLS** [xjh22222228/nav#109]
### Version
5.3.1

### Reproduction link
[https://github.com/PhoebeCLS/nav](https://github.com/PhoebeCLS/nav)

### Steps to reproduce
部署完成后，手机默认主题始终为light(电脑已经更改)，且手机怎么进入后台？电脑进入后台是否就是ctrl e？

### What is expected?
如果手机不能进入后台请求添加此功能

### What is actually happening?
手机浏览器打开后无法进入后台

**Comment by xjh22222228** [comment]
手机打开应该是APP主题的， 手机目前无法编辑，手机操作也麻烦。

**Comment by PhoebeCLS** [comment]
好的希望支持更多手机主题！谢谢大佬

**Comment by PhoebeCLS** [comment]
好的希望支持更多手机主题！谢谢大佬

**Comment by PhoebeCLS** [comment]
。

**Comment by PhoebeCLS** [comment]
好的希望支持更多手机主题！谢谢大佬

**Comment by xjh22222228** [comment]
主题会陆续推出，如果你有好的主题可以发来参考。

**Comment by aifact** [comment]
可以用新版edge手机浏览器，我是安卓的。这个浏览器有个访问  桌面版网站  功能，打开这个功能后，需要在地址栏里，手动将地址https://你的域名/#/app，改为https://你的域名/#/side 登录token就可以像电脑端相似的方式添加网址了，不过手机切换，复制粘贴也麻烦，或者开个其他浏览器，方便切换。

**Comment by aifact** [comment]
可以用新版edge手机浏览器，我是安卓的。这个浏览器有个访问  桌面版网站  功能，打开这个功能后，需要在地址栏里，手动将地址https://你的域名/#/app，改为https://你的域名/#/side 登录token就可以像电脑端相似的方式添加网址了，不过手机切换，复制粘贴也麻烦，或者开个其他浏览器，方便切换。

**Comment by aifact** [comment]
> 可以用新版edge手机浏览器，我是安卓的。这个浏览器有个访问 桌面版网站 功能，打开这个功能后，需要在地址栏里，手动将地址[https://你的域名/#/app，改为https://你的域名/#/side](https://%E4%BD%A0%E7%9A%84%E5%9F%9F%E5%90%8D/#/app%EF%BC%8C%E6%94%B9%E4%B8%BAhttps://%E4%BD%A0%E7%9A%84%E5%9F%9F%E5%90%8D/#/side) 登录token就可以像电脑端相似的方式添加网址了，不过手机切换，复制粘贴也麻烦，或者开个其他浏览器，方便切换。

nav不支持app和桌面端自动被edge识别，只能手动在地址栏改地址，切换主题为非app的，其中side的页面上的添加功能，也不能用，点出来不能输入，只能到后台进行添加
