### ISSUE TITLE
🌟 核心功能：所有主题中合并与展开功能键的优化

### ISSUE THREAD

**Issue by aifact** [xjh22222228/nav#114]
#53 
单独为这个功能，捐赠了，请作者，看看能否实现。

在当前激活的二级目录的标题后面，增加一个收起与合并三级目录的功能键，点到哪个二级目录，就在二级目录标题后，加个收起与合并三级目录的功能键，这样能够快速切换，比将收起与合并三级目录的功能键放在右下角悬浮工具栏好。

可以缩短操作距离，优化使用流程，适配大屏，提高切换的快捷性，更高效率。右下角的功能键，与一，二级目录（操作层级）离的太远

**Comment by xjh22222228** [comment]
晚点加上。

**Comment by aifact** [comment]
> 晚点加上。

嗯嗯，不急，核心功能更优先。

**Comment by aifact** [comment]
已测试，有一个小问题，在nav3.cn 的side主题中，实用工具--开发相关——开发神器，比较多有44个，在浏览到一半时，使用二级标题后的合并展开功能键，会有一个回到第一个三级目录的步骤，而其他比较少的目录，就是直接合并三级目录。

**Comment by xjh22222228** [comment]
你说的是什么问题， 来张图。

**Comment by aifact** [comment]
> 你说的是什么问题， 来张图。

明天具体截图说明，今天淦不动了

**Comment by aifact** [comment]
> > 你说的是什么问题， 来张图。
> 
> 明天具体截图说明，今天淦不动了

![无标题项目](https://user-images.githubusercontent.com/79238945/113517060-6e2a9800-95b0-11eb-8fb6-6bb7debc00d2.gif)

**Comment by aifact** [comment]
20210405 12：47  nav3.cn 测试。还有一个问题见下图
![无标题项目s](https://user-images.githubusercontent.com/79238945/113538205-356cdc00-960d-11eb-8f3f-1a967e03d019.gif)

**Comment by aifact** [comment]
能用了，小问题忽略

**Comment by aifact** [comment]
light，sim等主题也可以添加这个快速合并与展开的功能按钮

**Comment by aifact** [comment]
有个功能需要增加，就是当前二级标题下的三级标题一旦有被鼠标点击展开时，当前二级标题后的按钮，应该跟随着改变状态，这样才能实现浏览三级标题下网址时，点击一次二级标题后的按钮，实现合并三级标题

**Comment by aifact** [comment]
右侧悬浮按钮的状态也未和三级标题展开状态同步，可能要实现，一旦有一个三级目录是展开的，按钮就是处展开的状态，点击一次就可立刻合并所有三级目录

**Comment by aifact** [comment]
这个展开与合并的快捷功能键的逻辑，当三级目录标题大于等于1个，展开与合并的快捷功能键自动切换成展开；当且只有在所有三级标题都被合并后，展开与合并的快捷功能键才自动切换成合并状态，然后在浏览中，只要点击一次功能键，就可合并与展开三级列表标题
