### ISSUE TITLE
菜单功能重复

### ISSUE THREAD

**Issue by 2926295173** [xjh22222228/nav#119]
### What problem does this feature solve?
复制链接与分享网站都是实现的复制网址功能。重复了，希望删除

### What does the proposed API look like?
。

**Comment by xjh22222228** [comment]
不重复，
复制链接： 复制当前网站的链接
分享链接：发现给他人能直接打开你的导航网站并显示分享的网站

**Comment by 2926295173** [comment]
哦好的，是我大意了，sorry
