### ISSUE TITLE
能否介绍一下这个怎么搭建 ?

### ISSUE THREAD

**Issue by keepthinkingit** [xjh22222228/nav#12]
仓库已经克隆到 网站根目录 , 不知道怎么样才能搭建起来 ?
有没有教程/帮助 之类的 ? 
谢谢 .

**Comment by xjh22222228** [comment]
@keepthinkingit  V2版本尚未开源， 可以考虑 [v1](https://github.com/xjh22222228/nav/tree/v1)

**Comment by keepthinkingit** [comment]
好的 , 谢谢 .
