### ISSUE TITLE
功能建议—添加图片懒加载

### ISSUE THREAD

**Issue by 2926295173** [xjh22222228/nav#120]
### What problem does this feature solve?
将会解决首次进入加载时间长，网页卡顿的问题

### What does the proposed API look like?
.

**Comment by aifact** [comment]
#89

**Comment by 2926295173** [comment]
好的，将关闭

**Comment by aifact** [comment]
主要是现在使用了github，CDN，基本上加载速度还说的过去，我现在在到处复制其他人的导航站里网址资源

**Comment by aifact** [comment]
nav3.cn的首屏加载缓慢的问题，可能有两个，1、收藏网站的图标资源网址变了，无法访问，2、http资源，在https下无法加载
