### ISSUE TITLE
代码建议--建议您的开源项目运用DeepScan检查和优化代码

### ISSUE THREAD

**Issue by 2926295173** [xjh22222228/nav#122]
https://deepscan.io/
是github上的合作website,免费为开源项目提供代码优化检测，请您试试看优化代码，目前fork您的代码检测出21个问题，还望您查看修复。[![DeepScan grade](https://deepscan.io/api/teams/13592/projects/16636/branches/361040/badge/grade.svg)](https://deepscan.io/dashboard#view=project&tid=13592&pid=16636&bid=361040)

**Comment by xjh22222228** [comment]
好的，3Q， 看了下都是LINT问题。
