### ISSUE TITLE
黑暗主题美化：希望还是能实现黑暗主题的全部黑暗

### ISSUE THREAD

**Issue by aifact** [xjh22222228/nav#126]
#104
希望还是能实现全部黑暗
![image](https://user-images.githubusercontent.com/79238945/114775396-d42ed080-9da3-11eb-95d1-b42b4355850e.png)

**Comment by aifact** [comment]
已测试，黑暗没有问题，但似乎搜索的历史记录不显示了

**Comment by xjh22222228** [comment]
浏览器问题，目前还没有解决方案，只能去掉自动填充才能解决。
