### ISSUE TITLE
功能需求：是否能在网址条目页面下方增加按钮，并实现直接点击按钮，添加网址到访问者的浏览器收藏夹？

### ISSUE THREAD

**Issue by aifact** [xjh22222228/nav#127]
看这个导航站，似乎要实现这个功能，但是这个功能在chrome等浏览器报错，不知道是什么浏览器
**https://lework.github.io/lenav/#/**

相应的GitHub库地址：https://github.com/lework/lenav
不知道chrome这类的浏览器是否有提供这个功能的API
![image](https://user-images.githubusercontent.com/79238945/114779892-3c33e580-9da9-11eb-9b8a-5ca25bbf5751.png)

**Comment by xjh22222228** [comment]
不支持。
