### ISSUE TITLE
搜索结果展示页面优化：使用可合并展开与跳转主页的树状导图，展示检索出的相同目录层级下的网址

### ISSUE THREAD

**Issue by aifact** [xjh22222228/nav#129]
![image](https://user-images.githubusercontent.com/79238945/114875732-2c131900-9e30-11eb-966d-b0afc9ed522b.png)

**Comment by xjh22222228** [comment]
精力有限, 新功能先缓一缓，先把前面的处理完。

**Comment by aifact** [comment]
> 精力有限, 新功能先缓一缓，先把前面的处理完。

嗯，是的，我是想到，就提交到这里，目前side已经够用了，也不急

**Comment by aifact** [comment]
**另一种实现：**

在nav3中，搜索或搜索结果用弹出悬浮窗体进行展示。
窗体中可选择切换全部展示（提供根据多种条件排序，如添加时间，推荐星级，等能实现的条件）
也可一键切换到树状导图，进行浏览，可查阅搜索关键词，搜索出来的分类，然后点击分类，跳转到分类，查看相近的站点，然后有个一键返回搜索结果的功能键，能够进行悬浮窗体与主站的一键切换与返回，这样还能回到搜索结果，再次浏览选择其他感兴趣的，进行浏览（具体感觉还是要用网页设计工具，做一下具体的网页页面设计，我看能不能学一学，设计一下）

**主要目的：**
实现能根据搜索关键词，不仅能够给出具体网址，还能给出所在的分类，并且能够方便的跳转分类，浏览其他感兴趣的，然后再跳转回搜索结果，再找感兴趣的结果，再次跳转分类，进行浏览，毕竟Nav3支持3级分类，且网址收集到上千个后，如何加快浏览效率，发现与搜索关键词一个分类的新的收集网址，对访客也是有吸引力的！
