### ISSUE TITLE
Typora被拼成了Typeora

### ISSUE THREAD

**Issue by MarcusPierce** [xjh22222228/nav#131]
### Version
5.3.2

### Reproduction link
[https://www.nav3.cn/#/sim?page=0&id=2&_=1619570441245&q=](https://www.nav3.cn/#/sim?page=0&id=2&_=1619570441245&q=)

### Steps to reproduce
点击GUI软件

### What is expected?
Typeora拼成Typora

### What is actually happening?
Typora被拼成了Typeora

**Comment by xjh22222228** [comment]
感谢，已修正！
