### ISSUE TITLE
表哥，我部署成功了

### ISSUE THREAD

**Issue by Cuiyim** [xjh22222228/nav#138]
但是同步远程数据的时候提示
错误: 403
同步失败, 请重试

**Comment by xjh22222228** [comment]
文档有写，按照步骤操作。

**Comment by Cuiyim** [comment]
表哥表哥，我是按照步骤操作的。。。有时候点一下就直接失败，有时候是上边的进度条快跑完的时候提示这个

**Comment by xjh22222228** [comment]
那说明你操作不对，是不是没选权限？重新操作吧。

**Comment by Cuiyim** [comment]
![image](https://user-images.githubusercontent.com/51844650/117802517-27535080-b288-11eb-9c61-343413c337d0.png)

**Comment by Cuiyim** [comment]
错误401  同步失败

**Comment by xjh22222228** [comment]
没权限，把仓库删了，重新操作试试。

**Comment by xjh22222228** [comment]
成功了吗？ 另外你是从哪个渠道了解此项目的。

**Comment by Cuiyim** [comment]
成功了。只有删除仓库第一次构建可以同步，之后同步全都是报错

**Comment by Cuiyim** [comment]
> 成功了吗？另外你是从哪些渠道了解此项目的。

git搜索  导航 一个一个点进去点到的

**Comment by xjh22222228** [comment]
同步成功5分钟后  再同步，不要频繁操作。

**Comment by Cuiyim** [comment]
过了五小时了再操作的，，，

**Comment by cyber-pixel** [comment]
> 过了五小时了再操作的，，，

后来呢？？
