### ISSUE TITLE
功能设计: 本地或vps自动化构建，及推送，提高部署的可适配范围。

### ISSUE THREAD

**Issue by aifact** [xjh22222228/nav#139]
问题描述
github的访问性不稳定，玩导航页的，基本上有云空间，VPS，免费的也很多，都会对访问性优化，因此，本地化后台，进行编辑，推送到云空间，或vps进行部署有后台的，能提高访问性能。

需求描述
1、本地化electron后台软件，进行编辑和推送到云空间
2、使用支持vps的本地化github action，进行与github 网站action的同步部署
参考案例
1、github 开源博客软件项目gridea
2、github上与github action runner相似的开源项目，进行vps的同步部署

**Comment by xjh22222228** [comment]
最近比较忙，新功能不会有太大变化，欢迎提PR。

electron 好处可以提高速度， 但是太大了，资源也占用太多。

**Comment by aifact** [comment]
> 最近比较忙，新功能不会有太大变化，欢迎提PR。
> 
> electron 好处可以提高速度， 但是太大了，资源也占用太多。

还是可能的选项2，基于本地化github action runner，合适

我不会编程，只能提交点功能上的设计，参考案例啥的。现在的nav，对我来说已经够用了。感谢你开源的这个导航页项目！

**Comment by owlrock7** [comment]
首先感谢大佬的项目！撒花～
因为手残学不会 git rebase , 也不想重新fork部署，所以采用了vps本地运行。
pm2 start yarn --name nav --watch -- start 能正常运行，不清楚现在的情况数据是否能永久运行？

**Comment by xjh22222228** [comment]
@owlrock7  数据不会丢失。

**Comment by owlrock7** [comment]
> @owlrock7 数据不会丢失。

好的，感谢解答。以后可以自行拉库更新了。
