### ISSUE TITLE
同步远端失败

### ISSUE THREAD

**Issue by 51sec** [xjh22222228/nav#142]
### Version
5.3.2

### Reproduction link
[https://bookmarks-zeta.vercel.app/#/light](https://bookmarks-zeta.vercel.app/#/light)

### Steps to reproduce
试图编辑链接内容，然后同步到远程，但是得到404失败

### What is expected?
能够同步

### What is actually happening?
失败

---
没有了。

**Comment by 51sec** [comment]
错误: 404
同步失败, 请重试

**Comment by xjh22222228** [comment]
大概率是没权限，生成TOKEn时全部勾选。

**Comment by 51sec** [comment]
已经全选了啊。生成了两个Token试验都是一样。

**Comment by xjh22222228** [comment]
我看了下你的仓库，你的配置文件都没改呢。
[https://github.com/51sec/nav/blob/main/nav.config.ts](https://github.com/51sec/nav/blob/main/nav.config.ts)

**Comment by 51sec** [comment]
啊，谢谢，我以为改了呢。就是这个问题。成功了。多谢！
