### ISSUE TITLE
推荐新的免费自动化部署空间：netlify.com

### ISSUE THREAD

**Issue by aifact** [xjh22222228/nav#149]
vercel.app被封了，推荐新的免费自动化部署空间：netlify.com   
建议写入项目doc中。

**Comment by xjh22222228** [comment]
没被墙呀， 我试试netlify 好用不。

**Comment by aifact** [comment]
> 没被墙呀， 我试试netlify 好用不。

被校园网墙的，netlify和vercel，一样简单
