### ISSUE TITLE
Help me translate to English

### ISSUE THREAD

**Issue by askfriends** [xjh22222228/nav#151]
### What problem does this feature solve?
Hello;
I have forked and translated it to English by using google translate.
After i have translated to English, there is no change in the site, I'm still seeing same Chinese menus and everything is in Chinese including in admin panel.
I cleared cookies and website data as well. So please have a look at my repo and suggest what I'm missing here.
Thanks
My Repo: https://github.com/askfriends/nav/
https://askfriends.github.io/nav/

### What does the proposed API look like?
Kindly have a look at my repo and suggest what should i do to reflect the changes to my site.

**Comment by xjh22222228** [comment]
Current work is in progress！Expected to be released within 3 days.

**Comment by askfriends** [comment]
> Current work is in progress！Expected to be released within 3 days.

sounds too good, waiting for it.

**Comment by askfriends** [comment]
> It has now been translated into English. Please help us to check, thanks!
> 
> [english.ts](https://github.com/xjh22222228/nav/blob/main/src/locale/english.ts)

i have just updated and its in English now, but site title, description and keywords are still in Chinese, so please add an option to change site title as well.
![Web capture_10-10-2021_19933_](https://user-images.githubusercontent.com/2517219/136699197-dfda7159-9a0e-4774-b131-53f8bbf8b6c4.jpeg)

**Comment by aifact** [comment]
> i have just updated and its in English now, but site title, description and keywords are still in Chinese, so please add an option to change site title as well.

all of these site title, description and keywords  can be rewrited up to you for building your website.
