### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by askfriends** [xjh22222228/nav#152]
### What problem does this feature solve?
I have some feature requests, hope you will look into it.

1. Add drag & Drop option to save any link by just drag & drop.
2. Add option to move websites from one category to another in admin panel.
3. Add option to select multiple websites and then we can 
a) Delete selected websites
b) move selected websites from one category to another.
4. Add option to import/export database file from admin panel for backup.
5. If possible add link shortener websites support link adfly etc.

### What does the proposed API look like?
Mentioned above in detaile

**Comment by aifact** [comment]
all these can modify in Chrome by using Bookmark Manager addin，after that ，import to your website
