### ISSUE TITLE
功能需求：解决side主题中多个打开合并按钮功能重叠问题

### ISSUE THREAD

**Issue by aifact** [xjh22222228/nav#154]
功能需求：side主题按钮修改，升级，
1、三级标题，在浏览其下网址条目时 ，悬浮固定于顶部，这样三级标题前的合并/展开按钮，就可以在具体浏览中，快速切换；

2、然后将二级标题后，合并/展开按钮，改为单向功能——只负责合并所有打开的三级列表（或者打开之前最后一次展开的三级标题），即回到三级列表全部合并状态，不负责打开（当前版本，会有打开所有三级列表的一个过程，网址条目多了，会明显卡顿）

3、当前版本右下角的悬浮窗中的合并/展开按钮，也改为单向功能，仅合并所有打开三级条目（或者打开之前最后一次展开的三级标题），与二级标题后按钮同功能，右下角有这个按钮，在大屏幕浏览时，可以直接在右下角点击按钮，回到全部合并状态的三级列表目录

**Comment by xjh22222228** [comment]
有点抽象，最好换下行说明， 三级标题不好悬浮。 搜索栏都占一些空间了。
