### ISSUE TITLE
开发环境不支持换域名

### ISSUE THREAD

**Issue by johnsafe** [xjh22222228/nav#158]
我正在找一款导航模板，就看到了这个项目，发现它功能很强，正是我想要的。   
但在我的电脑上跑起来体验以后，发现有几个问题：开发环境无法换host（需要：`"disableHostCheck":true`）；logo 的cdn指定了sevencdn，不够灵活，不如让用户自己填写logo的url等。  
后续我会提更多的issue来反映需求，等深度体验以后如有机会会提 pr。

**Comment by aifact** [comment]
> 我正在找一款导航模板，就看到了这个项目，发现它功能很强，正是我想要的。 但在我的电脑上跑起来体验以后，发现有几个问题：开发环境无法换host（需要：`"disableHostCheck":true`）；logo 的cdn指定了sevencdn，不够灵活，不如让用户自己填写logo的url等。 后续我会提更多的issue来反映需求，等深度体验以后如有机会会提 pr。
~~~~~~~~~~~~~~~~~~~~~~~~~~~~
欢迎，有兴趣可以看看这个项目已经关闭的issue，看看讨论的哪些功能，值得开发
