### ISSUE TITLE
免费的直接部署方式集合

### ISSUE THREAD

**Issue by aifact** [xjh22222228/nav#160]
本issue收集免费的部署空间
自动部署
1、https://www.stormkit.io/
![image](https://user-images.githubusercontent.com/79238945/144384085-999f5f3b-4c36-46df-a2c8-77665cdc4233.png)

2、https://alwaysdata.com
基本全能，无需验证，但只有100mb
3、https://vercel.app

4、https://netlify.com
比vercel快

5、https://render.com/
升级换代，很快，自动部署的免费限制为256mb，超出内存，nav无法免费使用，需要用git action 编译好，推流编译好的静态文件到静态空间

免费空间（github action 推送编译好的静态文件，通过FTP到免费空间）
1、https://infinityfree.net/
还不错，有手动三个月一续的ssl

2、http://deta.sh/
https://github.com/BogDAAAMN/deta-deploy-action

**Comment by aifact** [comment]
https://www.stormkit.io/
国内很快，巴适

**Comment by ymirlee** [comment]
有無stormkit.io 搭建教程可以提供，感謝

**Comment by aifact** [comment]
> 有無stormkit.io 搭建教程可以提供，感謝
> 
> 我deploy過程遇到如下錯誤
> 
> yarn install v1.22.15 [1/4] Resolving packages... [2/4] Fetching packages... info fsevents@2.3.2: The platform "linux" is incompatible with this module. info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation. info fsevents@1.2.13: The platform "linux" is incompatible with this module. info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation. [3/4] Linking dependencies... warning " > @angular/common@11.2.12" has incorrect peer dependency "rxjs@^6.5.3". warning " > @angular/core@11.2.12" has incorrect peer dependency "rxjs@^6.5.3". warning " > @angular/forms@11.2.12" has incorrect peer dependency "rxjs@^6.5.3". warning " > @angular/router@11.2.12" has incorrect peer dependency "rxjs@^6.5.3". warning "ng-zorro-antd > @ant-design/icons-angular@11.0.1" has incorrect peer dependency "rxjs@^6.4.0". [4/4] Building fresh packages... Done in 66.58s. [sk-step] The argument 'file' cannot be empty. Received ''

fork的最新版，在stormkit.io上部署有问题，正在排查，建议[netlify.com](https://www.netlify.com/),也能满足需求，[netlify的部署文件](https://github.com/xjh22222228/nav/blob/main/netlify.toml)已经在main库中更新，部署时填写如下
![image](https://user-images.githubusercontent.com/79238945/145178161-573175e4-c427-41a5-be5c-80331e25ad97.png)

**Comment by yefenghu** [comment]
> 
请问能否在自己的服务器上部署，比较傻瓜式的比如用宝塔面板搭建

**Comment by xjh22222228** [comment]
stormkit 不是很熟悉， 报错提示没有找到 index.html ， 打包的所有资源会在 dist 文件夹下， 我看了下没有找到可以选择部署文件夹。 所以猜测他检查的是根目录，而不是 dist 目录。

**Comment by aifact** [comment]
> 

好像可以直接在github 的action的配置里，加上推送到ftp的命令，登录密码用github的secret

**Comment by aifact** [comment]
> stormkit 不是很熟悉， 报错提示没有找到 index.html ， 打包的所有资源会在 dist 文件夹下， 我看了下没有找到可以选择部署文件夹。 所以猜测他检查的是根目录，而不是 dist 目录。

我之前在没有添加镜像站的提交，部署成功过，但是最新的main库，不行，我已经按照[stormkit的要求](https://www.stormkit.io/docs/deployments/configuration/angular)，添加了配置文件，也不行，很奇怪，准备去官方论坛问问

**Comment by aifact** [comment]
> > 
> 
> 好像可以直接在github 的action的配置里，加上推送到ftp的命令，登录密码用github的secret

github有很多ftp action 的npm包，直接可以推

**Comment by aifact** [comment]
> > > 
> > 
> > 
> > 好像可以直接在github 的action的配置里，加上推送到ftp的命令，登录密码用github的secret
> 
> github有很多ftp action 的npm包，直接可以推

https://github.com/SamKirkland/FTP-Deploy-Action

**Comment by aifact** [comment]
> stormkit 不是很熟悉， 报错提示没有找到 index.html ， 打包的所有资源会在 dist 文件夹下， 我看了下没有找到可以选择部署文件夹。 所以猜测他检查的是根目录，而不是 dist 目录。

netlify.com不错，还能给个部署成功的图标 #166

**Comment by aifact** [comment]
> > stormkit 不是很熟悉， 报错提示没有找到 index.html ， 打包的所有资源会在 dist 文件夹下， 我看了下没有找到可以选择部署文件夹。 所以猜测他检查的是根目录，而不是 dist 目录。
> 
> netlify.com不错，还能给个部署成功的图标 #166
在readme中添加以下
<a href="https://app.netlify.com/sites/docusaurus-2/deploys"><img src="https://api.netlify.com/api/v1/badges/9e1ff559-4405-4ebe-8718-5e21c0774bc8/deploy-status" alt="Netlify Status"></a>

其中
https://app.netlify.com/sites/docusaurus-2/deploys
https://api.netlify.com/api/v1/badges/9e1ff559-4405-4ebe-8718-5e21c0774bc8/deploy-status
改成自己部署库的site seting中的

**Comment by aifact** [comment]
新增部署方式
https://app.cloudcannon.com/
