### ISSUE TITLE
部署问题：部署空间需要index.html文件，作为入口，main分枝中是否修改了index.html？

### ISSUE THREAD

**Issue by aifact** [xjh22222228/nav#164]
![image](https://user-images.githubusercontent.com/79238945/144620890-ed7104a4-a06d-4ce5-9859-94d9ddfae10b.png)

**Comment by aifact** [comment]
搞不清楚，请帮我看看
1、node版本
node --version
 v14.18.1


2、安装
yarn install v1.22.15
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.3.2: The platform "linux" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > @angular/common@11.2.12" has incorrect peer dependency "rxjs@^6.5.3".
warning " > @angular/core@11.2.12" has incorrect peer dependency "rxjs@^6.5.3".
warning " > @angular/forms@11.2.12" has incorrect peer dependency "rxjs@^6.5.3".
warning " > @angular/router@11.2.12" has incorrect peer dependency "rxjs@^6.5.3".
warning "ng-zorro-antd > @ant-design/icons-angular@11.0.1" has incorrect peer dependency "rxjs@^6.4.0".
[4/4] Building fresh packages...
Done in 75.13s.


3、yarn build
yarn run v1.22.15
$ npm run setup && ng build --prod --base-href ./
npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1638557309019-0.798443523700558/node but npm is using /usr/local/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
> nav@6.0.1 setup /home/app/repo
> tsc nav.config.ts && ts-node ./scripts/build.mjs
Timezone: 0
Build done!
Option "extractCss" is deprecated: Deprecated since version 11.0. No longer required to disable CSS extraction for HMR.
Compiling @angular/core : es2015 as esm2015
Compiling @angular/common : es2015 as esm2015
Compiling @angular/platform-browser : es2015 as esm2015
Compiling @angular/platform-browser-dynamic : es2015 as esm2015
Compiling @angular/cdk/bidi : es2015 as esm2015
Compiling @angular/cdk/platform : es2015 as esm2015
Compiling @angular/cdk/collections : es2015 as esm2015
Compiling @angular/cdk/scrolling : es2015 as esm2015
Compiling @angular/cdk/portal : es2015 as esm2015
Compiling @angular/cdk/keycodes : es2015 as esm2015
Compiling @angular/cdk/overlay : es2015 as esm2015
Compiling ng-zorro-antd/core/types : es2015 as esm2015
Compiling @angular/common/http : es2015 as esm2015
Compiling @ant-design/icons-angular : es2015 as esm2015
Compiling ng-zorro-antd/core/environments : es2015 as esm2015
Compiling ng-zorro-antd/core/logger : es2015 as esm2015
Compiling ng-zorro-antd/core/util : es2015 as esm2015
Compiling ng-zorro-antd/core/polyfill : es2015 as esm2015
Compiling @angular/cdk/layout : es2015 as esm2015
Compiling ng-zorro-antd/core/services : es2015 as esm2015
Compiling ng-zorro-antd/core/config : es2015 as esm2015
Compiling @angular/cdk/observers : es2015 as esm2015
Compiling @angular/cdk/a11y : es2015 as esm2015
Compiling @angular/animations : es2015 as esm2015
Compiling @angular/animations/browser : es2015 as esm2015
Compiling @angular/platform-browser/animations : es2015 as esm2015
Compiling ng-zorro-antd/core/time : es2015 as esm2015
Compiling ng-zorro-antd/i18n : es2015 as esm2015
Compiling @ant-design/icons-angular/icons : es2015 as esm2015
Compiling ng-zorro-antd/icon : es2015 as esm2015
Compiling ng-zorro-antd/core/transition-patch : es2015 as esm2015
Compiling ng-zorro-antd/core/wave : es2015 as esm2015
Compiling ng-zorro-antd/button : es2015 as esm2015
Compiling ng-zorro-antd/core/no-animation : es2015 as esm2015
Compiling ng-zorro-antd/core/outlet : es2015 as esm2015
Compiling ng-zorro-antd/pipes : es2015 as esm2015
Compiling ng-zorro-antd/modal : es2015 as esm2015
Compiling @angular/forms : es2015 as esm2015
Compiling ng-zorro-antd/input : es2015 as esm2015
Compiling ng-zorro-antd/core/animation : es2015 as esm2015
Compiling ng-zorro-antd/message : es2015 as esm2015
Compiling ng-zorro-antd/notification : es2015 as esm2015
Compiling ng-zorro-antd/grid : es2015 as esm2015
Compiling ng-zorro-antd/core/color : es2015 as esm2015
Compiling ng-zorro-antd/core/overlay : es2015 as esm2015
Compiling ng-zorro-antd/tooltip : es2015 as esm2015
Compiling ng-zorro-antd/form : es2015 as esm2015
Compiling ng-zorro-antd/popconfirm : es2015 as esm2015
Compiling ng-zorro-antd/card : es2015 as esm2015
Compiling @angular/router : es2015 as esm2015
Compiling ng-zorro-antd/menu : es2015 as esm2015
Compiling ng-zorro-antd/layout : es2015 as esm2015
Compiling ng-zorro-antd/checkbox : es2015 as esm2015
Compiling ng-zorro-antd/core/resize-observers : es2015 as esm2015
Compiling ng-zorro-antd/dropdown : es2015 as esm2015
Compiling ng-zorro-antd/empty : es2015 as esm2015
Compiling ng-zorro-antd/select : es2015 as esm2015
Compiling ng-zorro-antd/pagination : es2015 as esm2015
Compiling ng-zorro-antd/radio : es2015 as esm2015
Compiling ng-zorro-antd/spin : es2015 as esm2015
Compiling ng-zorro-antd/table : es2015 as esm2015
Compiling ng-zorro-antd/tabs : es2015 as esm2015
Compiling ng-zorro-antd/tag : es2015 as esm2015
Compiling ng-zorro-antd/rate : es2015 as esm2015
Compiling ng-zorro-antd/switch : es2015 as esm2015
Compiling @angular/cdk/drag-drop : es2015 as esm2015
Compiling ng-zorro-antd/popover : es2015 as esm2015
Compiling ng-zorro-antd/slider : es2015 as esm2015
Compiling ng-zorro-antd/carousel : es2015 as esm2015
- Generating browser application bundles...
✔ Browser application bundle generation complete.
- Generating ES5 bundles for differential loading...
✔ ES5 bundle generation complete.
- Copying assets...
✔ Copying assets complete.
- Generating index html...
✔ Index html generation complete.
Initial Chunk Files | Names | Size
main-es5.9b204bd311d1245c9068.js | main | 1.36 MB
main-es2015.9b204bd311d1245c9068.js | main | 1.24 MB
styles.d8ad12d9e32d2aa12352.css | styles | 1.12 MB
polyfills-es5.908c2ddeeb7bc6aeb0a7.js | polyfills-es5 | 131.97 kB
polyfills-es2015.e70d50847bb23848ddaa.js | polyfills | 36.11 kB
runtime-es2015.b73667a77b6a42c08f57.js | runtime | 1.45 kB
runtime-es5.b73667a77b6a42c08f57.js | runtime | 1.45 kB
| Initial ES5 Total | 2.61 MB
| Initial ES2015 Total | 2.40 MB
Build at: 2021-12-03T18:51:28.367Z - Hash: 30295442766962dc8786 - Time: 168974ms
Warning: /home/app/repo/src/view/system/web/index.component.ts depends on 'file-saver'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
Warning: bundle initial-es2015 exceeded maximum budget. Budget 2.00 MB was not met by 405.82 kB with a total of 2.40 MB.
Warning: bundle initial-es5 exceeded maximum budget. Budget 2.00 MB was not met by 623.20 kB with a total of 2.61 MB.
Done in 179.54s.
We could not detect an index.html file in your publish folder. Client side applications need to have an index.html file in the top level of the published folder.`

**Comment by xjh22222228** [comment]
什么意思？部署失败？你上次是怎么部署的。

**Comment by xjh22222228** [comment]
我这边试了下打包都是正常的。

**Comment by aifact** [comment]
> 什么意思？部署失败？你上次是怎么部署的。

是我忘了删除了部署配置文件
参考部署文档，我才反应过来
https://www.stormkit.io/docs/deployments/configuration/angular
