### ISSUE TITLE
bug：side主题，点击左侧二级标题，右侧的页面不能跳转到合适的位置，其他主题也有该问题

### ISSUE THREAD

**Issue by aifact** [xjh22222228/nav#165]

**Comment by xjh22222228** [comment]
跳到什么合适的位置？ 没明白。

**Comment by aifact** [comment]
跳转到工作区，就是置顶图标的在顶部，三级列表默认是收起来的状态，这样进入导航站工作状态，作为工作区

**Comment by aifact** [comment]
> 跳转到工作区，就是置顶图标的在顶部，三级列表默认是收起来的状态，这样进入导航站工作状态，作为工作区
> 
> 现在side主题的左侧标题栏，滚动到最后，点击二级标题，右侧页面不滚动到列表，也不展示所有三级标题列表 ![image](https://user-images.githubusercontent.com/79238945/144741437-50408c58-aef1-4278-9fc9-d83351e33300.png)
> 
> 建议点击二级标题，右侧页面跳转成，固定快捷标签置顶，三级列表默认收起，然后搜索变成右侧悬浮按钮 ![image](https://user-images.githubusercontent.com/79238945/144741799-92dd166f-c6a7-44e9-8f55-d8afb0cdb520.png)

如果可能，搜索按钮，可以直接呼出搜索悬浮框

**Comment by aifact** [comment]
已测试fix(side): scroll

还有一个问题，二级标题后的合并按钮，当点击合并时，未将顶部快捷标签，固定到顶部

![image](https://user-images.githubusercontent.com/79238945/145782429-e49602ff-60d1-4a61-8d7c-6bc74eae0eed.png)

还有一个，进入快捷标签置顶后，搜索按钮怎么添加，是添加到快捷标签栏的最后，还是右下悬浮快捷按钮栏

**Comment by aiyou9** [comment]
Side主题，现在浏览时，会将固定快捷方式，置顶，但是不是要给一个快速进入搜索的方式，比如按钮啥的？

**Comment by aifact** [comment]
side主题，浏览时，将固定的快捷方式图标，作为顶部，

但是此时，搜索功能就无法，快速进入，进行搜索，需要滚动到顶部

能不能在切换主题的上面，加个搜索按钮，用于切换到搜索，甚至是呼出悬浮搜索窗口。
