### ISSUE TITLE
自动化部署空间的可用性检测

### ISSUE THREAD

**Issue by aifact** [xjh22222228/nav#166]
本项目最佳使用，还是直接fork，然后自动化部署，比较快，尤其是netlify，build速度快，建议提供netlify，vercel等自动化部署的可用性检测，参考案例

https://github.com/facebook/docusaurus

中的netlify可部署性检测!

[Screenshot_20211206_151757_com.github.android.jpg](https://user-images.githubusercontent.com/79238945/144804161-273c9bcb-d614-4375-9a97-766cf3202a66.jpg)

**Comment by xjh22222228** [comment]
没懂做什么

**Comment by aifact** [comment]
> 没懂做什么
就是在readme中，加个netlify自动部署的是否成功的状态
![image](https://user-images.githubusercontent.com/79238945/144857086-5b36c31f-8e27-4d0b-a500-6bf21e9d7271.png)
