### ISSUE TITLE
fix: some black style in nav admin system is slowly loading

### ISSUE THREAD

**Issue by aifact** [xjh22222228/nav#167]
![image](https://user-images.githubusercontent.com/79238945/144879464-e6deee0f-bdde-4cb4-a1c0-e15e573ae66b.png)

**Comment by aifact** [comment]
感觉是黑暗css的残留，因为一刷新，就没有黑暗模式了，后台没有黑暗模式？

**Comment by aifact** [comment]
好多了，但是黑色背景切换，还有一些慢，后台是没有黑暗模式吗？

**Comment by xjh22222228** [comment]
后台主要是自己用的，没有暗黑。
