### ISSUE TITLE
bug：添加搜索引擎，没有填网址的文本框

### ISSUE THREAD

**Issue by aifact** [xjh22222228/nav#169]
![image](https://user-images.githubusercontent.com/79238945/144895951-87fcebff-c1f1-4833-bfc3-ee0feefb5ed5.png)

**Comment by xjh22222228** [comment]
填什么网址？ 引擎地址就是

**Comment by aifact** [comment]
> 填什么网址？ 引擎地址就是

是新添加一个引擎，引擎地址都没有输入网址的文本框，没地方填写，例如我添加的ECOSIA
