### ISSUE TITLE
寻求支持，token权限具体选项，便于安全管理

### ISSUE THREAD

**Issue by aifact** [xjh22222228/nav#173]

**Comment by aifact** [comment]
1，使用github page，为了安全，账户与应用的token选择的最少权限，有哪些？

2.如果不使用github page，使用vercel部署，需要设置什么样token，需要选择哪些权限

**Comment by xjh22222228** [comment]
应该只要勾选 repo 和 user 就可以。

**Comment by aifact** [comment]
> 应该只要勾选 repo 和 user 就可以。

好的，我添加到navdoc里
