### ISSUE TITLE
网站管理，删除分类后，对删除数据，是否添加可选的选项

### ISSUE THREAD

**Issue by aifact** [xjh22222228/nav#175]
当前删除分类，是删除分类下所有数据
是否可以添加一个功能
给一个删除的可选项

一个是删除数据
一个是将删除分类下的数据，保存到该层分类中的未分类（如果没有就新建一个分类）

是否有必要
感觉还是浏览器中管理，比较方便

**Comment by xjh22222228** [comment]
删除分类不就是想删除这个分类下的所有数据吗 ，否则就是重命名。

**Comment by aifact** [comment]
> 删除分类不就是想删除这个分类下的所有数据吗 ，否则就是重命名。

确实，这功能没必要。关闭了
