### ISSUE TITLE
nav使用文档

### ISSUE THREAD

**Issue by aifact** [xjh22222228/nav#176]
套个壳，加载快点
https://navdoc.super.site/

**Comment by aifact** [comment]
> https://aiyou9.notion.site/git-Nav-9b10c8ce6e5547a394a63420c57e7355

套个壳，加载快点
https://navdoc.super.site/

**Comment by aifact** [comment]
套个壳，加载快点
https://navdoc.super.site/

**Comment by aiyou9** [comment]
创建了一个交流qq群，有兴趣可以加群聊
扫二维码

![Nav导航部署使用群二维码](https://user-images.githubusercontent.com/15712822/147861505-5561bd10-af6b-44df-b858-4a16f6bf2dbf.png)

或点击下图链接

<a target="_blank" href="https://qm.qq.com/cgi-bin/qm/qr?k=m5Bt2uMgUM-8xo7VJPa_i7hWQFjCda3M&jump_from=webapi"><img border="0" src="//pub.idqqimg.com/wpa/images/group.png" alt="Nav导航部署使用" title="Nav导航部署使用"></a>
