### ISSUE TITLE
system does not work

### ISSUE THREAD

**Issue by wanghaisheng** [xjh22222228/nav#177]
利用cloudcannon部署很简单，首页是能访问的
https://scenic-cranberry.cloudvent.net/#/light

但system后台页显示一片空白
步骤3里的token也有申请

https://scenic-cranberry.cloudvent.net/#/system/

**Comment by aifact** [comment]
> 利用cloudcannon部署很简单，首页是能访问的 https://scenic-cranberry.cloudvent.net/#/light
> 
> 但system后台页显示一片空白 步骤3里的token也有申请
> 
> https://scenic-cranberry.cloudvent.net/#/system/
我用我的token登录了进入，没问题，你再试试，检查一下你的token

![image](https://user-images.githubusercontent.com/79238945/146231752-564e6cfe-b481-4a88-afe7-50d4e12f457b.png)

**Comment by wanghaisheng** [comment]
果然 这个cloudcannon似乎部署以后有延迟
同样的操作我现在也能看到输入token的地方了

**Comment by aifact** [comment]
参考一下中文readme，英文翻译有问题


3、到 https://github.com/用户名/nav/settings/secrets/new 添加刚刚申请的token， name填写 TOKEN 大写。
这里翻译有问题， 添加刚刚申请的token

4s://github.com/xjh22222228/nav/tree/v3

**Comment by wanghaisheng** [comment]
4是啥  应该就是这个 我重新改了下 好像还是401
![image](https://user-images.githubusercontent.com/2363295/146235365-455b7bbe-ed3b-42a0-b8ef-4ea24fa4c7ff.png)

**Comment by aifact** [comment]
> 4是啥 应该就是这个 我重新改了下 好像还是401 ![image](https://user-images.githubusercontent.com/2363295/146235365-455b7bbe-ed3b-42a0-b8ef-4ea24fa4c7ff.png)

就是之前的token，粘贴到value，命名为TOKEN
![image](https://user-images.githubusercontent.com/79238945/146235757-2311ac12-9569-45d3-86f0-b9af4fd82bf3.png)

**Comment by wanghaisheng** [comment]
就是我图里面的repository token把
没有啥格式要求把？

**Comment by aifact** [comment]
![image](https://user-images.githubusercontent.com/79238945/146236498-e6594c90-2b9a-4d27-9bdf-3ee6a4494582.png)

**Comment by aifact** [comment]
> 我核实一下 需要2个token 1.Personal access tokens
> 
> 2.就是我图里面的repository token把
> 
> 那么 请在下方输入您的TOKEN进行登录校验 用的1还是2
> 
> 我看懂了 1.申请Personal access tokens 然后把值复制出来 2.在repository token里新建一个名称为TOKEN 值为1中复制的内容

把1复制到2

**Comment by wanghaisheng** [comment]
恩 我搞懂了
先前repository token我是自己生成的 死活不对

**Comment by wanghaisheng** [comment]
我看了你写的文档 好齐全
花了不少功夫把
@aifact

**Comment by aifact** [comment]
> repository token

一天

**Comment by aifact** [comment]
> 

感谢你的反馈，token那里，我也是看英文，糊里糊涂，看原来中文，英文翻译有错误

**Comment by wanghaisheng** [comment]
我是起初没看懂 为啥要两个token 
后面这个我懂 肯定是要往repo写静态数据
前面那个我没看明白用来干啥

**Comment by aifact** [comment]
> 我核实一下 需要2个token 1.Personal access tokens
> 
> 2.就是我图里面的repository token把
> 
> 那么 请在下方输入您的TOKEN进行登录校验 用的1还是2
> 
> 我看懂了 1.申请Personal access tokens 然后把值复制出来 2.在repository token里新建一个名称为TOKEN 值为1中复制的内容

1、是github账户的访问token，是可以通过部署js代码中web api，访问github
2、是通过授权action获得token授权，获得处理nav库的权限，进行库data文件下文件的编辑，以及产生github page
所以需要将token授权给action

我的理解不知道对不对
即使是部署在自己服务器上（我没做过，不是很清楚），可能也是要用静态文件中的js代码，通过github账户的访问token，登录github，操作github远程nav库的data文件的，需要把当前更新，推送到github的库中

**Comment by wanghaisheng** [comment]
主要是数据写入 达到一个实时效果
数据读的话 应该是不要token的 不论是全局还是repo

**Comment by aifact** [comment]
> 主要是数据写入 达到一个实时效果 数据读的话 应该是不要token的 不论是全局还是repo

不是实时，是需要重新buid静态文件，5-10min延迟，
数据写入是部署网页的js，通过github webapi，以token登录，将浏览器中网页修改内容，推送到github nav库中，
数据读，是部署的自动化编译空间，监控github 库的提交，自动进行静态文件的重新build

与php动态网站，不一样，那个是mysql数据库，实时读写

**Comment by wanghaisheng** [comment]
难道不就是通过github action里的js去读写https://github.com/xjh22222228/nav/tree/main/data下的json文件吗

**Comment by aifact** [comment]
> 难道不就是通过github action里的js去读写[https://github.com/xjh22222228/nav/tree/main/data下的json文件吗](https://github.com/xjh22222228/nav/tree/main/data%E4%B8%8B%E7%9A%84json%E6%96%87%E4%BB%B6%E5%90%97)

具体你问一下xjh22222228，我不写代码，
action的配置，参考一下https://github.com/xjh22222228/nav/blob/v3/.github/workflows/ci.yml

**Comment by wanghaisheng** [comment]
我看了一下license 不让商用。。
代码就先不研究了
@aifact

**Comment by aiyou9** [comment]
> 我看了一下license 不让商用。。 代码就先不研究了 @aifact
@xjh22222228 @wanghaisheng  
#186 如何获取项目商业化授权
最近准备淦个收费资源组，需要一个导航页，还是本项目比较好，虽然同款猿梦导航最新版本，用数据库了，但多级目录，大屏幕适配还是nav3。
商业化使用的问题，作者已经更新了，欢迎 @wanghaisheng  大佬使用，贡献代码到项目库
2022年1月21日

![屏幕截图 2022-01-21 153109](https://user-images.githubusercontent.com/15712822/150485137-2af47ba8-268a-464a-a71e-77ff24dcb598.png)

**Comment by aiyou9** [comment]
> 我看了一下license 不让商用。。 代码就先不研究了 @aifact

商业化，作者更改了，可以商用，我最近也在研究，怎么加广告，你也是要加广告的吗？

**Comment by xjh22222228** [comment]
Banner 不就可以加广告，可以跳转第三方链接。

**Comment by wanghaisheng** [comment]
@aiyou9 广告都没敢想 只是初衷是本着商业化去的 原来的license不支持 我发了邮件好像也没有理我

**Comment by aiyou9** [comment]
> 

横幅广告也不错，我的想法是，点击每个收藏网址，都有一个跳转页面，这个跳转页面上放广告，不知道是否可以在搜录网址前，加一个自己的跳转网址来实现

**Comment by xjh22222228** [comment]
你的意思是类似知乎，点击跳转确认跳转的页面改成广告页面

**Comment by wanghaisheng** [comment]
@aiyou9  看看那些广告平台的sdk 应该是可以直接套在上面
