### ISSUE TITLE
核心功能需求：扩展导航站点文件导入类型

### ISSUE THREAD

**Issue by aifact** [xjh22222228/nav#179]
这种md文件，是否能导入，
就是分类，
下面是网址后带有标签符号-（可以人为制定分割符）,后面是站点描述
这个能开发个导入功能吗？
https://github.com/ripienaar/free-for-dev/blob/master/README.md

**Comment by xjh22222228** [comment]
如果是要支持 md 文件导入，格式应该是这样：

```
- 工具
  - GUI
    - Player
      - [example](https://example.com) - Hello example.
```

**Comment by aifact** [comment]
> 如果是要支持 md 文件导入，格式应该是这样：
> 
> ```
> - 工具
>   - GUI
>     - Player
>       - [example](https://example.com) - Hello example.
> ```

一般也不会分到三级目录，
https://github.com/ripienaar/free-for-dev/blob/master/README.md
这个文件里只有一级
但是
[example](https://example.com) - Hello example
这个格式还是有的，就先导入成一级，然后自己再手动改？

**Comment by aifact** [comment]
https://www.mk2048.com/blog/blog_hb2c0h110kj.html
感觉大家都是用MD写完，转html的，直接html导入，会不会比MD简单点

**Comment by aifact** [comment]
https://www.mk2048.com/blog/blog_hb2c0h110kj.html
感觉大家都是用MD写完，转html的，直接html导入，会不会比MD简单点

**Comment by aifact** [comment]
获取所有md文件中的所有外链，生成一个Chrome书签文件
https://zhuanlan.zhihu.com/p/423855339

**Comment by aifact** [comment]
https://blog.csdn.net/snsHL9db69ccu1aIKl9r/article/details/115152782

**Comment by aifact** [comment]
> > 如果是要支持 md 文件导入，格式应该是这样：
> > ```
> > - 工具
> >   - GUI
> >     - Player
> >       - [example](https://example.com) - Hello example.
> > ```
> 
> 一般也不会分到三级目录，这个文件里只有一级
> 
> https://github.com/ripienaar/free-for-dev/blob/master/README.md 但是
> 
> ```
> [example](https://example.com) - Hello example
> ```
> 
> 这个网址加网址描述还是有的，- Hello example与前面的网址，直接拆分 github中有很多awesome都是MD格式，如https://github.com/sindresorhus/awesome
> 
> 如果能直接导入，也是很好的
> 
> 或者MD转浏览器收藏文件夹文件，可能有人已经做了，我找找
> 
> 就先导入成一级，然后自己再手动改？

还是和浏览器收藏夹一样，哪一级没有，就归为未分类，这样方便一些

**Comment by xjh22222228** [comment]
不用转浏览器，直接就能解析，得有个格式，网址存到哪个分类下

**Comment by aifact** [comment]
> 不用转浏览器，直接就能解析，得有个格式，网址存到哪个分类下

嗯，直接转，md格式兼容性还得高点，比如
1、一般来说，md中目录层级都是使用标题格式，但一般大家都是一级，或两级标题分类，为了支持nav3的三级，还是将层级缺失的放未分类，未分类是否有必要区分哪次导入？比如，以在界面给个输入框，加上未未分类的标志词？比如这次我导入的是awesome python，下次我导入的是awesome js，每次都给个输入框，自己填一些标志词，比如第一次在输入框里填python，就是python-未分类，第二次js就是js未分类

不过感觉还是用浏览器插件，在浏览器收藏夹里管理员更快，可以拖动，批量调整分类。不知道nav3能否实现批量管理功能，比如cubox.pro，右上角给了个勾选框，可以进入批量选择模式，然后选好了，拖动到分类中。

2、在md文件中，网址与后面网址描述，有人喜欢用-，有的人喜欢用中文—，或者空格，这在导入时，可能也需要给文本框，填一些md文件中，网址与描述间的分割标志词，比如-，_，~，—，或者汉字啥的

**Comment by aifact** [comment]
> > 不用转浏览器，直接就能解析，得有个格式，网址存到哪个分类下
> 
> 嗯，直接转，md格式兼容性还得高点，比如
> 1、一般来说，md中目录层级都是使用标题格式，但一般大家都是一级，或两级标题分类，为了支持nav3的三级，还是将层级缺失的放未分类，未分类是否有必要区分哪次导入？比如，以在界面给个输入框，加上未未分类的标志词？比如这次我导入的是awesome python，下次我导入的是awesome js，每次都给个输入框，自己填一些标志词，比如第一次在输入框里填python，就是python-未分类，第二次js就是js未分类
> 
> 不过感觉还是用浏览器插件，在浏览器收藏夹里管理员更快，可以拖动，批量调整分类。不知道nav3能否实现批量管理功能，比如
> 
> https://cubox.pro
> 
> 右上角给了个勾选框，可以进入批量选择模式，然后选好了，拖动到分类中。
> 
> 2、在md文件中，网址与后面网址描述，有人喜欢用-，有的人喜欢用中文—，或者空格，这在导入时，可能也需要给文本框，填一些md文件中，网址与描述间的分割标志词，比如-，_，~，—，或者汉字啥的

网址超链接与描述间还有可能是帽号，还有分割，可能只分割第一个分割符

**Comment by aifact** [comment]
大部分导航，awesome等html，和md文件中，都是一层，两层目录层级都很少，MD和html之间能够相互转化，能导入md中网址，就可以扩大收集范围。最后nav3成了合并md网址列表，和浏览器网址收藏文件夹的工具，哈哈！！
