### ISSUE TITLE
如何获的本项目的商业使用授权

### ISSUE THREAD

**Issue by aifact** [xjh22222228/nav#186]

**Comment by xjh22222228** [comment]
不用授权。

**Comment by aiyou9** [comment]
最近没关注项目，原来更新了商业授权，感 谢 @xjh22222228  最近正好需要商业化使用。谢谢！
![屏幕截图 2022-01-21 153109](https://user-images.githubusercontent.com/15712822/150485317-d17307d0-abb4-44e2-ba33-2728583bb67e.png)
