### ISSUE TITLE
是否有计划，开发付费支持的商业高级版？

### ISSUE THREAD

**Issue by aifact** [xjh22222228/nav#187]
比如#152 所说，结合我自己的想法，一些可以作为付费的商业高级版，开发：
1 批量删除，批量管理
2 导入不同格式的网址收藏文件
3 接入爬虫接口
4  接入广告平台api接口，自动添加跳转，广告页，自动短链
5 本地对接的浏览器插件
6 NLP人工智能，推荐分类，与自动分类 #183 
……等等

**Comment by xjh22222228** [comment]
目前还没考虑， 感觉这东西没什么价值。

**Comment by aifact** [comment]
嗯，好的，开源项目商业化，确实不容易
