### ISSUE TITLE
导出功能：导出本地浏览器收藏夹能导入的html文件格式？

### ISSUE THREAD

**Issue by aiyou9** [xjh22222228/nav#190]
需求场景
在nav3.cn部署网页上，多人一起收集，然后网址有很多，需要重新整理分类，还是要到浏览器中，使用浏览器插件，才能快速整理分类。

需求功能：
增加一个导出按钮
从nav3.cn网页，导出本地浏览器收藏夹可导入的HTML文件

**Comment by aiyou9** [comment]
我为这个功能，捐赠了，请大佬研究一下

**Comment by xjh22222228** [comment]
可以研究一下， 这个功能不好实现， 主要是没有导出规范，也没有文档， 需要点时间研究下规则。

**Comment by xjh22222228** [comment]
1、如果做这个功能会有一些问题，一个网站会有多个url(英文、中文...)，导出就会有多条数据。
2、导出后再导入不能无缝还原，因为这个是浏览器处理的，部分设置会丢失（描述、快捷方式等设置都会没有）。

**Comment by aiyou9** [comment]
> 1、如果做这个功能会有一些问题，一个网站会有多个url(英文、中文...)，导出就会有多条数据。 

确实，这个场景是，如何同步nav与浏览器收藏夹，能不能导出时，对一个网站相关联的url，导出浏览器收藏栏导入文件时，处理为浏览器中，同一个文件夹下的，但是带有匹配的标签，比如这个网站的网址，然后加上中文、英文的等标签，然后从浏览器收藏栏导出文件，导入NAV，能够将这些带有标签的网址，对应着处理，关联到相应的网站上。


2、导出后再导入不能无缝还原，因为这个是浏览器处理的，部分设置会丢失（描述、快捷方式等设置都会没有）。

主要功能是同步浏览器收藏夹的网址，这写描述不需要在浏览器收藏栏中，可能目录层级，可以处理成浏览器收藏栏的网址标签，具体的描述都在Nav上，并不需要在浏览器收藏栏中显示，浏览收藏栏的标签可以做一些处理

**Comment by aifact** [comment]
https://www.ituring.com.cn/book/1421   chrome浏览器，插件开发教程

**Comment by xjh22222228** [comment]
跟插件没关系，这个不依赖Chrome扩展。  需要将数据转换成 HTML 文件。 问题在于这个HTML文件的格式比较严格，少一个空格都会失败。

**Comment by aiyou9** [comment]
> 

好的，我去找找有没有相关的 json  转 这种要求严格的HTML 的现成解决方案

**Comment by aiyou9** [comment]
1、最后一个回答，https://cloud.tencent.com/developer/ask/sof/250455
2、python3 谷歌、火狐浏览器书签导出文件格式化JSON数据输出；https://gitee.com/nxqf/browser-bookmarks-parser
3、https://github.com/moappi/json2html    文档http://www.json2html.com/
4、现成的转换包 https://github.com/search?o=desc&q=bookmark-parser&s=stars&type=Repositories  
npm上也有这个包bookmark-parser  https://github.com/calibr/node-bookmarks-parser

**Comment by xjh22222228** [comment]
提供的这些都没什么用途，基本上都是HTML解析为JSON，  需要的是 JSON 解析为 HTML，目前我还没找到有哪个开源实现出来的。

**Comment by aiyou9** [comment]
> JSON 解析为 HTML

http://www.json2html.com/ 这个也不是？  
我再去找找

**Comment by aiyou9** [comment]
> > 提供的这些都没什么用途，基本上都是HTML解析为JSON， 需要的是 JSON 解析为 HTML，目前我还没找到有哪个开源实现出来的。
> > 这个好像可以，但是有指定格式
> > https://github.com/1nfiniteloop/json-bookmarks

@xjh22222228 大佬看看这个是否能够实现，谢谢
