### ISSUE TITLE
同步到远端时发生404错误

### ISSUE THREAD

**Issue by ariaxo** [xjh22222228/nav#194]
“同步失败，请重试”
请问应该如何解决呢？

**Comment by xjh22222228** [comment]
重新Fork,  Token 是否正确

**Comment by aiyou9** [comment]
中文readme： https://github.com/xjh22222228/nav/blob/main/README_zh-CN.md
自己淦的使用手册  https://navdoc.super.site/8-using-instruction

**Comment by ariaxo** [comment]
重新fork，获取token并写入后依然无法同步，报错Request failed with status code 404
可以麻烦看一下怎么回事吗（哭

**Comment by xjh22222228** [comment]
按照教程来没。我看你仓库都没触发构建。

**Comment by Kkwoai** [comment]
可以查看一下nav.config.ts文件内的仓库地是否更改 我的就是这个地址没有改

**Comment by jqzhang0126** [comment]
我的也是404，没办法通过后台修改数据

**Comment by yumc78** [comment]
用着突然就无法同步了404错误

**Comment by ZDY321** [comment]
> 按照教程来没。我看你仓库都没触发构建。



> 重新Fork, Token 是否正确

大佬你好，我用这个导航主题时同步也是会出现404的错误，重新Fork, Token之后也是无法解决

**Comment by 88lin** [comment]
我也是404，怎么解决啊

**Comment by jqzhang0126** [comment]
没解决了，挂着网盘不掉就没管了

 

发件人: ***@***.*** ***@***.***> 代表 你好呀
发送时间: 2023年1月2日 22:30
收件人: xjh22222228/nav ***@***.***>
抄送: jqzhang0126 ***@***.***>; Comment ***@***.***>
主题: Re: [xjh22222228/nav] 同步到远端时发生404错误 (Issue #194)

 

我也是404，怎么解决啊

**Comment by 88lin** [comment]
有没有解决办法，重新fork也没有用

**Comment by xjh22222228** [comment]
大哥们，你们是不是没有权限，都勾选了吗。 @88lin  我看你的vercel 都构建失败。

**Comment by 88lin** [comment]
@xjh22222228 我全勾选了

**Comment by enweny** [comment]
有人遇到Request failed with status code 404的吗？
nav.config.ts文件内的仓库地址我改了，token权限也选了repo 和 user

**Comment by huashengrun** [comment]
我也遇到了，权限都给了

**Comment by koltluo** [comment]
后台设置点保存的时候，显示403同步失败是怎么回事？
![FireShot Capture 008 - 发现导航 - 精选实用导航网站 - book nav8 top](https://github.com/xjh22222228/nav/assets/144575750/355a92dd-6a9d-45cb-b8a2-42de9d895ce6)
