### ISSUE TITLE
添加的数据丢失的问题

### ISSUE THREAD

**Issue by mucstudio** [xjh22222228/nav#201]
通过后台添加了一批数据。当天晚上没有同步，第二天起来发现昨晚添加的网址数据都没了，

**Comment by aiyou9** [comment]
> 通过后台添加了一批数据。当天晚上没有同步，第二天起来发现昨晚添加的网址数据都没了，

没有同步，就在浏览器的cookie里，关闭浏览器，可能会自动清除，建议平时收集到浏览器收藏栏，然后导入，因为支持增量导入

可参考我淦的教程：https://blog.xbreeding.com/KLaVVy-2Q/

**Comment by mucstudio** [comment]
感谢 已经处理好了  我忘记了点击同步！！
