### ISSUE TITLE
在提一个新问题 能否增加一个分类排序的功能

### ISSUE THREAD

**Issue by mucstudio** [xjh22222228/nav#202]
目前分类排序都是按照默认添加类目的时间排序的 

是否可以自定义排序顺序位置呢 

因为网址导航内容会不断的补充和完善，那么后面肯定会又新增的类目，但是考虑到实用性以及常用性，有些经常使用的会考虑放到最前面去。

**Comment by xjh22222228** [comment]
支持排序的吧？ 长按列表拖动？

**Comment by mucstudio** [comment]
我试试

**Comment by mucstudio** [comment]
果然可以 谢谢 又学到了
