### ISSUE TITLE
请问支持宝塔部署吗？

### ISSUE THREAD

**Issue by zailushang2008** [xjh22222228/nav#203]
我们都在国内，部署在github访问打不都打不开，这有什么用。

**Comment by xjh22222228** [comment]
目前是需要依赖Github来管理，  希望有人能给出一个方案， 尽量不依赖数据库， 可以增加服务端来支撑。

**Comment by aiyou9** [comment]
> 目前是需要依赖Github来管理， 希望有人能给出一个方案， 尽量不依赖数据库， 可以增加服务端来支撑。

服务端安装  local action，像github那样一样处理源代码，生成静态页面，以前issue，有调研过

**Comment by abcmiao** [comment]
> > 目前是需要依赖Github来管理， 希望有人能给出一个方案， 尽量不依赖数据库， 可以增加服务端来支撑。
> 
> 服务端安装 local action，像github那样一样处理源代码，生成静态页面，以前issue，有调研过

请问这个local action 是啥东西，也查不到，也不知道怎么搞。求详细指点

**Comment by aifact** [comment]
> > > 目前是需要依赖Github来管理， 希望有人能给出一个方案， 尽量不依赖数据库， 可以增加服务端来支撑。
> > 
> > 
> > 服务端安装 local action，像github那样一样处理源代码，生成静态页面，以前issue，有调研过
> 
> 请问这个local action 是啥东西，也查不到，也不知道怎么搞。求详细指点

https://github.com/jonico/awesome-runners

**Comment by yumc78** [comment]
看到一个博主有docker安装在本地，不知道怎么操作的

**Comment by aiyou9** [comment]
> docker

有网址吗？

**Comment by aiyou9** [comment]
官方文档： https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners#self-hosted-runner-security-with-public-repositories
博文：
https://testdriven.io/blog/github-actions-docker/
近期持续更新的项目
https://github.com/myoung34/docker-github-actions-runner

**Comment by gebangfeng** [comment]
>如果是企业里用倒是还方便，

我是要给企业做个内部导航。
**我的是一个半自动方案**
## 说说我是怎么用的
我们内部构建服务是有gitlab和jenkins
首先我在gitlab上创建了一个nav仓库,接着在jenkins配置了要给pipeline任务(负责build,打包docker镜像,更新现有服务的镜像版本),然后将gitlab和jenkins进行了打通,gitlab有变更触发jenkins构建。
## 说说添加删除导航中网址的流程
首先我在在github上创建一个token，以便进入导航的system/web后台,进入后我正常的添加网址,添加完成后我点击下载备份,我得到了db.json文件.我将这个文件中的内容复制并替换gitlab的nav仓库中的db.json文件.提交后会触发jenkins构建。等待几分钟我就能看到最新构建的网址了

**Comment by aiyou9** [comment]
> > 如果是企业里用倒是还方便，
> 
> 我是要给企业做个内部导航。 **我的是一个半自动方案**
> 
> ## 说说我是怎么用的
> 我们内部构建服务是有gitlab和jenkins 首先我在gitlab上创建了一个nav仓库，接着在jenkins配置了要给pipeline任务（负责build，打包docker镜像，更新现有服务的镜像版本），然后将gitlab和jenkins进行了打通，gitlab有变更触发jenkins构建。
> 
> ## 说说添加删除导航中网址的流程
> 首先我在github上创建一个token，以便进入导航的system/web后台，进入后我正常的添加网址，添加完成后我点击下载备份，我得到了db.json文件.我将这个文件中的内容复制并替换gitlab的nav仓库中的db.json文件.提交后会触发jenkins构建。等待几分钟我就能看到最新构建的网址了

chrome 内核的书签同步插件，可以进行协作了  https://floccus.org/

**Comment by marklove5102** [comment]
我给onenav写了个c++后台。不喜欢php部署太麻烦。

**Comment by aiyou9** [comment]
> 我们都在国内，部署在github访问打不都打不开，这有什么用。
部署到netlify.com

**Comment by ggtony233** [comment]
这个项目能否部署到nginx上？

**Comment by ggtony233** [comment]
我尝试将这个项目打包到nginx再封装到docker中，跑起来似乎还好
![下载](https://github.com/xjh22222228/nav/assets/72987782/6e9ce251-f746-433a-bc9c-a01878ca2867)

```log
REPOSITORY                        TAG            IMAGE ID       CREATED          SIZE
mynewnav                          test           4e459f725373   44 seconds ago   44.8MB
```

这是打包好的镜像大小
但我打开控制台发现任然存在一些报错，不知道这些报错影响大吗？
![2024-01-24_16-21](https://github.com/xjh22222228/nav/assets/72987782/1649961d-ccf0-4351-9b62-10a16c8e82d9)
然后我的过程是这样的:  
1. 在服务器上安装docker
2. 随便建了个文件夹
3. 然后在文件夹里面写了一个下面内容的dockerfile
```dockerfile
FROM extensions/git-clone:latest AS nav
RUN git clone git clone https://ghproxy.net/https://github.com/xjh22222228/nav.git /root/mynav
FROM node:18.19.0-bullseye AS install
COPY --from=nav /root/mynav /root/mynav
WORKDIR /root/mynav 
RUN yarn install&&yarn build
FROM nginx:alpine
COPY --from=install /root/mynav/dist/ /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
```
4. `docker build -t mynewnav:test -f ./<dockerfile的文件名> .`
5.  然后运行`docker run --rm -p 48081:80 -d mynewnav:test`就出现了上面的页面和f12所的一些问题

@xjh22222228 这些报错对网页使用有影响吗？

**Comment by xjh22222228** [comment]
@ggtony233 没问题
