### ISSUE TITLE
yarn bulid 后，打开dist/index.html一直加载中

### ISSUE THREAD

**Issue by fulige18** [xjh22222228/nav#206]
### Version
6.0.1

### Reproduction link
[file:///D:/nav-main/dist/index.html](file:///D:/nav-main/dist/index.html)

### Steps to reproduce
正常按说明步骤来构建

### What is expected?
能正常加载
![QQ拼音截图20220415135938](https://user-images.githubusercontent.com/100845677/163527957-85f01010-ffa1-42cb-9ad3-7e7aa78e60e4.png)

### What is actually happening?
无法加载

**Comment by xjh22222228** [comment]
你需要丢到服务器，而不是直接打开
