### ISSUE TITLE
反馈两个小问题

### ISSUE THREAD

**Issue by Muyuoop** [xjh22222228/nav#208]
### What problem does this feature solve?
1. Light主题下，二级标题不能滑动，如果二级标题过多超过窗口，后面的就点不到了。
2. sim主题下，主标题目前没有居中，居中会更好看一些。

### What does the proposed API look like?
希望Light的二级标题增加滑动窗口
希望sim主题标题居中

**Comment by yzmbf30** [comment]
做为新手，看都没看懂怎么安装部署的，网上都找不到有谁安装过

**Comment by Muyuoop** [comment]
> 做为新手，看都没看懂怎么安装部署的，网上都找不到有谁安装过

我刚搭建好，其实安装说明已经很详细了，有问题的话可以私信我，muyuoop@qq.com。

**Comment by aiyou9** [comment]
> 做为新手，看都没看懂怎么安装部署的，网上都找不到有谁安装过
可参考一下这个文档
https://navdoc.super.site/
