### ISSUE TITLE
改网站logo的疑问

### ISSUE THREAD

**Issue by foxdodo** [xjh22222228/nav#211]
尝试直接在网页后台上传logo并保存, 图片也是200x200像素 png格式, 发现图片是传到了image分支, 但是导航页的logo并没有改变. 
这是只能自己修改github代码来改logo的吗? 还是有什么图片命名格式要求?

**Comment by xjh22222228** [comment]
你指的是哪个不生效， 点保存没有。

**Comment by foxdodo** [comment]
> 你指的是哪个不生效， 点保存没有。

上传成功, 也点了页面最底部的保存按钮
构建成功后网页的logo还是不变
![image](https://user-images.githubusercontent.com/3275698/166216790-91ac6052-ec90-4188-b09e-6349104b1036.png)

**Comment by xjh22222228** [comment]
是不是有缓存？ 方便发下地址吗。

**Comment by foxdodo** [comment]
> 是不是有缓存？ 方便发下地址吗。

https://n.faplist.ml/

上一个版本我是在github改了setting文件才能改logo, 然后你一更新后我这菜鸡玩不来github合并上游, 每次你更新我都删了库重新fork好麻烦🤣

**Comment by xjh22222228** [comment]
不好意思，已经修复了。 你可以学下怎么合并， 不需要重新Fork。
