### ISSUE TITLE
求教shortcut主题的图标手动排序问题

### ISSUE THREAD

**Issue by foxdodo** [xjh22222228/nav#212]
尝试拖动shortcut主题下的图标, 发现被拖动的图标根本不跟我拖动的方向走, 倒是其他图标移动了, 这移动看得我有点蒙逼.
请问这是没有拖动功能还是需要去github后台代码自己修改排序?

**Comment by xjh22222228** [comment]
我这边试了下，没什么问题。

**Comment by foxdodo** [comment]
> 我这边试了下，没什么问题。

![image](https://user-images.githubusercontent.com/3275698/167251597-e343eb98-4ca2-4545-a61a-9032dfd25a05.png)

**Comment by foxdodo** [comment]
> 我这边试了下，没什么问题。

![](https://cdn.jsdelivr.net/gh/foxdodo/picgo/img/drag.gif)
