### ISSUE TITLE
希望可以增加一个可选项可以给网站增加一个角标

### ISSUE THREAD

**Issue by fulige18** [xjh22222228/nav#213]
### What problem does this feature solve?
方便对网站有一个标签表明该类网址的特性，比如是新增的，还是热门的，是需要代理访问的还是不需要等等；

### What does the proposed API look like?
看下参考图这种
![image](https://user-images.githubusercontent.com/100845677/170640805-c465fdf4-ff1d-4b4c-91f8-fedb8237918d.png)

**Comment by xjh22222228** [comment]
OK
