### ISSUE TITLE
能否切换jsdelivr?

### ISSUE THREAD

**Issue by foxdodo** [xjh22222228/nav#214]
现在国内大部分地区jsdelivr都连接超时, 导致shortcut主题下上传的背景图刷不出来. 能否切换成其他cdn, 或者支持添加外链的shortcut主题背景图

![image](https://user-images.githubusercontent.com/3275698/170741160-8fe73858-2b63-401b-9966-6e997ec2a001.png)

**Comment by foxdodo** [comment]
刚才试了下fastly.jsdelivr.net暂时没被墙, 但感觉jsdelivr离全线被墙也不远了, 希望大佬能找个替代的cdn或者其他解决方案

**Comment by aiyou9** [comment]
> > 打开 [https://github.com/用户名/nav/actions](https://github.com/%E7%94%A8%E6%88%B7%E5%90%8D/nav/actions) 点击 绿色按钮
> 
> 321这么简单我都搞不定啊，绿色按钮找了两天也没找到在哪

https://navdoc.super.site/
