### ISSUE TITLE
怎么更新https://username.github.io/nav/#/system/info的token信息

### ISSUE THREAD

**Issue by zh3389** [xjh22222228/nav#218]
背景: 之前token设置的1个月,然后token过期了.
第一次尝试. 更新了设置里面的token, 再进行提交的时候报401错误.
第二次尝试. 尝试更新 https://username.github.io/nav/#/system/info 里面的token信息未果.
第三次尝试. 删除项目重新fork后, 部署第四步更改配置文件 nav.config.ts 后的默认部署成功. 但登录进去后之前存入https://username.github.io/nav/#/system/info 的token还在 还是不能修改, 也不能提交增加的网址 报错还是401.

**Comment by xjh22222228** [comment]
401 没有权限，检查是否勾选响应权限。

**Comment by zh3389** [comment]
> 

全部都勾选了, 想知道第一次进后台页面时 https://username.github.io/nav/#/system/info 输入的token在哪里配置.  我想看看能不能修改.
