### ISSUE TITLE
后台管理不安全

### ISSUE THREAD

**Issue by wudgaby** [xjh22222228/nav#227]
后台管理可以绕过.不安全.
部署到公网的话. 会被随意添加恶意网址.

**Comment by wudgaby** [comment]
很简单啊. 在浏览器localstore放个token=123. 然后进入后台管理就绕过了验证.
除非你每次curd的时候.都校验一次token

**Comment by xjh22222228** [comment]
是有这个问题， 但是改不了。

**Comment by xjh22222228** [comment]
3Q
