### ISSUE TITLE
GitHub page部署报错，求大佬看看

### ISSUE THREAD

**Issue by hyyxiaoluo** [xjh22222228/nav#233]
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/runner/work/nav/nav/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/runner/work/nav/nav/node_modules/webpack/lib/NormalModule.js:417:16)
    at /home/runner/work/nav/nav/node_modules/webpack/lib/NormalModule.js:452:10
    at /home/runner/work/nav/nav/node_modules/webpack/lib/NormalModule.js:323:13
    at /home/runner/work/nav/nav/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /home/runner/work/nav/nav/node_modules/loader-runner/lib/LoaderRunner.js:172:11
    at loadLoader (/home/runner/work/nav/nav/node_modules/loader-runner/lib/loadLoader.js:32:11)
    at iteratePitchingLoaders (/home/runner/work/nav/nav/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at runLoaders (/home/runner/work/nav/nav/node_modules/loader-runner/lib/LoaderRunner.js:365:2)
    at NormalModule.doBuild (/home/runner/work/nav/nav/node_modules/webpack/lib/NormalModule.js:2[95](https://github.com/hyyxiaoluo/nav/actions/runs/4652179791/jobs/8232231955#step:4:96):3)
    at NormalModule.build (/home/runner/work/nav/nav/node_modules/webpack/lib/NormalModule.js:446:15)
    at Compilation.buildModule (/home/runner/work/nav/nav/node_modules/webpack/lib/Compilation.js:739:10)
    at /home/runner/work/nav/nav/node_modules/webpack/lib/Compilation.js:[111](https://github.com/hyyxiaoluo/nav/actions/runs/4652179791/jobs/8232231955#step:4:112)1:12
    at /home/runner/work/nav/nav/node_modules/webpack/lib/NormalModuleFactory.js:409:6 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.15.0
Error: Process completed with exit code 1.
自始至终按照教程来的

**Comment by hyyxiaoluo** [comment]
vercelb部署也是一样报错，我看后台报错都是一样的，我用chatgpt分析错误是这
`这是一个 Node.js 项目的构建日志。从日志中看，该项目使用了 Angular 和 ng-zorro-antd 等框架，并在构建时遇到了错误。错误信息显示出现了一个 OpenSSL 错误，导致构建进程退出。

具体地说，错误类型是 ERR_OSSL_EVP_UNSUPPORTED，发生的位置在 node:internal/crypto/hash 模块的第 71 行，提示某一密钥处理算法不受支持。您可以检查代码中使用的加密算法是否正确，或者考虑升级 Node.js 版本或更新相关依赖库来解决该错误。`
但是自己还是不明白哪里错了，大佬们不就是五步走么，我看咱这都没人失败一样，就我这部署失败，我这都不好意思问了，我参照的https://www.xxyopen.com/2022/07/18/os/nav.html一步一步来的啊

**Comment by xjh22222228** [comment]
应该是版本太高了，试试node  v16的版本？

**Comment by hyyxiaoluo** [comment]
@xjh22222228 怎么修改版本啊，我用的GitHubpage和vercel都失败了，是哪个配置文件修改下还是咋改，我这不太会

**Comment by Double517** [comment]
可以在package.json中的start 和build中添加export NODE_OPTIONS=--openssl-legacy-provider &&

**Comment by wangAoqi666** [comment]
> 可以在package.json中的start 和build中添加export NODE_OPTIONS=--openssl-legacy-provider &&

在前面添加还是在后面添加？帮忙看下这样对吗？
<img width="1076" alt="image" src="https://user-images.githubusercontent.com/49084179/231418639-08579677-1890-417b-b11a-e42fb79d9437.png">

**Comment by khmoyu** [comment]
> Error: error:0308010C:digital envelope routines::unsupported
>     at new Hash (node:internal/crypto/hash:71:19)
>     at Object.createHash (node:crypto:133:10)
>     at module.exports (/home/runner/work/nav/nav/node_modules/webpack/lib/util/createHash.js:135:53)
>     at NormalModule._initBuildHash (/home/runner/work/nav/nav/node_modules/webpack/lib/NormalModule.js:417:16)
>     at /home/runner/work/nav/nav/node_modules/webpack/lib/NormalModule.js:452:10
>     at /home/runner/work/nav/nav/node_modules/webpack/lib/NormalModule.js:323:13
>     at /home/runner/work/nav/nav/node_modules/loader-runner/lib/LoaderRunner.js:367:11
>     at /home/runner/work/nav/nav/node_modules/loader-runner/lib/LoaderRunner.js:172:11
>     at loadLoader (/home/runner/work/nav/nav/node_modules/loader-runner/lib/loadLoader.js:32:11)
>     at iteratePitchingLoaders (/home/runner/work/nav/nav/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
>     at runLoaders (/home/runner/work/nav/nav/node_modules/loader-runner/lib/LoaderRunner.js:365:2)
>     at NormalModule.doBuild (/home/runner/work/nav/nav/node_modules/webpack/lib/NormalModule.js:2[95](https://github.com/hyyxiaoluo/nav/actions/runs/4652179791/jobs/8232231955#step:4:96):3)
>     at NormalModule.build (/home/runner/work/nav/nav/node_modules/webpack/lib/NormalModule.js:446:15)
>     at Compilation.buildModule (/home/runner/work/nav/nav/node_modules/webpack/lib/Compilation.js:739:10)
>     at /home/runner/work/nav/nav/node_modules/webpack/lib/Compilation.js:[111](https://github.com/hyyxiaoluo/nav/actions/runs/4652179791/jobs/8232231955#step:4:112)1:12
>     at /home/runner/work/nav/nav/node_modules/webpack/lib/NormalModuleFactory.js:409:6 {
>   opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
>   library: 'digital envelope routines',
>   reason: 'unsupported',
>   code: 'ERR_OSSL_EVP_UNSUPPORTED'
> }
> 
> Node.js v18.15.0
> Error: Process completed with exit code 1.
> 自始至终按照教程来的

大哥，我也出现了这个问题，请问是怎么解决的

**Comment by hyyxiaoluo** [comment]
```
> > Error: error:0308010C:digital envelope routines::unsupported
> > at new Hash (node:internal/crypto/hash:71:19)
> > at Object.createHash (node:crypto:133:10)
> > at module.exports (/home/runner/work/nav/nav/node_modules/webpack/lib/util/createHash.js:135:53)
> > at NormalModule._initBuildHash (/home/runner/work/nav/nav/node_modules/webpack/lib/NormalModule.js:417:16)
> > at /home/runner/work/nav/nav/node_modules/webpack/lib/NormalModule.js:452:10
> > at /home/runner/work/nav/nav/node_modules/webpack/lib/NormalModule.js:323:13
> > at /home/runner/work/nav/nav/node_modules/loader-runner/lib/LoaderRunner.js:367:11
> > at /home/runner/work/nav/nav/node_modules/loader-runner/lib/LoaderRunner.js:172:11
> > at loadLoader (/home/runner/work/nav/nav/node_modules/loader-runner/lib/loadLoader.js:32:11)
> > at iteratePitchingLoaders (/home/runner/work/nav/nav/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
> > at runLoaders (/home/runner/work/nav/nav/node_modules/loader-runner/lib/LoaderRunner.js:365:2)
> > at NormalModule.doBuild (/home/runner/work/nav/nav/node_modules/webpack/lib/NormalModule.js:2[95](https://github.com/hyyxiaoluo/nav/actions/runs/4652179791/jobs/8232231955#step:4:96):3)
> > at NormalModule.build (/home/runner/work/nav/nav/node_modules/webpack/lib/NormalModule.js:446:15)
> > at Compilation.buildModule (/home/runner/work/nav/nav/node_modules/webpack/lib/Compilation.js:739:10)
> > at /home/runner/work/nav/nav/node_modules/webpack/lib/Compilation.js:[111](https://github.com/hyyxiaoluo/nav/actions/runs/4652179791/jobs/8232231955#step:4:112)1:12
> > at /home/runner/work/nav/nav/node_modules/webpack/lib/NormalModuleFactory.js:409:6 {
> > opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
> > library: 'digital envelope routines',
> > reason: 'unsupported',
> > code: 'ERR_OSSL_EVP_UNSUPPORTED'
> > }
> > Node.js v18.15.0
> > Error: Process completed with exit code 1.
> > 自始至终按照教程来的
> 
> 大哥，我也出现了这个问题，请问是怎么解决的
name: Build web
on:
  push:
    branches:
      - master
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Install
      uses: sergioramos/yarn-actions/install@v6
      with:
        frozen-lockfile: true
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Build
      run: |
        npm run build
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist
```
你试试ci.yml文件改成这样

**Comment by hyyxiaoluo** [comment]
> > Error: error:0308010C:digital envelope routines::unsupported
> > at new Hash (node:internal/crypto/hash:71:19)
> > at Object.createHash (node:crypto:133:10)
> > at module.exports (/home/runner/work/nav/nav/node_modules/webpack/lib/util/createHash.js:135:53)
> > at NormalModule._initBuildHash (/home/runner/work/nav/nav/node_modules/webpack/lib/NormalModule.js:417:16)
> > at /home/runner/work/nav/nav/node_modules/webpack/lib/NormalModule.js:452:10
> > at /home/runner/work/nav/nav/node_modules/webpack/lib/NormalModule.js:323:13
> > at /home/runner/work/nav/nav/node_modules/loader-runner/lib/LoaderRunner.js:367:11
> > at /home/runner/work/nav/nav/node_modules/loader-runner/lib/LoaderRunner.js:172:11
> > at loadLoader (/home/runner/work/nav/nav/node_modules/loader-runner/lib/loadLoader.js:32:11)
> > at iteratePitchingLoaders (/home/runner/work/nav/nav/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
> > at runLoaders (/home/runner/work/nav/nav/node_modules/loader-runner/lib/LoaderRunner.js:365:2)
> > at NormalModule.doBuild (/home/runner/work/nav/nav/node_modules/webpack/lib/NormalModule.js:2[95](https://github.com/hyyxiaoluo/nav/actions/runs/4652179791/jobs/8232231955#step:4:96):3)
> > at NormalModule.build (/home/runner/work/nav/nav/node_modules/webpack/lib/NormalModule.js:446:15)
> > at Compilation.buildModule (/home/runner/work/nav/nav/node_modules/webpack/lib/Compilation.js:739:10)
> > at /home/runner/work/nav/nav/node_modules/webpack/lib/Compilation.js:[111](https://github.com/hyyxiaoluo/nav/actions/runs/4652179791/jobs/8232231955#step:4:112)1:12
> > at /home/runner/work/nav/nav/node_modules/webpack/lib/NormalModuleFactory.js:409:6 {
> > opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
> > library: 'digital envelope routines',
> > reason: 'unsupported',
> > code: 'ERR_OSSL_EVP_UNSUPPORTED'
> > }
> > Node.js v18.15.0
> > Error: Process completed with exit code 1.
> > 自始至终按照教程来的
> 
> 大哥，我也出现了这个问题，请问是怎么解决的

![image](https://user-images.githubusercontent.com/102205671/235360620-086533fa-69a5-4d44-88b1-ae11b96b2252.png)
`name: Build web
on:
  push:
    branches:
      - master
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Install
      uses: sergioramos/yarn-actions/install@v6
      with:
        frozen-lockfile: true
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Build
      run: |
        npm run build
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist`
你试试将代码改成这样，等于是降下版本，不改的话我看后台是直接下载18版本不行的，这个是16的我这边可以

**Comment by hyyxiaoluo** [comment]
> > Error: error:0308010C:digital envelope routines::unsupported
> > at new Hash (node:internal/crypto/hash:71:19)
> > at Object.createHash (node:crypto:133:10)
> > at module.exports (/home/runner/work/nav/nav/node_modules/webpack/lib/util/createHash.js:135:53)
> > at NormalModule._initBuildHash (/home/runner/work/nav/nav/node_modules/webpack/lib/NormalModule.js:417:16)
> > at /home/runner/work/nav/nav/node_modules/webpack/lib/NormalModule.js:452:10
> > at /home/runner/work/nav/nav/node_modules/webpack/lib/NormalModule.js:323:13
> > at /home/runner/work/nav/nav/node_modules/loader-runner/lib/LoaderRunner.js:367:11
> > at /home/runner/work/nav/nav/node_modules/loader-runner/lib/LoaderRunner.js:172:11
> > at loadLoader (/home/runner/work/nav/nav/node_modules/loader-runner/lib/loadLoader.js:32:11)
> > at iteratePitchingLoaders (/home/runner/work/nav/nav/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
> > at runLoaders (/home/runner/work/nav/nav/node_modules/loader-runner/lib/LoaderRunner.js:365:2)
> > at NormalModule.doBuild (/home/runner/work/nav/nav/node_modules/webpack/lib/NormalModule.js:2[95](https://github.com/hyyxiaoluo/nav/actions/runs/4652179791/jobs/8232231955#step:4:96):3)
> > at NormalModule.build (/home/runner/work/nav/nav/node_modules/webpack/lib/NormalModule.js:446:15)
> > at Compilation.buildModule (/home/runner/work/nav/nav/node_modules/webpack/lib/Compilation.js:739:10)
> > at /home/runner/work/nav/nav/node_modules/webpack/lib/Compilation.js:[111](https://github.com/hyyxiaoluo/nav/actions/runs/4652179791/jobs/8232231955#step:4:112)1:12
> > at /home/runner/work/nav/nav/node_modules/webpack/lib/NormalModuleFactory.js:409:6 {
> > opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
> > library: 'digital envelope routines',
> > reason: 'unsupported',
> > code: 'ERR_OSSL_EVP_UNSUPPORTED'
> > }
> > Node.js v18.15.0
> > Error: Process completed with exit code 1.
> > 自始至终按照教程来的
> 
> 大哥，我也出现了这个问题，请问是怎么解决的
![image](https://user-images.githubusercontent.com/102205671/235360727-ed615111-4a31-42d5-a00a-4203ebd890a9.png)
```
name: Build web
on:
  push:
    branches:
      - master
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Install
      uses: sergioramos/yarn-actions/install@v6
      with:
        frozen-lockfile: true
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Build
      run: |
        npm run build
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist
```

你试试所示的截图文件中将代码改成这样，等于是降下版本，不改的话我看后台是直接下载18版本不行的，这个是16的我这边可以

**Comment by khmoyu** [comment]
好的，谢谢
