### ISSUE TITLE
部署后访问L O A D I N G ...

### ISSUE THREAD

**Issue by jiuyueidc** [xjh22222228/nav#24]

**Comment by xjh22222228** [comment]
部署了吗，没看到有

**Comment by jiuyueidc** [comment]
自己还需要`npm`构建打包吗？

[https://github.com/jiuyueidc/nav#build-setup](https://github.com/jiuyueidc/nav#build-setup)

**Comment by xjh22222228** [comment]
不用，自动部署的。

**Comment by jiuyueidc** [comment]
按照操作，还是一样loading...  是不是我们只能使用v1分支呀？
![oBO4b.png](https://i.w3tt.com/2020/09/14/oBO4b.png)
