### ISSUE TITLE
vercel部署失败

### ISSUE THREAD

**Issue by ning0818** [xjh22222228/nav#240]
<html>
<body>

Error: error:0308010C:digital envelope routines::unsupported
--
19:26:35.046 | at new Hash (node:internal/crypto/hash:71:19)
19:26:35.046 | at Object.createHash (node:crypto:133:10)
19:26:35.046 | at module.exports (/vercel/path0/node_modules/webpack/lib/util/createHash.js:135:53)
19:26:35.046 | at NormalModule._initBuildHash (/vercel/path0/node_modules/webpack/lib/NormalModule.js:417:16)
19:26:35.046 | at /vercel/path0/node_modules/webpack/lib/NormalModule.js:452:10
19:26:35.046 | at /vercel/path0/node_modules/webpack/lib/NormalModule.js:323:13
19:26:35.047 | at /vercel/path0/node_modules/loader-runner/lib/LoaderRunner.js:367:11
19:26:35.047 | at /vercel/path0/node_modules/loader-runner/lib/LoaderRunner.js:172:11
19:26:35.047 | at loadLoader (/vercel/path0/node_modules/loader-runner/lib/loadLoader.js:32:11)
19:26:35.047 | at iteratePitchingLoaders (/vercel/path0/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
19:26:35.047 | at runLoaders (/vercel/path0/node_modules/loader-runner/lib/LoaderRunner.js:365:2)
19:26:35.047 | at NormalModule.doBuild (/vercel/path0/node_modules/webpack/lib/NormalModule.js:295:3)
19:26:35.047 | at NormalModule.build (/vercel/path0/node_modules/webpack/lib/NormalModule.js:446:15)
19:26:35.047 | at Compilation.buildModule (/vercel/path0/node_modules/webpack/lib/Compilation.js:739:10)
19:26:35.047 | at /vercel/path0/node_modules/webpack/lib/Compilation.js:1111:12
19:26:35.047 | at /vercel/path0/node_modules/webpack/lib/NormalModuleFactory.js:409:6 {
19:26:35.048 | opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
19:26:35.048 | library: 'digital envelope routines',
19:26:35.048 | reason: 'unsupported',
19:26:35.048 | code: 'ERR_OSSL_EVP_UNSUPPORTED'
19:26:35.048 | }
19:26:35.048 |  
19:26:35.048 | Node.js v18.15.0
19:26:35.087 | error Command failed with exit code 1.
19:26:35.088 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
19:26:35.119 | Error: Command "yarn run build" exited with 1
19:26:35.559 | BUILD_UTILS_SPAWN_1: Command "yarn run build" exited with 1

</body>
</html>

**Comment by isslower** [comment]
一样的问题 ，突然就部署失败了

**Comment by li010116** [comment]
失败后在setting中可以吧node版本换成16的就可以啦
