### ISSUE TITLE
后台无法更换网站图标

### ISSUE THREAD

**Issue by Thot-null** [xjh22222228/nav#242]
### Version
6.0.1

### Reproduction link
[https://nav.thotz.top](https://nav.thotz.top)

### Steps to reproduce
vercel部署成功，但是不能上传网站logo，尺寸格式均正确，但是404

### What is expected?
上传成功

### What is actually happening?
上传失败

**Comment by Thot-null** [comment]
提议：
编辑网站图标地址时，也支持url及各种图片格式，而不只是base64

**Comment by xjh22222228** [comment]
我试了下可以正常更换，保存后要等待几分钟，看看是否是你的页面有缓存没更新。

**Comment by Thot-null** [comment]
他直接就是404，上传失败

**Comment by xjh22222228** [comment]
权限都勾选了吗， 已经支持url格式了。

**Comment by Thot-null** [comment]
那个倒无所谓，大佬，再提个意见，能不能把head和body插入文件的功能也加一加，这样可以方便魔改啥的。app主题里也添加一个站内搜索

**Comment by xjh22222228** [comment]
插到底部就行，一样能实现。

**Comment by Thot-null** [comment]
佬，给你瞅瞅      https://s2.loli.net/2023/08/05/QoiKkqYezwLnZyG.gif    就是这样省的

**Comment by xjh22222228** [comment]
应该Github后面做了更新，现在Fork完之后需要手动创建一个 "image" 分支。

**Comment by Thot-null** [comment]
没事佬，你加了那个自定义头像url后就可以了，感谢大佬

**Comment by Thot-null** [comment]
大佬就是我要引入51统计，他要往head里添加我该怎么写

**Comment by xjh22222228** [comment]
把下面代码全部丢进去
```
<script>
  const s = document.createElement('script');
  s.id = 'LA_COLLECT';
  s.src = '//sdk.51.la/js-sdk-pro.min.js';
  const s1 = document.createElement('script');
  s1.innerHTML = 'window.LA && window.LA.init({id:"14511321545",ck:"1356461230352"})';
  document.head.appendChild(s);
  s.onload = function() {
    document.head.appendChild(s1);
  }
</script>
```

**Comment by Thot-null** [comment]
不太中尼，佬，算啦，不搞啦，感谢佬
