### ISSUE TITLE
添加自定义秘钥

### ISSUE THREAD

**Issue by xxchenjh** [xjh22222228/nav#244]
### What problem does this feature solve?
能否再第一次登陆管理页面后，添加自定义秘钥，总是记录token不方便

### What does the proposed API look like?
token用来忘记秘钥时用，日常使用自定义秘钥

**Comment by xjh22222228** [comment]
没有，因为这个不是保存在数据库。你需要自己保存好Token。

**Comment by icewolf-li** [comment]
那有没有可能就是部署好了之后，更改Token的验证，也就是说从源代码的层面自定义密钥，本人小白，有点找不出验证Token的方法在哪
