### ISSUE TITLE
获取token和验证token，可以从源码上面设置吗

### ISSUE THREAD

**Issue by icewolf-li** [xjh22222228/nav#245]
### What problem does this feature solve?
就是部署好了之后，更改Token的验证，也就是说从源代码的层面自定义密钥，本人小白，有点找不出验证Token的方法在哪

### What does the proposed API look like?
大佬能不能指一下那些文件、方法、函数是用来验证token登录的，获取到的token能不能改成自己想要的

**Comment by aiyou9** [comment]
> 

token 是github的，要用来访问，调用github action，进行新内容的编译，不懂你说的token自定义

**Comment by icewolf-li** [comment]
> 

我的意思是，从代码层面自定义一个密码，我想找验证token的函数，但是看不懂typescript，把登录验证的函数判断，自定义一个值当作密码，或者使用totp验证登录

**Comment by zhuhuibiao** [comment]
同问

**Comment by zhuhuibiao** [comment]
作者的意思是在github上生成一个TOKEN，然这个TOKEN加密后的秘钥，就是登录的密码。

**Comment by xjh22222228** [comment]
文件在：src/utils/user.ts  ，getToken 方法返回你的 token 就行
