### ISSUE TITLE
vercel已经报错，不支持 16.x

### ISSUE THREAD

**Issue by Flyingpen** [xjh22222228/nav#248]
### Version
6.0.1

### Steps to reproduce
日志详情：
Error: Node.js version 16.x has reached End-of-Life. Deployments created on or after 2024-02-06 will fail to build. Please set Node.js Version to 18.x in your Project Settings to use Node.js 18.
sh: ng: command not found
Error: Command "ng build" exited with 127

vercel强制要求更换成Node.js 18.

### What is expected?
感谢作者，希望能兼容Node.js 18.

### What is actually happening?
希望能兼容Node.js 18.

---
再次感谢作者提供这么好的开源站点！

**Comment by aiyou9** [comment]
netlify呢？

**Comment by Flyingpen** [comment]
> netlify呢？

没试过，主要使用vercel。

**Comment by xjh22222228** [comment]
[升级](https://github.com/xjh22222228/nav/blob/main/README_zh-CN.md#%E5%8D%87%E7%BA%A7)
