### ISSUE TITLE
..

### ISSUE THREAD

**Issue by jiuyueidc** [xjh22222228/nav#25]
昨天我按照部署流程申请token，填写token，页面一直是loading，试了N次。

**Comment by xjh22222228** [comment]
@jiuyueidc 原因是Fork了本仓库，gh-pages 部署的代码不一致导致的， 你往仓库随便提交次commit， 5分钟后应该可以看到。

**Comment by jiuyueidc** [comment]
> @jiuyueidc原因是Fork了本仓库，gh-pages部署的代码直接导致的，你往仓库随便提交次提交，5分钟后应该可以看到。

我也在`gh-pages`分支随便提交了下commit，如图（修改了标题）
![oBKCY.png](https://i.w3tt.com/2020/09/15/oBKCY.png)

40多分钟了，GitHub页面设置那还显示在构建中`Your GitHub Pages site is currently being built from the gh-pages branch.`
如图
![oBASU.png](https://i.w3tt.com/2020/09/15/oBASU.png)

**Comment by xjh22222228** [comment]
@jiuyueidc 在 master 分支提交一次Commit。

**Comment by xjh22222228** [comment]
@jiuyueidc   打开 https://github.com/jiuyueidc/nav/actions     ，点击绿色按钮，然后提交一次Commit。

**Comment by jiuyueidc** [comment]
> @jiuyueidc 打开 https://github.com/jiuyueidc/nav/actions ，点击绿色按钮，然后提交一次Commit。

运行出错`The deploy step encountered an error: The process '/usr/bin/git' failed with exit code 128`

![oBvnv.png](https://i.w3tt.com/2020/09/15/oBvnv.png)

**Comment by xjh22222228** [comment]
@jiuyueidc 你的 Token 填写正确了没， key是大写 `TOKEN`

**Comment by jiuyueidc** [comment]
> @jiuyueidc 你的 Token 填写正确了没， key是大写 `TOKEN`

如图，正确的，name是`TOKEN`，填写的值是申请的那一串token，新申请token需要勾选什么吗？

![oByDq.png](https://i.w3tt.com/2020/09/15/oByDq.png)

**Comment by xjh22222228** [comment]
@jiuyueidc 要勾选，把全部勾了，不然没权限

**Comment by jiuyueidc** [comment]
感谢，成功了 我写篇文章详细记录下

**Comment by keyL-liucong** [comment]
> 感谢，成功了 我写篇文章详细记录下

能贴下文章吗，遇到一样的问题
