### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by Thot-null** [xjh22222228/nav#250]
佬，最近vercel国内被墙的力度又加大了几份，目前网站的体量又大了几分，看看是否能做些许优化，使网页加速；其次，vercel更新了node18x版本，将于2024/2月份停止16x的所有服务，如果您看到的话，恳请您进行相应的修改优化，不胜感激。

**Comment by Flyingpen** [comment]
同求！！

**Comment by xjh22222228** [comment]
正在升级。

**Comment by xjh22222228** [comment]
[已升级到 node:v18](https://github.com/xjh22222228/nav/blob/main/README_zh-CN.md#%E5%8D%87%E7%BA%A7)

**Comment by Thot-null** [comment]
> [已升级到 node:v18](https://github.com/xjh22222228/nav/blob/main/README_zh-CN.md#%E5%8D%87%E7%BA%A7)

感谢佬

**Comment by Thot-null** [comment]
佬，现在又出现#242那个问题了，还是无法直接上传网站图标

**Comment by Thot-null** [comment]
> 佬，现在又出现#242那个问题了，还是无法直接上传网站图标

而且，可能是我本地网络的原因？一直404

**Comment by xjh22222228** [comment]
上传图片出现404的， 在仓库页面点击 `main` 分支在输入框里输入 `image` 创建分支

**Comment by Thot-null** [comment]
> 上传图片出现404的， 在仓库页面点击 `main` 分支在输入框里输入 `image` 创建分支

已经创建了分支，还是不能更改网站logo，网站基础信息无法修改
![image](https://github.com/xjh22222228/nav/assets/102007068/ec25be10-cd4d-4c38-9798-b6d932f2e227)

**Comment by xjh22222228** [comment]
你是不是删了仓库然后重新Fork的， 重新申请个token

**Comment by Thot-null** [comment]
> 你是不是删了仓库然后重新Fork的， 重新申请个token

没有，现在我重新开了个仓库重新fork就可以啦，感谢大佬

**Comment by Thot-null** [comment]
[导航链接：](https://nav.thotz.top)
[仓库地址：](https://github.com/Thot-null/nav)

如下图，在后台设置完网站基础信息之后，基础信息并不会改变。

图一：实际的网站信息

![image-20231028183253824](https://github.com/xjh22222228/nav/assets/102007068/8b405820-6270-4126-9d81-9d6f746fb626)


图二：仓库的信息

![image-20231028183037455](https://github.com/xjh22222228/nav/assets/102007068/3c9250fe-7bf7-40ae-af08-00298f2681bc)




已经修改了网站的logo，但实际显示的只有页面内的，如图

![image-20231028182847938](https://github.com/xjh22222228/nav/assets/102007068/dd642080-93fa-4f31-a0a9-20d00b0d8456)

其实logo并没有被修改，这是我的仓库
![image-20231028183009850](https://github.com/xjh22222228/nav/assets/102007068/0c072a06-9905-47d3-90df-7d6bf2a1f5ec)

**Comment by xjh22222228** [comment]
已经修复了。

**Comment by Thot-null** [comment]
大佬，这个不改是不是就无法连接到我的仓库
![image](https://github.com/xjh22222228/nav/assets/102007068/1be8d618-5da2-465f-b83b-76be92b7855a)

**Comment by aiyou9** [comment]
> 大佬，这个不改是不是就无法连接到我的仓库 ![image](https://private-user-images.githubusercontent.com/102007068/278847673-1be8d618-5da2-465f-b83b-76be92b7855a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4ODQzOTgsIm5iZiI6MTcwMjg4NDA5OCwicGF0aCI6Ii8xMDIwMDcwNjgvMjc4ODQ3NjczLTFiZThkNjE4LTVkYTItNDY1Zi1iODNiLTc2YmU5MmI3ODU1YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxOFQwNzIxMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZDM4MDcxNjM5NWMxZTkxMTJmMmUwMDU4NjdiZWQ1YmViNzVjNzM1OTU4YzMxZDlmOTFmZGNmMDU2OTUxNGQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JdlTBPxm5a8hBduFlIPp8IFrCmjU_0XHXWOencJLp6I)

是的，必须改成自己的github库
