### ISSUE TITLE
Build web ：All jobs have failed 和 登录生成的TOKEN不安全

### ISSUE THREAD

**Issue by zhuhuibiao** [xjh22222228/nav#257]
我什么在页面显示推送成功，邮箱老收到，Build web ：All jobs have failed。githab上的也已经更新了，但是网页还是之前的内容没变化。
问题：TOKEN
用生成的TOKEN基本可以登录任何一个用项目构建的网站。

**Comment by zhuhuibiao** [comment]
还有为啥我推送的到了你的项目上。

**Comment by aiyou9** [comment]
设置里没改 库地址6、Be sure to modify the project configuration file [nav.config.ts](https://github.com/xjh22222228/nav/blob/main/nav.config.ts)

**Comment by zhuhuibiao** [comment]
> 设置里没改 库地址6、Be sure to modify the project configuration file [nav.config.ts](https://github.com/xjh22222228/nav/blob/main/nav.config.ts)

我真的改了 ，我打包的时候检查了好几遍
