### ISSUE TITLE
请问有人知道 我用vercel部署 怎么配置进入后台的token吗

### ISSUE THREAD

**Issue by cdxiaodong** [xjh22222228/nav#261]
请问有人知道 我用vercel部署 怎么配置进入后台的token吗

**Comment by xjh22222228** [comment]
在链接里加  #sysyem,  比如 https://www.example.com/#/system,  输入你的 token 就行。

**Comment by cdxiaodong** [comment]
好的好的 再请教个问题 system保存配置报错404是因为什么呢 是因为我用的vercel部署的吗
![image](https://github.com/xjh22222228/nav/assets/84082748/3ca41783-d2ec-4ce6-84d7-8cfcbb23d0ee)

**Comment by xjh22222228** [comment]
https://github.com/cdxiaodong/nav/blob/main/nav.config.ts#L6     修改成你的仓库地址， [仔细看文档](https://github.com/xjh22222228/nav/blob/main/README_zh-CN.md#%E9%83%A8%E7%BD%B2)
