### ISSUE TITLE
功能需求：能不能将第三层的列表，也换成选项卡的形式，进行切换，网页个数使用上标

### ISSUE THREAD

**Issue by setdiaoyong** [xjh22222228/nav#27]

**Comment by xjh22222228** [comment]
描述过于抽象，最好有个图片展示。

**Comment by setdiaoyong** [comment]
![第三级分类标签做成如图红色标签所示；我自己加了一个一级分类，博客看点超出的页面，如箭头所示，算个功能需求，页面大小自适应](https://user-images.githubusercontent.com/62551864/98761397-50e20b00-2410-11eb-982d-2038ac8e9fdf.png)

**Comment by setdiaoyong** [comment]
第三级用选项卡也不好，展示数量受限。新想法，在现在基础上，默认打开网页，第三级是缩并成列表的，能不能在第三级前也加上自选的LOGO，美化，然后提供按钮，选择展开或者缩并第三级，方便快速浏览与跳转相应网页条目。我重开一个issue

**Comment by xjh22222228** [comment]
@setdiaoyong 初衷设计就是这样的，不会改变， 会开发新的主题，你有更好的主题推荐吗？

**Comment by setdiaoyong** [comment]
第三级列表下是否还能够像这个网站一样，增加标签页https://ionego.net/
