### ISSUE TITLE
自己拉代码构建docker镜像部署  进入不了system后台 输入网址自动重定向到#/light路由

### ISSUE THREAD

**Issue by footlose** [xjh22222228/nav#273]
自己拉代码构建docker镜像部署  进入主页没问题但进入不了system后台 输入url/#/system 网址自动重定向到#/light

**Comment by xjh22222228** [comment]
[https://www.nav3.cn/#/system](https://www.nav3.cn/#/system)     尝试访问此网站是否有弹出授权

**Comment by footlose** [comment]
https://www.nav3.cn/#/system  访问此网站 弹出授权 但是自定义部署的网站访问 https://域名/#/system 会直接重定向到 https://域名/#/light

**Comment by footlose** [comment]
可以进/#/admin页面
