### ISSUE TITLE
.pack 文件有点大

### ISSUE THREAD

**Issue by zchdoc** [xjh22222228/nav#279]
.git\objects\pack 下有大文件，大佬可否优化一下 
![95027fac0a60bd2f59fba8a05a2140a](https://github.com/xjh22222228/nav/assets/19989607/c7ed8d69-0318-4670-b7be-ee25422659c8)

**Comment by zchdoc** [comment]
项目空间都被 .git 占了

**Comment by xjh22222228** [comment]
git clone --depth=1 https://github.com/xjh22222228/nav.git

**Comment by zchdoc** [comment]
学到了

**Comment by zchdoc** [comment]
> git clone --depth=1 https://github.com/xjh22222228/nav.git


学到了
