### ISSUE TITLE
关于通过GITHUB API提交到库和自动部署，实现访客在线提交，站长审核，更新等后台功能的想法

### ISSUE THREAD

**Issue by setdiaoyong** [xjh22222228/nav#28]
1, Vue及框架的表单设计器，设计收集页面；2, GITHUB API将访客在收集页面提交的信息，保存到git库的一个新分支，等待导航站长的审核。3，站长使用github 网页，或在部署网页用API，进行git库中用户提交分支，与部署分支的合并或舍弃，实现审核功能，4，使用任何一个自动部署github的网站，如https://now.sh等，自动进行增量合并到部署分支，然后经自动部署，获得网址，以供访问。

**Comment by setdiaoyong** [comment]
[Github库可以用API进行修改](https://www.cnblogs.com/kylinlin/articles/5243475.html)

**Comment by setdiaoyong** [comment]
搞了一下，问卷网的收集表，将项目当前的分类导入进入，设计了提交问卷，有两种，不知道哪个好，第一种，用自增表格，可以一次收集同一分类下的多个网址，见[收集表测试1](https://www.wenjuan.com/s/UZBZJv1IMr/)
![收集表测试1](https://user-images.githubusercontent.com/62551864/98781980-2f921680-2432-11eb-9820-1976dd9e0dc0.png)

第二种，拆分开来，一次只能填一种，可以添加logo图片，见[收集表测试2](https://www.wenjuan.com/s/buumQjT/)
![集表测试2](https://user-images.githubusercontent.com/62551864/98782059-4afd2180-2432-11eb-9040-2703724b2012.png)

**Comment by xjh22222228** [comment]
@setdiaoyong  感谢您的建议和提供方案，这个确实很好，但是开放API 支持个人？

**Comment by setdiaoyong** [comment]
> @setdiaoyong 感谢您的建议和提供方案，这个确实很好，但是开放API 支持个人？

确实，问卷网的开放API，调用收费方式不清晰，我已填了申请表，说明了目的是个人测试，目前没有收到答复。

**Comment by setdiaoyong** [comment]
> > @setdiaoyong 感谢您的建议和提供方案，这个确实很好，但是开放API 支持个人？
> 
> 确实，问卷网的开放API，调用收费方式不清晰，我已填了申请表，说明了目的是个人测试，目前没有收到答复。

看了一下，要收费的，那就得自己写了，用VUE 现成框架的表单设计，开发应该很快，用户填完网址信息，直接在部署网页上，走github API 提交到github库，然后，now.sh等自动部署方式，立刻就能看部署好的结果，我觉得香。但是编译后发布版，怎么能有后台，我就不懂了。

**Comment by setdiaoyong** [comment]
> [Github库可以用API进行修改](https://www.cnblogs.com/kylinlin/articles/5243475.html)
> 从页面处理，提交，然后配合git库的自动部署？

加入微软后，最新V4版的api,搞成了[GitHub GraphQL API
](https://docs.github.com/en/free-pro-team@latest/graphql/guides/introduction-to-graphql)
微软开放政策厉害了

**Comment by setdiaoyong** [comment]
参考资源
这两个项目
（https://github.com/chinese-poetry/chinese-poetry)
(https://github.com/pwxcoo/chinese-xinhua)
以及博客
（https://blog.csdn.net/Scoful/article/details/103211795?utm_medium=distribute.pc_relevant.none-task-blog-title-2&spm=1001.2101.3001.4242）
(https://blog.csdn.net/tiandixuanwuliang/article/details/81738512?utm_medium=distribute.pc_aggpage_search_result.none-task-blog-2~all~sobaiduend~default-2-81738512.nonecase&utm_term=github%20%E5%BD%93%E6%95%B0%E6%8D%AE%E5%BA%93&spm=1000.2123.3001.4430)

**Comment by setdiaoyong** [comment]
> > > @setdiaoyong 感谢您的建议和提供方案，这个确实很好，但是开放API 支持个人？
> > 
> > 
> > 确实，问卷网的开放API，调用收费方式不清晰，我已填了申请表，说明了目的是个人测试，目前没有收到答复。
> 
> 看了一下，要收费的，那就得自己写了，用VUE 现成框架的表单设计，开发应该很快，用户填完网址信息，直接在部署网页上，走github API 提交到github库，然后，now.sh等自动部署方式，立刻就能看部署好的结果，我觉得香。但是编译后发布版，怎么能有后台，我就不懂了。

我看看有没有其他问卷公司提供个人免费的API

**Comment by xjh22222228** [comment]
目前方案还在设计中,  2个方案：

- 浏览器插件（用户无法贡献，只能作者添加）
- 在github pages网页上操作，采用issue模板方式，作者提交直接通过，其他用户提交作者需要回复通过。

**Comment by setdiaoyong** [comment]
> 目前方案还在设计中, 2个方案：
> 
> * 浏览器插件（缺点用户无法贡献，只能作者添加）
> * 在github pages网页上操作，采用issue模板方式，作者提交直接通过，其他用户提交作者需要回复通过。

![image](https://user-images.githubusercontent.com/62551864/102689923-d8efd780-423c-11eb-9142-c7b593dac9be.png)

个人意见（思维有点乱，上图还得结合github的各种API研究研究），仅供参考
1、感觉把源代码的库作为开发库，开一个大家拉取的主版本分支，然后网址数据使用Git（网页应该有API）进行提交处理，这样每一个网址信息都可以打上标签（像修BUG修复，子功能增加，释放子版本分枝，）大家都拉取主版本的库，在自己拉取的库中添加的网址信息，也是通过git添加的（每一条网址信息都附带有分枝或标签，就像修bug一样，最后分享功能就是相互修bug）。

2、代码实现在展示页面的时候，能够登录github，然后获取授权后，可以点击页面上的拉取按钮（包含github拉取特定标签或分枝的功能，对应每一个添加的网址信息，也可跳转github拉取，合并页面中（提交的标签名也可用作分类），选择拉取到自己的分类中），这样用户访问时，登录自己的github账号，获取操作授权，或者点击跳转到github拉取合并的界面，就可以把作者网站的好网址拉取到自己的库中，是不是可以实现网址分享功能（就像fork，compare一样，把所有网址变成库里的一个分支，或者一个标签，可以进行fork，或拉取，合并，是否可以实现分享，相当于拉取一个分支或标签（不知道能不能拉取，修bug应该是标签？），页面上给出fork的代码，用户看到好的就直接点拉取到自己的收集库中），github感觉就是个分布式数据存储库。

3、主要是储存标记（库，分支，标签……）操作（fork，拉取，合并……）对应着分布式数据库储存与互操的哪些要点

4、不懂API与github给的权限，只能根据已有知识瞎想，表达的有点乱，仅供参考

**Comment by xjh22222228** [comment]
类似你之前说的这个 [https://www.wenjuan.com/s/buumQjT/](https://www.wenjuan.com/s/buumQjT/),  就是一个可视化界面，作者可以增删改查排序，其他用户也是同样的操作只不过其他用户提交后会到 issues 里，需要作者回复一句 “同意”。

目前这个方案还算可行，浏览器插件只能作者用，无法共享。

还有这个项目不涉及到后台，不然给人部署就很麻烦，就突显不出价值了。

你还有更好的方案吗？

**Comment by setdiaoyong** [comment]
1、[老外也在搞这创意，把github当做数据库用，有一些可以参考 ](https://github.com/DavidBruant/github-as-a-database)
2、[你说的是github项目issue-db吗？](https://github.com/issue-db/issue-db) https://github.com/issue-db/sandbox
3、https://github.com/Ciaanh/hosthub 博客：https://medium.com/younited-tech-blog/what-if-hosting-sources-website-and-database-on-github-8caf82d0bc07（要tz）

**Comment by setdiaoyong** [comment]
突然想到，关于无后台的相互分享功能，让自己有部署的访客用github账号登录，可获得自己喜欢的网址(每一个网址都是一个增量提交(不知道这个增量提交，以后通过页面合并到访客库中也是增量，同一个文件？或者是不是要一个网址一个文件？然后放在哪个文件夹下就显示在页面的哪个层级中(部署时读取文件夹名，可能性能堪忧)，不论怎样，目的是要实现每个网址单独处理，方便相互合并到不同文件夹下)，访客使用增量提交到自己的库，不知道github api有没有这个增量提交合并功能)，大家的部署都来自开发者的发布库，在部署页面中提供自己github的token(安全性待定)，用于设置每一条网址旁的pull按钮，访客之前登录是否可以把看到好的网址，想合并到自己库的，就点击网址旁的按钮，选择自己库要合并到的文件夹下(文件夹名就是每个层级的名称，是否可实现部署时读取文件夹名，如何进行创建新的层级，还是所有现在github通过代码预设好)，相当于访客使用网址部署者的github账号向访客自己的github部署库里增加一个提交，就可以相互分享了，感觉这样简单点

**Comment by setdiaoyong** [comment]
> 突然想到，关于无后台的相互分享功能，让自己有部署的访客用github账号登录，可获得自己喜欢的网址(每一个网址都是一个增量提交(不知道这个增量提交，以后通过页面合并到访客库中也是增量，同一个文件？或者是不是要一个网址一个文件？然后放在哪个文件夹下就显示在页面的哪个层级中(部署时读取文件夹名，可能性能堪忧)，不论怎样，目的是要实现每个网址单独处理，方便相互合并到不同文件夹下)，访客使用增量提交到自己的库，不知道github api有没有这个增量提交合并功能)，大家的部署都来自开发者的发布库，在部署页面中提供自己github的token(安全性待定)，用于设置每一条网址旁的pull按钮，访客之前登录是否可以把看到好的网址，想合并到自己库的，就点击网址旁的按钮，选择自己库要合并到的文件夹下(文件夹名就是每个层级的名称，是否可实现部署时读取文件夹名，如何进行创建新的层级，还是所有现在github通过代码预设好)，相当于访客使用网址部署者的github账号向访客自己的github部署库里增加一个提交，就可以相互分享了，感觉这样简单点

》为了防止并发，已经对单个文件进行修改导致冲突，每个网址可能需要使用单文件模式，添加后就很少修改，然后只增量添加到不同的库，文件名使用提交用户产生的提交编号，就保证在所有fork源代码的库中不会有重复文件名，相当于利用git提交特性，实现所有用户使用github提交到源代码的fork库，然后每个用户都是在添加网址，相互之间也可以拉取合并别人添加的网址，这个网址文件相当于源代码库与fork库中子功能增加文件（在向外部展示页面上，每个网址旁都有一个按钮，点击后，能够把这个补丁文件加到每个fork出的子库的自己层级分类中，）。

![网址文件相当于补丁文件，可以在所有fork库中流动](https://user-images.githubusercontent.com/62551864/102703163-556ad080-42a6-11eb-8416-9f3d2d5cd706.png)

**Comment by setdiaoyong** [comment]
> 1、[老外也在搞这创意，把github当做数据库用，有一些可以参考 ](https://github.com/DavidBruant/github-as-a-database) 这里说是用通用的Web API
> 2、[你说的是github项目issue-db吗？](https://github.com/issue-db/issue-db) https://github.com/issue-db/sandbox
> 3、https://github.com/Ciaanh/hosthub 博客：https://medium.com/younited-tech-blog/what-if-hosting-sources-website-and-database-on-github-8caf82d0bc07
> （要tz）博客里面说，github并发访问具有读/写限制。如果许多用户同时更新db文件，会有冲突。（还是单文件保存一个网址）
> 代码作者给出的示例https://ciaanh.github.io/hosthub/
> 
> 4、https://github.com/mapbox/hubdb

**Comment by xjh22222228** [comment]
并发这个不用考虑哈，很少用户会去贡献，基本上只有作者去做这事情。

下个版本增加 GUI 界面增删改查功能。

**Comment by setdiaoyong** [comment]
> 并发这个不用考虑哈，很少用户会去贡献，基本上只有作者去做这事情。
> 
> 下个版本增加 GUI 界面增删改查功能。

我可能把用户定义错了，有的是指网页作者，就是fork库的这114人，有的是指访问部署网站的访客。单文件保存网址，在所有fork源代码的创建网页作者的库中传递，跨git库传递。

**Comment by xjh22222228** [comment]
功能已开发，参见，部分功能还需要测试：
https://github.com/xjh22222228/nav  v5.0.0-beta.1
