### ISSUE TITLE
设置“仅自己可见”后，用token登录无法可见的问题

### ISSUE THREAD

**Issue by openMJJ** [xjh22222228/nav#286]
设置“仅自己可见”后，用token登录无法可见，是我哪里设置错了吗？？

**Comment by xjh22222228** [comment]
你好，我这边测试了下没有问题，你的操作步骤是什么。

**Comment by openMJJ** [comment]
第一步用edge浏览器把，一个内容设置为“仅自己可见”，如下图：
![image](https://github.com/xjh22222228/nav/assets/125738740/badf65f5-54da-41c5-9a57-f8ef5aaea91d)

然后，在这个浏览器下，退出TOKEN，如下图：
![image](https://github.com/xjh22222228/nav/assets/125738740/2cd26be2-05db-44cf-8375-b26cc04b6b13)


以上都没有问题。。

但是以上步骤操作完毕后，再启动一个无痕浏览器打开https://openmjj.github.io/nav/后，如下图：
![image](https://github.com/xjh22222228/nav/assets/125738740/7f835973-a5dc-48f0-b960-7b02153c6ae2)

设置“仅自己可见”的JavaScript页面无法显示，登录system后，如下图：
![image](https://github.com/xjh22222228/nav/assets/125738740/8a8656a8-51dd-4906-a689-869d68a6104f)

设置中也没有JavaScript页面。。。

**Comment by xjh22222228** [comment]
是只有后台没显示，其他正常是吧

**Comment by openMJJ** [comment]
在原浏览器设置“仅自己可见”后，点击保存了。如下图：
![image](https://github.com/xjh22222228/nav/assets/125738740/e8801a32-b855-4a5b-9cd6-1c36247c36c1)

点击了左上角的保存。

**Comment by xjh22222228** [comment]
你现在不是能显示出来吗， 是无痕浏览器才会这样吗

**Comment by openMJJ** [comment]
新打开的无痕浏览器不显示， 以下是无痕浏览器的截图：
![image](https://github.com/xjh22222228/nav/assets/125738740/3fc50c7d-818b-4865-8115-9db140030977)

**Comment by xjh22222228** [comment]
不好意思，我这边用Edge按照你的流程没能操作出来，试试 [更新一下代码](https://github.com/xjh22222228/nav?tab=readme-ov-file#%E5%8D%87%E7%BA%A7)

**Comment by openMJJ** [comment]
没能操作出来？？？
意思是我操作有问题？
好吧，谢谢，我再试试吧。

**Comment by xjh22222228** [comment]
好的，感谢，我看一下。
