### ISSUE TITLE
部署的时候报错Error: The deploy step encountered an error: The process '/usr/bin/git' failed with exit code 128

### ISSUE THREAD

**Issue by lvsuhan** [xjh22222228/nav#289]
Error: The deploy step encountered an error: The process '/usr/bin/git' failed with exit code 128 ❌
Notice: Deployment failed! ❌

setting->general中修改设置我也设置过了

有什么解决办法吗

**Comment by xjh22222228** [comment]
你没有设置 TOKEN,  部署有说明，[https://github.com/xjh22222228/nav?tab=readme-ov-file#gh-pages-%E5%85%8D%E8%B4%B9](https://github.com/xjh22222228/nav?tab=readme-ov-file#gh-pages-%E5%85%8D%E8%B4%B9)

**Comment by SuMaiKaDe** [comment]
同报错
/usr/bin/git worktree remove github-pages-deploy-action-temp-deployment-folder --force
Error: The deploy step encountered an error: The process '/usr/bin/git' failed with exit code 128 ❌
Notice: Deployment failed! ❌
