### ISSUE TITLE
功能需求：增加一个浏览器书签文件导入工具

### ISSUE THREAD

**Issue by setdiaoyong** [xjh22222228/nav#29]
[类似书签导入功能实现参见webstack-jekyll后台版](https://github.com/hanxi/webstack-jekyll)

**Comment by setdiaoyong** [comment]
> [类似书签导入功能实现参见webstack-jekyll后台版](https://github.com/hanxi/webstack-jekyll)



> [类似书签导入功能实现参见webstack-jekyll后台版](https://github.com/hanxi/webstack-jekyll)
感觉将chrome浏览器收藏夹导出文件，直接转换成数据，一键替换所有导航目录，chrome书签插件直接导入？

**Comment by setdiaoyong** [comment]
> [类似书签导入功能实现参见webstack-jekyll后台版](https://github.com/hanxi/webstack-jekyll)

可以用这个webstack-jekyll的书签导入工具，转换chrome收藏夹文件，然后替换一下关键词，就可以粘贴到data文件夹分类中，开心！！！

**Comment by hanxi** [comment]
写个收费的浏览器插件？

**Comment by setdiaoyong** [comment]
> 写个收费的浏览器插件？

浏览器插件登录自己的github账号，获取token，直接用插件调用Github的API，push到github，使用自动部署（如rander，now.sh，支持git拉取的免费空间如grearhost.com，epizy.com,heliohost.org/），直接连服务器都白嫖了。适合我这样的小白，这插件应该会有更多的人买吧？

**Comment by aiyou9** [comment]
> > 写个收费的浏览器插件？
> 
> 浏览器插件登录自己的github账号，获取令牌，直接用插件调用Github的API，push到github，使用自动部署（如rander，now.sh，支持git拉取的免费空间如grearhost.com，epizy.com ，heliohost.org /），直接连服务器都白嫖了。适合我这样的小白，这插件应该会有更多的人买吧？

发现有gitee开源中国插件GitCodeTree，可能可以作为商业化插件项目起始，已经把github上的适配到gitee，哈哈
https://gitee.com/oschina/GitCodeTree

**Comment by xjh22222228** [comment]
考虑加入导入导出。

**Comment by xjh22222228** [comment]
已支持， v5.2.0
