### ISSUE TITLE
貌似提示ts语法错误

### ISSUE THREAD

**Issue by yixiqiannian** [xjh22222228/nav#293]
Error: nav.config.ts(12,3): error TS1005: ',' expected.
Error: Process completed with exit code 2.

**Comment by xjh22222228** [comment]
https://github.com/yixiqiannian/nav/blob/main/nav.config.ts#L6C3-L6C53    看到你把尾逗号删除了，现在补上了吧。

https://github.com/xjh22222228/nav?tab=readme-ov-file#gh-pages-%E5%85%8D%E8%B4%B9      大部分人部署失败务必按照第4步和第5步操作，否则是没权限的，请把权限全部勾选上， 设置name为 `TOKEN` 必须大写。
