### ISSUE TITLE
shortcut模板的搜索引擎文字是浅色的，导致完全看不清楚

### ISSUE THREAD

**Issue by 8706141** [xjh22222228/nav#296]
请尽快修复下，谢谢

**Comment by 8706141** [comment]
还有sim和side的搜索引擎如果多了会被遮挡，不能完全显示出来

**Comment by xjh22222228** [comment]
[麻烦升级一下](https://github.com/xjh22222228/nav?tab=readme-ov-file#%E5%8D%87%E7%BA%A7)

**Comment by 8706141** [comment]
> [麻烦升级一下](https://github.com/xjh22222228/nav?tab=readme-ov-file#%E5%8D%87%E7%BA%A7)

牛啊，这么快就解决了！辛苦辛苦！

**Comment by 8706141** [comment]
大佬抽空把移动端也适配下就完美了，手机上那个搜索显示也不太全

**Comment by 8706141** [comment]
大佬，书签的LOGO图标有点模糊能再修复下吗？

**Comment by xjh22222228** [comment]
你这个是书签导入的，由于浏览器书签本身图标很小所以很模糊

**Comment by xjh22222228** [comment]
明天自动抓取网站信息功能就上线了， 到时候设置一下会自动更新网站图标、描述信息等。

**Comment by xjh22222228** [comment]
自动抓取信息功能已发布，在系统设置里爬取规则设置一下，欢迎尝试。
