### ISSUE TITLE
关于个人收藏的问题

### ISSUE THREAD

**Issue by superglg738** [xjh22222228/nav#299]
请问下。支持个人收藏吗？

看了其他内容都非常的ok，如果自己在内网（无互联网）部署，准备作为内网地址导航，和单点登录的首页。

如果使用您的平台，有什么好的建议，改造会不会大。

毕竟这个平台已经有一个后台了。

**Comment by xjh22222228** [comment]
没有收藏， 需要联网，否则需要在 `server.js` 文件增加几个API，在 `src/servers` 添加API，比较容易； 如果想做为内网建议将仓库设为私有
