### ISSUE TITLE
netlify部署成功后，登陆后台提示要验证token,输入github的 token不行啊

### ISSUE THREAD

**Issue by ldpc520** [xjh22222228/nav#300]
如题，怎么解决啊？

**Comment by xjh22222228** [comment]
[https://github.com/[ldpc520](https://github.com/ldpc520)/nav/settings/secrets/actions/new](https://github.com/ldpc520/nav/settings/secrets/actions/new) 添加申请的 token， name 填写 TOKEN 大写。

**Comment by ldpc520** [comment]
第二和第三步已执行了的。登陆后台输入Github的token
右上角提示：
Error：404
Not Found

**Comment by xjh22222228** [comment]
链接发出来

**Comment by xjh22222228** [comment]
[nav.config](https://github.com/ldpc520/nav/blob/main/nav.config.ts)   代码都被你改乱了，怎么可能会部署成功

**Comment by ldpc520** [comment]
这个我就改成了我的仓库地址，其他的没动过，这个不能改，默认是吗？
&nbsp;


??健少??
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年7月22日(星期一) 下午3:44
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xjh22222228/nav] netlify部署成功后，登陆后台提示要验证token,输入github的 token不行啊 (Issue #300)














 
nav.config   代码都被你改乱了，怎么可能会部署成功

**Comment by xjh22222228** [comment]
把 nav.config  copy 过去，把仓库地址改成你的就行了， 猜测你是在网页翻译改的
