### ISSUE TITLE
部署报错，不知道什么问题，请教

### ISSUE THREAD

**Issue by lolo1024** [xjh22222228/nav#302]
![Screenshot_2024-07-27-22-52-17-667_com.github.android.jpg](https://github.com/user-attachments/assets/c5c4aa67-8823-430e-b6c2-81d7b13bc37f)

**Comment by xjh22222228** [comment]
[部署步骤](https://github.com/xjh22222228/nav?tab=readme-ov-file#gh-pages-%E5%85%8D%E8%B4%B9)

你这个是没有权限推上去，第三步和第四部， 权限勾选
