### ISSUE TITLE
部署完成进去是说明文档呢

### ISSUE THREAD

**Issue by lolo1024** [xjh22222228/nav#303]
![image](https://github.com/user-attachments/assets/8e937dcd-28b6-4d27-9bc6-4e8613dd5bf7)

**Comment by xjh22222228** [comment]
按照步骤部署没，一步不可缺少， 权限全部勾上，把仓库删了重新Fork吧。

下面是别人刚刚Fork的都没问题。

[dishao123/nav](https://github.com/dishao123/nav)

[yzgolden86/nav](https://github.com/yzgolden86/nav)
