### ISSUE TITLE
导入书签有限制吗？

### ISSUE THREAD

**Issue by lolo1024** [xjh22222228/nav#304]
现在测试导入6000+以上的书签无反应，是不支持还是因为未授权呢？
（刚买了授权还没返回激活码）

**Comment by xjh22222228** [comment]
把域名发到邮箱  xjh22222228@gmail.com  给你授权码， 书签可能太多了，尝试分开导入，或者方便可以把文件发过来

**Comment by lolo1024** [comment]
已发送书签和域名

**Comment by lolo1024** [comment]
![image](https://github.com/user-attachments/assets/3f8c36e8-7565-451a-891f-6744db7b134c)

**Comment by xjh22222228** [comment]
文件太大了，超出了容量， 先导入一半吧，后边我增加下容量。

**Comment by lolo1024** [comment]
分批大部分导入进去了，还有最后一批导不进去，只有700+KB的文件也没反应，只显示上传成功呢




&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xjh22222228/nav"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月28日(星期天) 下午4:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xjh22222228/nav] 导入书签有限制吗？ (Issue #304)





 
文件太大了，超出了容量， 先导入一半吧，后边我增加下容量。

**Comment by xjh22222228** [comment]
容量有限，过几天吧，我升级一下。改一下架构和性能。

**Comment by lolo1024** [comment]
升级怎么升级  那个没看懂...

**Comment by xjh22222228** [comment]
把仓库拉下来，在根目录执行 `npm run update`  就升级了， 首先得安装node，  如果没安装 node 的话执行升级文档里的那几条命令。

**Comment by lolo1024** [comment]
这几句我得好好理解一下，纯小白🥲

**Comment by xjh22222228** [comment]
到时候我会协助你升级， 需要几天时间处理。

**Comment by lolo1024** [comment]
非常感谢

**Comment by xjh22222228** [comment]
你好，按照下面步骤去升级，命令都帮你写好了，你只需要执行下面命令，全部复制粘贴到终端

```
git clone https://github.com/lolo1024/nav.git &&
cd nav &&
git pull &&
git remote add upstream https://gitee.com/xiejiahe/nav.git &&
git fetch upstream main &&
git merge upstream/main --allow-unrelated-histories --no-edit &&
git push
```

如果你安装了 node.js 更简单
```
git clone https://github.com/lolo1024/nav.git && cd nav && npm run update
```

**Comment by lolo1024** [comment]
> 你好,按照下面步骤去升级,命令都帮你写好了,你只需要执行下面命令,全部复制粘贴到终端
> 
> ```
> git clone https://github.com/lolo1024/nav.git &&
> cd nav &&
> git pull &&
> git remote add upstream https://gitee.com/xiejiahe/nav.git &&
> git fetch upstream main &&
> git merge upstream/main --allow-unrelated-histories --no-edit &&
> git push
> ```
> 
> 如果你安装了节点. js更简单
> 
> ```
> git clone https://github.com/lolo1024/nav.git && cd nav && npm run update
> ```

那个，我从来没弄过，终端在哪里🤦‍♂️抱歉，真是小白

**Comment by xjh22222228** [comment]
电脑命令行工具呀... ，  不知道的话只能删了仓库，重新Fork了。

**Comment by lolo1024** [comment]
这个明白了，从来没用过，我都隐藏了

**Comment by lolo1024** [comment]
![image](https://github.com/user-attachments/assets/3d73c2fd-0b75-4a16-874c-4168630c4ea4)
这个是网站设置吗？运行了20多分钟还没结束

**Comment by xjh22222228** [comment]
你保存了爬取规则，影响构建速度，建议在空闲时间去更新信息， 而且你的网站太多了6K， 把并发数量拉大点。
