### ISSUE TITLE
希望能够自动获取网站图标

### ISSUE THREAD

**Issue by dishao123** [xjh22222228/nav#305]
默认的字母太丑了

**Comment by xjh22222228** [comment]
这个功能本来就有，哪个网站获取不到图标？

可以将所有网站自动更新图标； 添加网站输入网址就能自动填入信息。

**Comment by dishao123** [comment]
@xjh22222228 不好意思，因为我看到有些网站没有图标，是什么原因导致的呢？
![4988038068703440384](https://github.com/user-attachments/assets/4a29d0c4-a658-4bdf-af07-3475762b74ec)

**Comment by xjh22222228** [comment]
早期数据，如果想更新，在后台爬取规则里更新一下抓取更新。

为了能够每个人傻瓜化更新，防止冲突，不再更新导航数据了，需要自己去添加。

**Comment by dishao123** [comment]
@xjh22222228 我还有一个问题，就是修改底部信息不生效

具体就是修改之后，点击保存，提示成功
![4988038068703440382](https://github.com/user-attachments/assets/0258e16e-b163-4473-b7e8-09a4c04f05d6)

但是前台没变化
![4988038068703440383](https://github.com/user-attachments/assets/e32d42ab-f23f-4794-915f-338323a1d9fa)

回到后台刷新之后，又变成默认的了
![4988038068703440394](https://github.com/user-attachments/assets/615e27a5-9cc7-4e75-b37d-598e32fb3b92)

**Comment by xjh22222228** [comment]
保存的时候有提示，要等构建完成才能生效，每次保存需要构建好再操作。

**Comment by dishao123** [comment]
@xjh22222228 等了好久都没用

**Comment by xjh22222228** [comment]
我这边尝试了下是没问题的，我看你的也更新了

**Comment by dishao123** [comment]
我用的是 Vercel 一直不生效，不知道怎么回事

**Comment by dishao123** [comment]
我重新部署一下看看

**Comment by dishao123** [comment]
@xjh22222228 我还有问题，就是用户投稿是收费功能吗？99元会员有哪些内容？以后更换域名还要再收费吗？

**Comment by xjh22222228** [comment]
目前会员可以用户提交收录、以后不用网站了还可以导出到浏览器书签

一个授权码绑定一个域名，后续可以更换
