### ISSUE TITLE
功能建议：设置第三级目录可展开与合并，提供一个一键操作按钮，方便浏览与跳转

### ISSUE THREAD

**Issue by setdiaoyong** [xjh22222228/nav#31]
设置第三级目录可展开与合并，提供一个一键操作按钮，方便浏览与跳转！
第三级菜单前，是否可以增加logo？
![第三级菜单的合并与展开](https://user-images.githubusercontent.com/62551864/99137272-a151a680-2664-11eb-9fd3-e7798f74395a.png)

**Comment by xjh22222228** [comment]
已支持：
https://nav3.cn/#/index?page=2&id=5

https://github.com/xjh22222228/nav#%E6%9B%B4%E6%96%B0%E6%95%B0%E6%8D%AE

https://github.com/xjh22222228/nav/blob/master/data/node/deno.ts#L9

**Comment by setdiaoyong** [comment]
一个个点感觉好麻烦，也不能立刻跳转到需要的目录，能不能有一键切换的功能，页按钮或者悬浮侧边按钮都行，感谢作者的耐心，谢谢！

**Comment by xjh22222228** [comment]
跳转到需要的目录什么意思
