### ISSUE TITLE
http://www.w3.org/2000/svg 在https下无法访问，展开菜单的箭头图标无法加载

### ISSUE THREAD

**Issue by setdiaoyong** [xjh22222228/nav#32]

**Comment by xjh22222228** [comment]
1、你那里需要访问这个 http://www.w3.org/2000/svg ？  https 是没办法访问Http的。
2、图标是本地资源是可以加载的，多刷新几次？
3、一键展开折叠已经支持了 => https://nav3.cn/

**Comment by setdiaoyong** [comment]
> 1、你那里需要访问这个 http://www.w3.org/2000/svg ？ https 是没办法访问Http的。
> 2、图标是本地资源是可以加载的，多刷新几次？
> 3、一键展开折叠已经支持了 => https://nav3.cn/
  
确实是没有刷新出来！我只是看了浏览器的报错，快速加载出来，可以在浏览器强制刷新：ctrl + R或ctrl+F5。
折叠展开实现了，差个后台，就完美了，给你点赞！

**Comment by setdiaoyong** [comment]
> > 1、你那里需要访问这个 http://www.w3.org/2000/svg ？ https 是没办法访问Http的。
> > 2、图标是本地资源是可以加载的，多刷新几次？
> > 3、一键展开折叠已经支持了 => https://nav3.cn/
> 
> 确实是没有刷新出来！我只是看了浏览器的报错，快速加载出来，可以在浏览器强制刷新：ctrl + R或ctrl+F5。
> 折叠展开实现了，差个后台，就完美了，给你点赞！

还有一个自动与手动夜间模式

**Comment by xjh22222228** [comment]
关于后台已经有方案了，借助github issue 模板实现，可能需要一段时间。
