### ISSUE TITLE
功能需求：“英文，中文，github“ ---关联站点跳转按钮的自定义名称及任意添加多个。

### ISSUE THREAD

**Issue by setdiaoyong** [xjh22222228/nav#33]
功能需求描述：
一个站点，可能有多个子站点入口，或者有对应多种关联站点，希望能够自由添加相应的关联站点跳转按钮，谢谢！

![“英文，中文，github“ ---子站点跳转按钮的自定义名称及任意添加多个](https://user-images.githubusercontent.com/62551864/99181844-2d9ac100-276c-11eb-8362-dc79845bab90.png)

**Comment by xjh22222228** [comment]
这个之前有考虑过，你有没有好的方案？

**Comment by setdiaoyong** [comment]
> 这个之前有考虑过，你有没有好的方案？

1 界面的展示
1.1 可以采用angular@core的自带轮播或轮播组件，滚动展示按钮，然后，需要选择时，鼠标焦点放入后，支持鼠标滚轮滚动，以及点击上下翻页滚动条按钮，或者轮播组件自带的轮播按钮，左右键，或者圆点按钮
参考：
(https://segmentfault.com/a/1190000019453659?utm_source=tag-newest)
(https://www.cnblogs.com/m110/p/7683618.html)
(https://www.cnblogs.com/lixuekui/p/5854599.html)
(https://www.jq22.com/jquery-info20175)
就像下图轮播，把图片变成三个按钮，也不用后面的效果，左右加上翻页键或圆点索引键，感觉左右翻页键不错。
![image](https://user-images.githubusercontent.com/62551864/99469267-4af2a980-297d-11eb-931f-5442edadde6e.png)

2. 内部数据
套一下轮播的壳，也不用重构了。

**Comment by setdiaoyong** [comment]
> > 这个之前有考虑过，你有没有好的方案？
> 
> 1 界面的展示
> 1.1 可以采用angular@core的自带轮播或轮播组件，滚动展示按钮，然后，需要选择时，鼠标焦点放入后，支持鼠标滚轮滚动，以及点击上下翻页滚动条按钮，或者轮播组件自带的轮播按钮，左右键，或者圆点按钮
> 参考：
> (https://segmentfault.com/a/1190000019453659?utm_source=tag-newest)
> (https://www.cnblogs.com/m110/p/7683618.html)
> (https://www.cnblogs.com/lixuekui/p/5854599.html)
> (https://www.jq22.com/jquery-info20175)
> 就像下图轮播，把图片变成三个按钮，也不用后面的效果，左右加上翻页键或圆点索引键，感觉左右翻页键不错。
> ![image](https://user-images.githubusercontent.com/62551864/99469267-4af2a980-297d-11eb-931f-5442edadde6e.png)
> 
> 1. 内部数据
>    套一下轮播的壳，也不用重构了。

原生或angular实现会不会比jQuery实现性能好一些？

**Comment by setdiaoyong** [comment]
> > > 这个之前有考虑过，你有没有好的方案？
> > 
> > 
> > 1 界面的展示
> > 1.1 可以采用angular@core的自带轮播或轮播组件，滚动展示按钮，然后，需要选择时，鼠标焦点放入后，支持鼠标滚轮滚动，以及点击上下翻页滚动条按钮，或者轮播组件自带的轮播按钮，左右键，或者圆点按钮
> > 参考：
> > (https://segmentfault.com/a/1190000019453659?utm_source=tag-newest)
> > (https://www.cnblogs.com/m110/p/7683618.html)
> > (https://www.cnblogs.com/lixuekui/p/5854599.html)
> > (https://www.jq22.com/jquery-info20175)
> > 就像下图轮播，把图片变成三个按钮，也不用后面的效果，左右加上翻页键或圆点索引键，感觉左右翻页键不错。
> > ![image](https://user-images.githubusercontent.com/62551864/99469267-4af2a980-297d-11eb-931f-5442edadde6e.png)
> > 
> > 1. 内部数据
> >    套一下轮播的壳，也不用重构了。
> 
> 原生或angular实现会不会比jQuery实现性能好一些？

默认不滚动，当鼠标焦点移入时，进行自动滚动，如果要快速跳转，可以自己点击左右翻页键

**Comment by setdiaoyong** [comment]
给个按钮，然后弹出悬浮下拉菜单，进行滚动选择？

**Comment by setdiaoyong** [comment]
> 给个按钮，然后弹出悬浮下拉菜单，进行滚动选择？

运行开销控制，对性能影响，估计很大，毕竟有可能每个网址都添加了这个关联站点

**Comment by xjh22222228** [comment]
这个功能问题不大，目前已经在着手发布V5版本了，大概明天能发个稳定版本，这个需求 5.1 加上。

**Comment by xjh22222228** [comment]
v5.1.0
