### ISSUE TITLE
功能需求：增加搜索引擎支持，可以支持自定义，自己添加适配专业文献检索库的搜索入口

### ISSUE THREAD

**Issue by setdiaoyong** [xjh22222228/nav#35]
功能需求描述：
搞科研，需要查文献，需要用专业检索库，希望能够提供自定义搜索引擎支持，这样可以将部署的导航站作为浏览器新标签页了。

![搜索引擎自定义支持](https://user-images.githubusercontent.com/62551864/99184658-89bb1080-277f-11eb-9550-b434b4533eb6.png)

**Comment by xjh22222228** [comment]
已支持  https://github.com/xjh22222228/nav/blob/master/config/index.ts#L11
