### ISSUE TITLE
商业化建议：开发新标签页，或者浏览器插件，这样后台功能可以作为高级功能，进行商业化授权使用

### ISSUE THREAD

**Issue by setdiaoyong** [xjh22222228/nav#36]

**Comment by setdiaoyong** [comment]
还有一个分享功能

**Comment by xjh22222228** [comment]
浏览器插件这个方案可行。

**Comment by setdiaoyong** [comment]
> 浏览器插件这个方案可行。

以用户自己的github私有库为后台数据库，用github API操作，哈哈，白嫖使我快乐

**Comment by setdiaoyong** [comment]
> > 浏览器插件这个方案可行。
> 
> 以用户自己的github私有库为后台数据库，用github API操作，哈哈，白嫖使我快乐

国内外的各种继续git，有API的，都可以适配

**Comment by xjh22222228** [comment]
#28

**Comment by setdiaoyong** [comment]
如果能根据这个开源后端，实现用户登录，和数据私人化存储，就可以作为商业化。如果维护，和成本比PHP版的低，我想，有些技术服务公司还是愿意用的，比如我知道SCI论文润色服务公司就有用科研资源导航站，推广公司业务的需求（以前我给他们提过建议，觉得可行，只要能广泛传播，其实，我感觉他们意思是要强制关注微信公众号，强制分享的意思（也好实现，好多分享站点都是这样的），他们没明说），可以为科研人员提供共享型与私人化兼并的导航站，还是有市场的。但是具体与已有其他的php或其他数据库类型的实现，有哪些方面的优点，我也不清楚，还有开发成本的考虑。凡是想商业化落地的都不容易，唉。
