### ISSUE TITLE
浏览器不能实时看到新页面

### ISSUE THREAD

**Issue by dawei233** [xjh22222228/nav#38]
更改配置文件添加新网站后，浏览器必须清楚全部缓存才能看到新页面，咋刷新都不行，强制刷新也不行

**Comment by xjh22222228** [comment]
不会啊，这边都是正常的呢，你哪个网站。

**Comment by dawei233** [comment]
0.0确实不照我下的最新版的 3.0 我改了 blog 下面的index.ts文件 不清理浏览器缓存完全看不到修改 痕迹

>环境是在windows上面直接npm start运行的 

我试了chrome原版浏览器和chome edge都一样

>

**Comment by xjh22222228** [comment]
哦，开发环境是正常的，部署后不会出现这样。主要是做了缓存，添加网站不需要 start, 直接改文件 build 就行了。

**Comment by dawei233** [comment]
用nginx反代以后就正常了是吧。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xjh22222228/nav"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月8日(星期二) 上午10:21
收件人:&nbsp;"xjh22222228/nav"<nav@noreply.github.com&gt;;
抄送:&nbsp;"QQ邮箱提醒"<1252925775@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xjh22222228/nav] 浏览器不能实时看到新页面 (#38)





 
哦，开发环境是正常的，部署后不会出现这样。主要是做了缓存，添加网站不需要 start, 直接改文件 build 就行了。

**Comment by xjh22222228** [comment]
代不代理无所谓，反正 build 后就可以了。

**Comment by dawei233** [comment]
好的好的感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xjh22222228/nav"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月8日(星期二) 上午10:24
收件人:&nbsp;"xjh22222228/nav"<nav@noreply.github.com&gt;;
抄送:&nbsp;"QQ邮箱提醒"<1252925775@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xjh22222228/nav] 浏览器不能实时看到新页面 (#38)





 
代不代理无所谓，反正 build 后就可以了。

**Comment by setdiaoyong** [comment]
直接fork源代码main分支，然后用https://now.sh部署，可以快速build，显示页面，源代码有啥更新，跨fork库，比较后，创建pull request 可以进行更新
