### ISSUE TITLE
打包问题。

### ISSUE THREAD

**Issue by dawei233** [xjh22222228/nav#39]
WARNING in E:\nav-3.0.0-rc0\src\app\app-routing.module.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.

WARNING in E:\nav-3.0.0-rc0\src\environments\environment.prod.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.
打包报错这个 ，不知道有没有和我一样问题的0..0
解决办法：
找到tsconfig.app ts文件，删除"include":["src/**/*.ts"]这一行，只在文件中保留入口点(main.ts和polyfills.ts)
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "./out-tsc/app",
    "types": []
  },
  "files": [
    "src/main.ts",
    "src/polyfills.ts"
  ],

  "exclude": [
    "src/test.ts",
    "src/**/*.spec.ts"
  ]
}

**Comment by xjh22222228** [comment]
https://github.com/xjh22222228/nav#%E5%A6%82%E4%BD%95%E9%83%A8%E7%BD%B2

自动打包。

**Comment by dawei233** [comment]
> https://github.com/xjh22222228/nav#%E5%A6%82%E4%BD%95%E9%83%A8%E7%BD%B2
> 
> 自动打包。

0.0我是在本地整的。
