### ISSUE TITLE
相关信息收集：github作为数据库的资料收集

### ISSUE THREAD

**Issue by setdiaoyong** [xjh22222228/nav#44]
0.0.0 https://youtu.be/nPPlyjMlQ34
0.0 （不是github）最新的讨论总结了git for data https://www.dolthub.com/blog/2020-03-06-so-you-want-git-for-data/
 https://github.com/attic-labs/noms
0、Github API的高级包装。适用于浏览器。 https://github.com/github-tools/github
1、API布道者（****） https://github.com/kinlane  
（有利用github api构建应用的示例代码，使用GitHub来运行我的API Evangelist）
博客文章： 1、https://apievangelist.com/2017/01/23/no-database-behind-an-api-and-just-using-files-stored-on-github/
 2、https://apievangelist.com/2016/09/19/providing-yaml-driven-xml-json-and-atom-using-jekyll-and-github/
http://kinlane.com/2016/08/15/using-github-repos-and-jekyll-as-a-data-store/

****2013年前的Github.js为git的管道命令提供了一个最小的高层包装，提供了一个用于在文件级别上操作GitHub存储库的API。它是在GitHub的内容编辑器Prose的上下文中开发的。https://github.com/kinlane/github
**http://prose.io/
2  设想，有一些优缺点总结  https://github.com/DavidBruant/github-as-a-database

3、Github Pages 使用jekyll 驱动数据库，使用yaml 文件存储json xml等格式 https://github.com/api-evangelist-tools/xml-json-using-yaml-jekyll
4、关于方案的讨论，放弃Github Pages ，使用 node+sqlite，使用支持node部署的部署空间如https://glitch.com/或Vercel（以前称为Now.sh），或者使用非SQL的远程数据库 如Firebase（https://firebase.google.com/docs/auth/web/github-auth）或CouchDB（可能需要花费很多时间重新编码）https://dev.to/pdavor/how-to-use-mysql-database-on-github-io-4kbd
5、有力的建议：https://stackoverflow.com/questions/846659/how-can-i-put-a-database-under-git-version-control
6、Firebase ：https://stackoverflow.com/questions/31655085/database-on-a-personal-github-page
*7、分析了git作为NoSQL数据库（非模式数据库）的要点（分析的很好，从文章看，git做数据库很适合收集网址，适合分层，一次收集完，也不会再修改了）https://www.kenneth-truyers.net/2016/10/13/git-nosql-database/
这里有个最新的讨论，还提供作者kenneth的视频https://elixirforum.com/t/git-as-a-database-and-alternatives/27068

说kenneth用于生产环境了

*8、引用了上面7，并在7的基础上提升了，成为非裸机仓库，能够直接访问文件（不知道是不是在说node应用）。https://nede.dev/blog/turning-git-into-an-application-database   
提供可用代码，https://github.com/pruttned/owl-invoice
9、git的备份功能，也可以用与构建数据库
10、git gc 增量保存
11、子文件夹提高修改性能
12、避免产生需要手动合并的冲突，网址使用单个文件，用文件名保存编码
13、https://github.com/mirage/irmin Irmin是一个分布式数据库，遵循与Git相同的设计原则

14.https://github.com/libgit2/libgit2
15、https://github.com/elixir-git/xgit
16、https://medium.com/m/global-identity?redirectUrl=https%3A%2F%2Ftowardsdatascience.com%2Fgit-best-practices-for-sql-5366ab4abb50
17、https://github.blog/2020-02-14-automating-mysql-schema-migrations-with-github-actions-and-more/
18、node包，https://www.npmjs.com/package/github-db
19、https://github.com/KnpLabs/php-github-api
20、https://github.community/t/using-github-for-web-development-that-uses-a-database/1013
21、东芝nosql时间序列数据库https://griddb.net/en/
22、索引数据库 https://w3c.github.io/IndexedDB/  https://github.com/web-platform-tests/wpt/tree/master/IndexedDB
23、https://rethinkdb.com/docs/install-drivers/javascript/
*24、https://clojureverse.org/t/persistent-git-friendly-local-database-any-suggestions/3919/4

**Comment by xjh22222228** [comment]
https://github.com/xjh22222228/nav  v5.0.0-beta.1
