### ISSUE TITLE
一图胜万字：git存储与发布

### ISSUE THREAD

**Issue by setdiaoyong** [xjh22222228/nav#45]
![image](https://user-images.githubusercontent.com/62551864/102705597-5f9bc780-42c4-11eb-9eb1-fe808d346048.png)

高清可访问https://www.processon.com/view/link/5fded81c5653bb4ccf3bd520

**Comment by setdiaoyong** [comment]
网址收集以单个文件形式保存在github的优缺点论述
🚀 优点
1、网址的收集，可以在github中使用单文件形式存储，可能丧失一些性能，但是有优点
因为网址一旦整理了，基本上就很少再修改了
2、可以在fork开源代码的网站作者中相互拉取，仅在网站作者再次编辑，加工后产生改变，一旦优化好，拉取合并就不会有冲突。
3、可以在部署的网页上提供功能，实现在fork源代码的导航网站作者中，相互传递网页收集信息文件，实现分享功能，导航网站作者可以个性化收集编排网址信息，实现所有fork源代码的网址作者互通资源。
4、可以吸引浏览部署网址的访客，加入fork的阵营，成为一个导航网站的作者，为整个导航数据库增加新的网址，扩大社群。
5、合并冲突解决简单，调用方便
待续…………

🐞 缺点：
1、遍历几百上千的静态文件，性能有所降低，但是生产部署的那个国外up主有说，性能降低的程度还在接受范围内
2、发布可能需要额外创建分枝，合并拉取在网页实现功能，基于深度挖掘github最新的graphAPI的实现方式
待续…………

**Comment by xjh22222228** [comment]
功能已开发，参见：
https://github.com/xjh22222228/nav  v5.0.0-beta.1
