### ISSUE TITLE
添加数据时，token填写对了，但是提示（登录失败, 请填写正确Token，Request failed with status code 404）

### ISSUE THREAD

**Issue by kaliisra** [xjh22222228/nav#46]
测试存取的token也是对的，
![111](https://user-images.githubusercontent.com/66672984/104870143-bad3df00-5982-11eb-95a2-674ad6863766.PNG)
![2222](https://user-images.githubusercontent.com/66672984/104870147-bc9da280-5982-11eb-88fd-abb82715aa9c.PNG)

**Comment by xjh22222228** [comment]
https://github.com/kaliisra/nav/blob/main/nav.config.ts#L5

**Comment by kaliisra** [comment]
卧槽，我傻了
