### ISSUE TITLE
功能建议：收集的网址在所有fork源代码的fork库中能够相互拉取，实现fork库的建站者自己重组网址分类

### ISSUE THREAD

**Issue by setdiaoyong** [xjh22222228/nav#47]
收集的网址在fork库中相互拉取功能的应用场景描述：
导航站的网址收集，一部分来自访客的推荐，主要部分来自建站者的偏好，从源代码，进行最开始的网址收集工作，成本太高。个人觉得收集网址信息来源有：1、从建站者自己浏览器收藏夹导入（大部分）。2、访客在部署网址上提交（少量新颖的）3、拉取其他fork源代码库的其他建站者创建的网页上（页面提供拉取的按钮，可以大量快速填充一个建站者自己需要收集的分类）4、……

如果实现以github为大后台，每一个fork源代码库的建站者有自己的收集喜好，如果能够在其他fork库建立的站点中，将自己需要用的网址快速拉取到自己的站点，形成一个大社区，互助性，收集成本降低，这样才能有广泛的fork源代码的建站者

**Comment by setdiaoyong** [comment]
现在5.0版本是不是在向储存库存储(以后所有fork库作者都可以向其中提交收集的网址与分类)，但fork库作者的页面展示可以自定义，是否显示存储库中收集的网址，以及fork库作者自定义编排展示顺序和分类？

**Comment by xjh22222228** [comment]
是的，目前是支持排序和分类的。

**Comment by setdiaoyong** [comment]
收集的网址和关联网址，如果用单文件储存，即可方便所有fork库作者一起编辑，相互拉取。收集网址的特性就是一次收集，以后都是增加关联网址，以及修订，就很少更改，基本全是增量数据库，就像bug的补丁一样，每个fork库的作者都能从其他fork库作者添加或修订的补丁，拉取到自己的库，然后按照fork库作者的排序，进行部署展示。单个文件存储，会降低拉取后的合并冲突，让github的API后台自动合并到fork库，实现一人创建，分享给大家拉取，合并到各自的库中进行分类，展示。

**Comment by setdiaoyong** [comment]
在跨fork库中进行拉取，合并，还是得单文件存储收集的网址，减少合并时的冲突，提高自动合并的概率

**Comment by xjh22222228** [comment]
这个功能估计无法实现，Github API有频率限制，每个人Fork后可以更改分支、仓库名、记录等内容很难处理。

**Comment by setdiaoyong** [comment]
> 这个功能估计无法实现，Github API有频率限制，每个人Fork后可以更改分支、仓库名、记录等内容很难处理。

是的，要跨fork库，还要在网页端，调用Github API，确实很不好处理，单文件储存，可以直接全部舍弃之前的文件，创建一个新文件（ID值是新的），之前有外国小哥研究了，但是不是从网页端实现的。https://nede.dev/blog/turning-git-into-an-application-database
https://elixirforum.com/t/git-as-a-database-and-alternatives/27068/3
https://www.kenneth-truyers.net/2016/10/13/git-nosql-database/
https://github.com/pruttned/owl-invoice
https://stackoverflow.com/questions/846659/how-can-i-put-a-database-under-git-version-control/28123546#28123546
https://github.com/github-tools/github

 @@ 🔥  🚀 
**有一个建站工具有可能实现了**
https://www.netlifycms.org/docs/intro/
https://github.com/netlify/netlify-cms
**后端开源，直接就可以迁移过来用**
https://github.com/netlify/netlify-cms/tree/master/packages/netlify-cms-backend-github

**Comment by setdiaoyong** [comment]
> > 这个功能估计无法实现，Github API有频率限制，每个人Fork后可以更改分支、仓库名、记录等内容很难处理。
> 
> 是的，要跨fork库，还要在网页端，调用Github API，确实很不好处理，单文件储存，可以直接全部舍弃之前的文件，创建一个新文件（ID值是新的），之前有外国小哥研究了，但是不是从网页端实现的。https://nede.dev/blog/turning-git-into-an-application-database
> https://elixirforum.com/t/git-as-a-database-and-alternatives/27068/3
> https://www.kenneth-truyers.net/2016/10/13/git-nosql-database/
> https://github.com/pruttned/owl-invoice
> https://stackoverflow.com/questions/846659/how-can-i-put-a-database-under-git-version-control/28123546#28123546
> https://github.com/github-tools/github
> 
> @@ 🔥 🚀
> **有一个建站工具有可能实现了**
> https://www.netlifycms.org/docs/intro/
> https://github.com/netlify/netlify-cms
> **后端开源，直接就可以迁移过来用**
> https://github.com/netlify/netlify-cms/tree/master/packages/netlify-cms-backend-github

不用相互拉取合并了，fork库作者，直接从其他fork库作者的库中复制，在fork库创建新文件，就没有合并的问题，反正都是各自用的，有亢余，无所谓，确实跨fork库分享功能有点难。
