### ISSUE TITLE
点新增数据，授权登录框空白

### ISSUE THREAD

**Issue by cheercloud** [xjh22222228/nav#49]
点新增数据，授权登录框空白，无法登录，这个正常吗，还是我哪里配置没对
![image](https://user-images.githubusercontent.com/8170151/106693575-ba3d7880-6611-11eb-9ea9-4dfe8bb38581.png)

**Comment by xjh22222228** [comment]
已处理，重新Fork!

**Comment by cheercloud** [comment]
非常感谢，生效
