### ISSUE TITLE
功能需求：5.1.1版本 Side 模板的左侧侧边栏中，站点图标下面，增加一排展开与收起列表，切换黑暗/明亮等功能键

### ISSUE THREAD

**Issue by setdiaoyong** [xjh22222228/nav#50]

**Comment by setdiaoyong** [comment]
在左侧站点标志下面，加一排功能键，白底灰色图标，应该不违和

**Comment by xjh22222228** [comment]
需要什么功能, 你在用这款主题吗

**Comment by setdiaoyong** [comment]
> 需要什么功能, 你在用这款主题吗

我准备施工了，把我收藏的导入进去，这个side主题，比较好，我喜欢，如果在左侧站点标志下面，加上收起与展开左侧的side列表和第三级列表等功能按钮，就能完美实现快速从一级列表，快速跳转到二级列表，三级列表，而且大屏幕不用多次转动眼睛或脑袋（不是说sim和light不好） 🤣 ，毕竟作为一个浏览器导航站，高频使用的话，还是需要注意使用体验的。


![image](https://user-images.githubusercontent.com/62551864/107323753-caf26080-6ae1-11eb-88db-d3150495625b.png)

**Comment by setdiaoyong** [comment]
每个层级收起与展开的图标，我根据你左侧有个想法，除了旋转，还可以在横线前加上红点，表示对应的第几级目录，如二级目录就在第一长横线下的缩进的第二个短横线前加一个红点，三级目录的就继续在第第三个缩进的短横线前加个红点。

二级目录收起展开功能按钮图标的设计：
![image](https://user-images.githubusercontent.com/62551864/107325468-bf546900-6ae4-11eb-8923-be6dcb523c81.png)

三级目录收起展开功能按钮图标的设计：
![image](https://user-images.githubusercontent.com/62551864/107325549-e0b55500-6ae4-11eb-882f-5f293bea21eb.png)

不过设计这个东西，仅作参考。

**Comment by xjh22222228** [comment]
二级展开现在只会展开一层， 三级暂开和暗黑 右侧里有会不会重复。

**Comment by setdiaoyong** [comment]
> 二级展开现在只会展开一层， 三级展开和暗黑 右侧里有会不会重复。

个人觉得主要是为了这个主题，这个主题与其他不同，其他的一级标题是全部固定展示出来的，点击一级标题就可以切换二级标题，只要有展开收起三级标题的功能键就够了。而这个side主题二级标题是收在一级里面的，所以要特别增加展开收起二级标题功能键，导航站在大屏幕上，跳转各个层级的功能键的位置还是要特别设计。

**Comment by setdiaoyong** [comment]
三级标题上是否可以通过增加标签页，如element-UI中的标签页. https://element.faas.ele.me/#/zh-CN/component/tabs  实现第四级标题，不过四级标题是否有实现的价值，有待商榷。

**Comment by aifact** [comment]
> 二级展开现在只会展开一层， 三级展开和暗黑 右侧里有会不会重复。

右下角的悬浮按钮，可以不用加三级展开与收起按钮，目录在左上角，操作按钮还是需要跟随浏览过程，就像word的悬浮工具栏。还是在当前激活的二级目录标题后，加一个展开与收起三级目录的按钮，点到哪个二级目录，就在二级目录标题后面加一个这个按钮。快速进行三级目录的跳转，省的还要从最左上角，到最右下角，找那个展开与合并三级的按钮。参考 #53
