### ISSUE TITLE
功能需求：5.2.0 side主题布局的一些建议

### ISSUE THREAD

**Issue by setdiaoyong** [xjh22222228/nav#51]
Side主题适合建站点，可以实现站点个性化标志的展示
1、左侧站点图标区域固定，不随页面滚动，实现站点个性化标志的展示；
2、右侧底部悬浮按钮中，增加一键呼出搜索框，进行站内搜索；
3、或者搜索框是否能固定在哪，比如站点标志下？
4、站点标志下增加一排功能键，如跳转博客，登录后台，展开收起层级等。

**Comment by aiyou9** [comment]
Side主题的站点标志，是不是在展开二级标题的时候，可以固定？
![image](https://user-images.githubusercontent.com/15712822/107662523-5841da80-6cc5-11eb-87dd-5a62315c0c12.png)
