### ISSUE TITLE
🍷 功能需求：Side三级目录的快速展开与收起

### ISSUE THREAD

**Issue by setdiaoyong** [xjh22222228/nav#53]
需求描述：
Side的二级目录是需要点击一级标题后，才能显示，因此，鼠标还要移动到右侧悬浮按钮，才能一次性收起与展开三级目录，不够快捷
建议：
1、可以在二级目录的标题后面，增加展开/收起按钮，快速展开收起三级目录
![image](https://user-images.githubusercontent.com/62551864/107761763-de622d80-6d66-11eb-85cc-4dcf932bf7d6.png)

2、或者点击二级目录，跳转后的三级目录，默认是收起的

目的
就是为使得导航站，能够切实有效的利用。
1、减少目光的跳转，大屏幕，可能还要来回转头，这些都是不好；
2、集中功能按钮，或者在操作流程中增加相对应的功能按钮，快速实现工作流——查阅跳转，复制，分享等等

**Comment by setdiaoyong** [comment]
一点击一级标题，展开的二级标题每个都加这些按钮，太重复了，是否可以在进一步点击二级标题后，再出现这个收起与展开三级目录的按钮。

**Comment by setdiaoyong** [comment]
如果能根据这个开源后端，实现用户登录，和数据私人化存储，就可以作为商业化。如果维护，和成本比PHP版的低，我想，有些技术服务公司还是愿意用的，比如我知道SCI论文润色服务公司就有用科研资源导航站，推广公司业务的需求（以前我给他们提过建议，觉得可行，只要能广泛传播，其实，我感觉他们意思是要强制关注微信公众号，强制分享的意思（也好实现，好多分享站点都是这样的），他们没明说），可以为科研人员提供共享型与私人化兼并的导航站，还是有市场的。但是具体与已有其他的php或其他数据库类型的实现，有哪些方面的优点，我也不清楚，还有开发成本的考虑。凡是想商业化落地的都不容易，唉。

**Comment by setdiaoyong** [comment]
重新描述一下场景：

side主题，切换一级和二级目录，都在左边。而当前，展开与收起三级目录的功能键在右边，进行切换时， 要来回点击，如果大屏，可能不仅要动眼球，还要旋转脑袋，因此需要在左边添加一个展开/收起三级目录的功能键。利于快速切换。

这个功能键只有当点击到需要查看的二级目录时，才会显示，而且可以在按钮中，增加显示当前二级目录下网址数量的功能。

![image](https://user-images.githubusercontent.com/62551864/108232980-4a390180-717e-11eb-9579-ea9b75bd05b0.png)

**Comment by setdiaoyong** [comment]
个人觉得这个功能，在当前大屏幕还是有价值的，提高浏览翻阅效率

**Comment by aifact** [comment]
所有的主题，大屏幕使用nav时，浏览时，需要进行三级目录的收起与展开，最好能快速跳转，这个issue的想法，在当前激活的二级目录标题后面，增加一个按钮，一键收起与展开当前激活二级目录下的三级列表，还是有必要的，当前nav版本使用的，收起与展开三级列表的悬浮按钮，在左下角，每次都得从最右上角目录，移动鼠标到最右下角，点击，才能进行三级目录的收起与展开，不是很舒服，尤其时屏幕大的需要转动眼球，甚至脑袋，手动捂脸！
