### ISSUE TITLE
功能需求：以github做后台的重要参考！！！

### ISSUE THREAD

**Issue by setdiaoyong** [xjh22222228/nav#54]
@@ 🔥 🚀
有一个建站工具有可能实现了
https://www.netlifycms.org/docs/intro/
https://github.com/netlify/netlify-cms
后端开源，直接就可以迁移过来用
https://github.com/netlify/netlify-cms/tree/master/packages/netlify-cms-backend-github

但是不知道能否重构到本项目中。

**Comment by xjh22222228** [comment]
这个主要干嘛用

**Comment by setdiaoyong** [comment]
这个项目就是以github作为静态网站的后台，全静态建站的，能够有基于github 的用户登录等一系列功能，全开源的，可以构建到自己的网站上。

**Comment by xjh22222228** [comment]
后台已经有了呀， 优势在哪里

**Comment by setdiaoyong** [comment]
> 后台已经有了呀， 优势在哪里

我也没研究，主要是想看看，能否通过这个现成的开源包，能不能实现fork库作者之间的网页分享功能，能把其他fork库作者收集的网址，拉到自己fork后部署的站点下。都是基于github API的，看介绍，这个后台可以进行手动编辑啥的，也没啥优势。

**Comment by setdiaoyong** [comment]
> 如果能根据这个开源后端，实现用户登录，和数据私人化存储，就可以作为商业化。如果维护，和成本比PHP版的低，我想，有些技术服务公司还是愿意用的，比如我知道SCI论文润色服务公司就有用科研资源导航站，推广公司业务的需求（以前我给他们提过建议，觉得可行，只要能广泛传播，其实，我感觉他们意思是要强制关注微信公众号，强制分享的意思（也好实现，好多分享站点都是这样的），他们没明说），可以为科研人员提供共享型与私人化兼并的导航站，还是有市场的。但是具体与已有其他的php或其他数据库类型的实现，有哪些方面的优点，我也不清楚，还有开发成本的考虑。凡是想商业化落地的都不容易，唉。

@@ 🔥 🚀
有一个建站工具有可能实现了
https://www.netlifycms.org/docs/intro/
https://github.com/netlify/netlify-cms
后端开源，直接就可以迁移过来用
https://github.com/netlify/netlify-cms/tree/master/packages/netlify-cms-backend-github

**Comment by setdiaoyong** [comment]
> 后台已经有了呀， 优势在哪里

可能的一个优势：在部署站点，实现部署站点的github多用户注册，及用户各自从部署站点中，创建自己的网址分类展示信息。

**Comment by setdiaoyong** [comment]
> > 后台已经有了呀， 优势在哪里
> 
> 可能的一个优势：在部署站点，实现部署站点的github多用户注册，及用户各自从部署站点中，创建自己的网址分类展示信息。
https://www.netlifycms.org/docs/intro/ 这个是一个编辑静态文件的UI后台
