### ISSUE TITLE
功能需求：现在的Token登录方式，实现真正的github用户登录

### ISSUE THREAD

**Issue by setdiaoyong** [xjh22222228/nav#56]
功能描述
当前基于token登录方式，可以改成github用户登录授权的方式
建议
@@ 🔥 🚀
这个静态文件编辑的建站工具实现了
https://www.netlifycms.org/docs/intro/
https://github.com/netlify/netlify-cms
后端开源，直接就可以迁移过来用
https://github.com/netlify/netlify-cms/tree/master/packages/netlify-cms-backend-github

目标
后台登录的优化，一键搞定

**Comment by xjh22222228** [comment]
OAuth 需要依赖服务端的，涉及到 secret，故无法实现。

**Comment by xjh22222228** [comment]
准备支持  [https://github.com/xjh22222228/github-oauth2/tree/serverless](https://github.com/xjh22222228/github-oauth2/tree/serverless)

**Comment by aifact** [comment]
如果能支持，是否能把基于issue的评论功能增加上，还有访客登录后打星标（可能从GitHub评论中的添加表情入手，就是不知道GitHub有没有提供这个API），

**Comment by 2926295173** [comment]
解决这个问题，可以试试cloudflare的workers功能啊，已经有人用这个实现hexo的静态后台管理功能了， https://hexoplusplus.js.org/

**Comment by aifact** [comment]
> 解决这个问题，可以试试cloudflare的workers功能啊，已经有人用这个实现hexo的静态后台管理功能了， https://hexoplusplus.js.org/

后台如果跨站点配置，选择的方式就更多，目前，为了实现一次性部署，还是全用github实现后台比较好

**Comment by xjh22222228** [comment]
github 登录优势没发现，反而更麻烦， 实现这个还得考虑。

每个用户都得部署 [oauth2](https://github.com/xjh22222228/github-oauth2), 还得申请 [OAuth App](https://github.com/settings/applications/new)。

**Comment by aifact** [comment]
> github 登录优势没发现，反而更麻烦， 实现这个还得考虑。
> 
> 每个用户都得部署 [oauth2](https://github.com/xjh22222228/github-oauth2), 还得申请 [OAuth App](https://github.com/settings/applications/new)。

用户登陆了，好像也没啥事可做，还是直接用github issue做个评论系统

**Comment by aifact** [comment]
> github 登录优势没发现，反而更麻烦， 实现这个还得考虑。
> 
> 每个用户都得部署 [oauth2](https://github.com/xjh22222228/github-oauth2), 还得申请 [OAuth App](https://github.com/settings/applications/new)。

如果部署在vercel，确实要额外的无服务的跳转

**Comment by aifact** [comment]
> github 登录优势没发现，反而更麻烦， 实现这个还得考虑。
> 
> 每个用户都得部署 [oauth2](https://github.com/xjh22222228/github-oauth2), 还得申请 [OAuth App](https://github.com/settings/applications/new)。

主要看访客登陆后，能做些啥

**Comment by aifact** [comment]
> 如果能支持，是否能把基于issue的评论功能增加上，还有访客登录后打星标（可能从GitHub评论中的添加表情入手，就是不知道GitHub有没有提供这个API），

看基于github issue的评论系统与blog系统，都是可以加表情的，加个代码统计一下所有评论中好评类与差评类不同表情的，可以作为访客评价

**Comment by aifact** [comment]
> github 登录优势没发现，反而更麻烦， 实现这个还得考虑。
> 
> 每个用户都得部署 [oauth2](https://github.com/xjh22222228/github-oauth2), 还得申请 [OAuth App](https://github.com/settings/applications/new)。

你这里说的用户，是指使用nav3源代码建站的用户？还是导航站访客？

**Comment by aifact** [comment]
> > github 登录优势没发现，反而更麻烦， 实现这个还得考虑。
> > 每个用户都得部署 [oauth2](https://github.com/xjh22222228/github-oauth2), 还得申请 [OAuth App](https://github.com/settings/applications/new)。
> 
> 你这里说的用户，是指使用nav3源代码建站的用户？还是导航站访客？

在团队中需要核心人员撰写开发文档，统一名词，破除交流障碍！！！最近刚看了一些团队协作的书
