### ISSUE TITLE
🍷 功能需求：在搜索时，如何显示出搜索到的网址，在目录中的分类层级，以后就知道在哪找

### ISSUE THREAD

**Issue by setdiaoyong** [xjh22222228/nav#60]

**Comment by xjh22222228** [comment]
在描述下面加一个面包屑怎么样

**Comment by setdiaoyong** [comment]
> 在描述下面加一个面包屑怎么样

定位目录不是常用的功能，只有在经常用时，才会查找到具体目录，因此放在界面上不是很清爽，也不好放，还是用触控按钮（碰触就凸起），然后显示悬浮窗，在里面显示目录层级，这样鼠标触及才会显示，保持整体的整洁。

![image](https://user-images.githubusercontent.com/62551864/108085998-e1378800-70b0-11eb-8e4f-21a5bc678d16.png)

**Comment by setdiaoyong** [comment]
增加一个全部展开按钮，然后是否可以在浏览器搜索页面去查询，定位
