### ISSUE TITLE
功能需求：搜索是否能够搜索收集在站定中的具体网址，而不仅仅是描述

### ISSUE THREAD

**Issue by setdiaoyong** [xjh22222228/nav#61]

**Comment by xjh22222228** [comment]
现在也可以吧

**Comment by setdiaoyong** [comment]
不能搜到
比如智联招聘的网址是
https://www.zhaopin.com/
搜zhaopin，没有搜索到
![image](https://user-images.githubusercontent.com/62551864/107876641-19e52f00-6f02-11eb-8869-efbe6aa17f70.png)
