### ISSUE TITLE
功能需求：增加备份功能

### ISSUE THREAD

**Issue by setdiaoyong** [xjh22222228/nav#64]

**Comment by xjh22222228** [comment]
怎么个备份法。

**Comment by setdiaoyong** [comment]
点击如下图备份按钮，在github库中把当前已收集的网址数据db.json（也可加上nav.config.ts，一起），复制到一个备份文件夹，文件名加上当前时间，如2021/2/14-20:27:07-db.json，这样防止误删除啥的，以后也可以增加，进入管理后台就自动先备份一下等可选功能。

![image](https://user-images.githubusercontent.com/62551864/107876724-a4c62980-6f02-11eb-8ed9-5eddc7ad4563.png)

**Comment by xjh22222228** [comment]
我感觉这个备份功能没有多大用处，什么场景需要用到。

**Comment by setdiaoyong** [comment]
> 我感觉这个备份功能没有多大用处，什么场景需要用到。

我用edge浏览器，设置好三级目录，不断收藏新网址，过一段时间，就准备导入一次，每次都是全部数据被更新，但是我在页面也提交或删除了一些网址，也想保留更改，所以怎么能够将浏览器不断增加的，与我再部署页面后台中的修改，进行合并。我想的是用github的pull request，进行合并，如果没有冲突，就合并，如果有冲突，可以在本地桌面进行冲突处理，然后合并。实现，多来源的合并增加。
