### ISSUE TITLE
功能需求：第三级目录的标题字体与颜色，以及收集站点数量显示的优化

### ISSUE THREAD

**Issue by setdiaoyong** [xjh22222228/nav#65]

**Comment by xjh22222228** [comment]
怎么优化

**Comment by setdiaoyong** [comment]
是否可以将三级列表中，收集网址数量，放到前面的圆圈中。
![image](https://user-images.githubusercontent.com/62551864/107879921-adc0f600-6f16-11eb-9b6d-19763e3230b3.png)


三级标题字体的字号再小一点
涉及到设计，仅供参考

**Comment by xjh22222228** [comment]
如果数量超过2位怎么办

**Comment by setdiaoyong** [comment]
> 如果数量超过2位怎么办

所有圆圈大小以最大的为准，所有的都是中部居中。或者用方块，不用圆圈，用下图这种方形图形
![image](https://user-images.githubusercontent.com/62551864/107880843-4dcd4e00-6f1c-11eb-9075-827e1055d500.png)
自己设计的，仅供参考
![image](https://user-images.githubusercontent.com/62551864/107881078-84579880-6f1d-11eb-9582-d315d6265660.png)

**Comment by xjh22222228** [comment]
还有更好的优化空间吗，数量基本不会超过3位数，但如果超过3位数还是有问题。

**Comment by setdiaoyong** [comment]
> 还有更好的优化空间吗，数量基本不会超过3位数，但如果超过3位数还是有问题。

数量显示并不是重要展示信息，如果会限制收录网址数量，可以不显示数量。

**Comment by setdiaoyong** [comment]
收集网址的数量，这个数字也可以使用触及三级目录前的图标（图标可以加动画，增大）后，展示悬浮弹窗，显示目录下的数量，不用在页面显示
