### ISSUE TITLE
文档增改：访问用户用自己的Token登录后，也能在访问的Nav导航站中添加删除网址吗？希望添加这部分的说明。

### ISSUE THREAD

**Issue by setdiaoyong** [xjh22222228/nav#71]

**Comment by setdiaoyong** [comment]
在https://nav3.cn/#/admin  后台添加了一个网址，但是点击同步后，报404

![image](https://user-images.githubusercontent.com/62551864/107908444-0634d980-6f91-11eb-908b-f0c8577f23a7.png)

**Comment by xjh22222228** [comment]
应该是没权限。

**Comment by xjh22222228** [comment]
不行，每个用户都能修改就有安全问题，这个得自己在设置里添加组织。

**Comment by setdiaoyong** [comment]
> 不行，每个用户都能修改就有安全问题，这个得自己在设置里添加组织。

能不能创建Pull requests，或者像需手动维护的网站分类 ，可以点击编辑，修改后，通过github后台，提交让网址部署者自己确定是否合并，对db.json，是否也能这样，在用token登录后，进行编辑后，在自己的github产生patch-1 ，然后提交给网址部署者。
![image](https://user-images.githubusercontent.com/62551864/107916017-80208f00-6fa0-11eb-888d-ee7cb74af193.png)

增加后提交
![image](https://user-images.githubusercontent.com/62551864/107916251-f3c29c00-6fa0-11eb-93ce-a85e6c3e43d7.png)
 比对变化，创建pull request，给访问网页作者的github库
![image](https://user-images.githubusercontent.com/62551864/107916252-f3c29c00-6fa0-11eb-804f-5c86b47d215f.png)

也可在7处改成自己的库的main，将patch-1的分支与main合并
![image](https://user-images.githubusercontent.com/62551864/107916366-2ec4cf80-6fa1-11eb-9f3f-2b7edc44a2bf.png)

**Comment by setdiaoyong** [comment]
安全问题第一位，不过pull request还是可以实现的提交的，不过现在是单个db.json. 还是得小心处理
