### ISSUE TITLE
功能需求：图标本地化上传，云端储存，多方CDN优选后加载

### ISSUE THREAD

**Issue by setdiaoyong** [xjh22222228/nav#74]
在部署网页，从本地上传图标

1、图床
https://blog.csdn.net/qq_36227473/article/details/108630632
2、github源代码库
3、网盘直链

**Comment by setdiaoyong** [comment]
> 在部署网页，从本地上传图标
> 
> 1、图床
> https://blog.csdn.net/qq_36227473/article/details/108630632
> 2、github源代码库
> 3、网盘直链

提供上传接口就行，github中有项目，如picgo那种的，就有很多接口

**Comment by xjh22222228** [comment]
图床不考虑了，挂掉早晚的事情，放在github会好一些，建一个分支存储图片怎么样。

**Comment by setdiaoyong** [comment]
> 图床不考虑了，挂掉早晚的事情，放在github会好一些，建一个分支存储图片怎么样。

嗯，那就在github储存，就是需要考虑访问速度，需要考虑是否可以一键自动化部署到多个自动构建服务器，如https://vercel.com/，https://www.netlifycms.org/，https://www.jsdelivr.com/  ，cloudflare   以及如何将静态资源放到CDN等，然后是否可以从中优选加载？

加速访问的参考资料：
https://blog.csdn.net/huiruwei1020/article/details/107728435

https://www.imooc.com/article/304189?block_id=tuijian_wz

https://monkeywie.cn/2020/08/20/fast-github-page-with-cloudflare/
https://www.codercto.com/a/112963.html
https://removeif.github.io/theme/github-page%E7%BD%91%E7%AB%99cdn%E4%BC%98%E5%8C%96%E5%8A%A0%E9%80%9F.html

https://blog.csdn.net/weixin_34568812/article/details/105983348

**Comment by xjh22222228** [comment]
CDN: https://raw.sevencdn.com

https://raw.sevencdn.com/xjh22222228/nav/main/logo.png

**Comment by xjh22222228** [comment]
已支持，创建 image 分支。

**Comment by setdiaoyong** [comment]
这个CDN真的快，是否有接口，能够添加自己CDN，或者静态文件自己的存储位置。或者加载缓慢，就从多个CDN中优选一个加载
