### ISSUE TITLE
界面美化：网址评级，登录后，可以在每个网址标签上，点亮几颗五角星，进行网址评级

### ISSUE THREAD

**Issue by setdiaoyong** [xjh22222228/nav#76]
![image](https://user-images.githubusercontent.com/62551864/108087828-c36b2280-70b2-11eb-9413-dd4cb5f092e1.png)

**Comment by xjh22222228** [comment]
已支持

**Comment by setdiaoyong** [comment]
> 已支持

我再看看，这个星星的颜色，去调个色
