### ISSUE TITLE
🌟  核心功能：多个来源的网址的合并，尤其是不断收集的浏览器收藏夹文件与部署页面后台删除修改后的文件合并。

### ISSUE THREAD

**Issue by setdiaoyong** [xjh22222228/nav#77]
场景描述：
我用edge浏览器，设置好三层文件夹，不断收藏新网址，过一段时间，就准备导入一次，每次都是全部数据被更新，但是我在页面也提交或删除了一些网址，也想保留更改，所以怎么能够将浏览器不断增加的，与我在部署页面后台中的修改，进行合并。我想的是用github的pull request，进行合并，如果没有冲突，就合并，如果有冲突，可以在本地桌面进行冲突处理，然后合并。（之前提备份功能需求，就是把之前在部署页面后台修改的，备份下下来，然后提交浏览器的收藏夹文件，然后在桌面软件中拉取，用备份文件替换内容后，提交，然后进行冲突解决，然后推送到github合并）
目的：
为了实现多来源的网址信息，进行合并。

**Comment by xjh22222228** [comment]
手动解决冲突不可靠，网址太多都不好处理。

目前导入会检测一级分类是否存在，会将浏览器书签覆盖现有。

能不能这样：将书签合并到现有的，如果现有的已存在就跳过，否则添加导入进去。

**Comment by setdiaoyong** [comment]
> 将书签合并到现有的，如果现有的已存在就跳过，否则添加导入进去。

可以以这种增量添加方式，也可能需要考虑这样的场景：在部署网址删除了收集的网址，以后再次导入的书签中未删除，如何解决。

还有，浏览器添加收藏，可在多个文件夹中创建重复的收藏，不知道是浏览器本身，还是插件，还能为每个网址加载一个图标，格式是data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAB3ElEQVQ4jY2TP2hTYRTFf/clD1LBJCaBoHVJbCpC0CGIdIhkLOiiOLSOUtvRURw6OYgUCiIIleDg4CS46NZBdAgipVCQElMTKoHwQGNipSY88q5Dkudr8iKe6eM795xz7/dHGMHMzMqcaO8ByGVABtsK+k4lcG9vb6PkrR8WkMncSqOBRyhXR02PQHiN9O5UKs+qrkEmvXwF9AVC+J/iIZSfIDcr1adv5Gxq6bxjyAcg9F/iv+gYjl4KxOO5x8CFqGmznPqCIUr99zFfxVzsG9dP1Sn/CtNxAkFEEgZoHqCQsFic3mc9u03UtMfEUdNmPbvN4vQ+hYQ1nCUfVCQJYHVDNDr9KVZnP/GycZpSM+Em3zhZd3mrGxochSQlc+a2jiadO97m4okmhXg/6e33JB9/xNg9iNCyzSOdBUdbbdkmpWaC3YOIa/D8a2pM6DVQPO/Ba/SklnHXE6CGoNZEVgXVMW8XgloGamz6kVHTJhtukQ23fG9lkL9piDprQGeUy0WazCcbzCcb5CJNP3lH1FkzyrXijoougB562a12DKs7hdWdYqsdG40+VNGFcq244w6YTq9kAuI8BK5NHLqPVz017larGxXwOf3Z1FJeDe77fWdxWP1cK7731v8BAFGxisGcnWIAAAAASUVORK5CYII=

导入到nav，也能显示图标（
![image](https://user-images.githubusercontent.com/62551864/108165635-da028f80-712d-11eb-8c8b-eb2fbe32f1c2.png)
），虽然不清晰。
![image](https://user-images.githubusercontent.com/62551864/108165519-ab84b480-712d-11eb-9640-a08d73a377dc.png)

**Comment by setdiaoyong** [comment]
还有一个场景，多个浏览器，以一定的目录层级，分别收集，最后一起统一导入到Nav上，完成合并

**Comment by setdiaoyong** [comment]
场景2：一个网址在不同浏览器的收藏夹中，收藏在不同目录下，在增量添加中怎么处理，是否可以为后导入的加上标签云

**Comment by aifact** [comment]
能不能把收藏栏文件夹中不符合分类层级要求，在导入时，自动创建一个新的，如叫 “未分类” 的目录层级，用于多个浏览器合并

**Comment by xjh22222228** [comment]
已实现。

**Comment by aifact** [comment]
已测试，有个问题，能不能在nav的已分类的文件夹下，用 ”未分类“ 来补齐层级，比如，nav需要三级目录，但是浏览器里收藏到了第一级目录或第二级目录，现在的导入后的处理是全部移到一个新的未分类-未分类-未分类，能不能  改为， 已有的第一级目录-未分类-未分类，或  已有的第一级目录-已有的第二级目录-未分类，这样在各个目录层级下创建未分类，补齐？

**Comment by aifact** [comment]
还有一个问题，就是导入时，凡是有分类不正确的新网址导入时，相应的目录层级，也被加到未分类中了。
![image](https://user-images.githubusercontent.com/79238945/112762823-6f017e00-9034-11eb-96f7-72ee850a90c7.png)

**Comment by aifact** [comment]
还有一个问题，把所有层级的目录，全在未分类中添加了一遍，使用的网址都用的是站点部署域名

**Comment by aifact** [comment]
如果能够在页面上实现拖拽网址展示页，进行分类调整，我看过，鼠标左键长摁把网址展示页提出来，展示页就跟着鼠标，然后摁住鼠标左键，去找需要放入的分类，鼠标指到哪，哪就自动展开，，找到了后，松开鼠标左键，就把网址展示页放入。

**Comment by aifact** [comment]
如果能够在页面上实现拖拽网址展示页，进行分类调整，我看过，鼠标左键长摁把网址展示页提出来，展示页就跟着鼠标，然后摁住鼠标左键，去找需要放入的分类，鼠标指到哪，哪就自动展开，，找到了后，松开鼠标左键，就把网址展示页放入。

**Comment by xjh22222228** [comment]
你说的问题这边未能复现，Chrome， 你能发下最小可复现的书签文件吗。

**Comment by aifact** [comment]
> 你说的问题这边未能复现，Chrome， 你能发下最小可复现的书签文件吗。

你试试将扩展程序，收藏到收藏栏，再导入

**Comment by aifact** [comment]
> > 你说的问题这边未能复现，Chrome， 你能发下最小可复现的书签文件吗。
> 
> 你试试将扩展程序，收藏到收藏栏，再导入

> > 你说的问题这边未能复现，Chrome， 你能发下最小可复现的书签文件吗。
> 
> 你试试将扩展程序，收藏到收藏栏，再导入

应该不是这个问题，我用nav3.cn 登录我的token，然后上传浏览器收藏，也出现了这个问题，只新建了目录，未将目录下的网址加入，而是全部加到了未分类-未分类-未分类，还在其中将目录也作为网址收藏了，使用的是当前部署域名；

1、可能与字符有关，？
2、还是网络没有加载出js？

书签文件：

[bookmarks_2021_3_30.html.txt](https://github.com/xjh22222228/nav/files/6230340/bookmarks_2021_3_30.html.txt)


导入效果

![image](https://user-images.githubusercontent.com/79238945/113018876-90d53f00-91b3-11eb-976d-87cb93edfaad.png)

**Comment by aifact** [comment]
> 你说的问题这边未能复现，Chrome， 你能发下最小可复现的书签文件吗。

在部署好的nav3.cn，测试

**Comment by xjh22222228** [comment]
已修复。

**Comment by aifact** [comment]
> 已修复。

side主题的第一个三级目录，被置顶的图标遮挡。建议在nav3.cn也加上置顶图标，方便看出这个问题

**Comment by aifact** [comment]
> 已修复。

如果浏览器收藏夹导出文件中，如果第一级目录文件夹下有网址，虽然创建了未分类，但是会导致该一级目录下，三级目录移位，主要是向上一个二级目录添加了这个二级目录的所有三级目录

**Comment by xjh22222228** [comment]
你说的这个是Ui问题，还是功能问题。

**Comment by aifact** [comment]
> 你说的这个是Ui问题，还是功能问题。

两个都有，1、ui顶部遮挡，我再在nav3. cn登陆后，设置置顶检测一下。2、功能问题，就是导入的时候，如果浏览器收藏夹的一级目录文件夹下有收藏的网址，虽然会在nav导航创建未分类的目录，但是会导致 该一级目录下所有二级目录中都按顺序会添加下一个二级目录中所有的三级目录，而且最后一个二级目录有可能会成空的。这个只要在各个层级对应的文件夹里加网址收藏，应该很好复现。

还有一个场景需要关注，就是收藏夹第三级之后还存在多级文件夹，怎么处理，这个需要再关注一下。


感觉测试用例，还是需要花点心思的，每个方向都不容易

**Comment by aifact** [comment]
![image](https://user-images.githubusercontent.com/79238945/113238937-4c918e00-92dc-11eb-964e-5e4e1218456b.png)
![image](https://user-images.githubusercontent.com/79238945/113238953-50251500-92dc-11eb-8cfe-f98bd5cc7425.png)

![image](https://user-images.githubusercontent.com/79238945/113238961-53b89c00-92dc-11eb-8581-6dd9ffe4f3d2.png)

**Comment by aifact** [comment]
感觉要各个目录层级，都添加一些网址收藏，以及新建超过3层目录层级作为测试用例，    如仅多了4级文件夹，就全部放未分类-4级文件夹目录-未分类；中，如果更多，可以尝试开发功能，在标题中，对未分类前增加已经放入的目录标题，中间用>等符号分割，如三级目录下，导入时有更细分的四层级，就在二级目录下，增加一个未分类--新增三级目录标题（标题为：三级目录>导入的第四级标题））也可在三级标题下用面包屑进行增加，无限层级，或者用tab标签页

**Comment by xjh22222228** [comment]
你说的问题一直没能复现出来，你再试试，三级后面的不考虑了，已经到顶了。

**Comment by aifact** [comment]
> 你说的问题一直没能复现出来，你再试试，三级后面的不考虑了，已经到顶了。

好的，我在你的nav3. cn上复现一下，然后把最小的复现上传到这里

**Comment by aifact** [comment]
> 你说的问题一直没能复现出来，你再试试，三级后面的不考虑了，已经到顶了。

是浏览器的问题，同样的文件，我导入多个浏览器，其中，新版edge和360极速浏览器导出文件，导入nav，就会出我这个问题，而谷歌浏览器导出文件，再导入nav，就不会像上面那样，估计是各个浏览器的导出文件的内容与编排格式还是有差别的。

**Comment by aifact** [comment]
> 你说的问题一直没能复现出来，你再试试，三级后面的不考虑了，已经到顶了。

是否需要提供测试的收藏夹导出文件？

**Comment by xjh22222228** [comment]
应该没问题了，再试一下。

**Comment by aifact** [comment]
> 应该没问题了，再试一下。

已测试，暂未发现问题。

但希望实现，导入后新建的未分类，在各个级别列表中统一一下顺序，要么排第一位，要么排最后，当前问题是：如果是自己在nav3部署网页新建的未分类，或者浏览器收藏夹新建的未分类，与导入时代码新建的未分类，在各级标题下排位顺序不一致。

**Comment by aifact** [comment]
合并还有一个待开发的功能，就是同一个三级标题目录下，同一个站点的不同子页面，在导入时，自动合并，需要实现网址标签页带有展开按钮，将其收录其中。
例如meetsidekick.com浏览器的新标签页实现的那样：
把GitHub的浏览历史，进行自动的分类，将其分成了各个相应的类别
![image](https://user-images.githubusercontent.com/79238945/114773262-68e3ff00-9da1-11eb-9886-d681c6cd2ab1.png)

**Comment by aifact** [comment]
还有一个场景需要考虑，浏览器收藏夹导入nav3后，在nav3进行了删除与调整网址分类的处理，但是本地电脑中的浏览器收藏夹并未进行处理，当本地浏览器收藏夹，继续搜集后，再次导入nav3后，是否会将之前在nav3删除与调整的又再一次加上？

**Comment by aifact** [comment]
> 还有一个场景需要考虑，浏览器收藏夹导入nav3后，在nav3进行了删除与调整网址分类的处理，但是本地电脑中的浏览器收藏夹并未进行处理，当本地浏览器收藏夹，继续搜集，再次导入nav3后，是否会将之前在nav3删除与调整的网址又再一次加上？

感觉就是个版本控制的问题，不知道通过GitHub自带的git服务器能否解决这个在nav3有删除与调整网址的处理，相当于git的提交，合并与解决冲突
