### ISSUE TITLE
功能需求：站点 logo图标，可不可也上传到imge分支，从CDN走

### ISSUE THREAD

**Issue by setdiaoyong** [xjh22222228/nav#78]

**Comment by xjh22222228** [comment]
已加CDN， 合并 image 分支

**Comment by setdiaoyong** [comment]
确实CDN要等10min以上，

**Comment by setdiaoyong** [comment]
> 确实CDN要等10min以上，

我这等了一天了，CDN还没更新，明天再看看

**Comment by xjh22222228** [comment]
实际上已经更新了，缓存问题，多刷几次。 更新图片就会有这种问题，新建的图片都正常的。

**Comment by setdiaoyong** [comment]
> > 确实CDN要等10min以上，
> 
> 我这等了一天了，CDN还没更新，明天再看看

有可能这个CDN每天有更新次数限制，我是更新了第一次，过一段时间就显示了，但是第二，第三次上传logo，CDN就不继续更新了。明天再看看。

**Comment by setdiaoyong** [comment]
> > > 确实CDN要等10min以上，
> > 
> > 
> > 第一次更新logo，一段时间后成功了，但是紧跟着第二次更新，我等了一天了，CDN还没更新，明天再看看
> 
> 有可能这个CDN每天有更新次数限制，我是更新了第一次，过一段时间就显示了，但是第二，第三次上传logo，CDN就不继续更新了。明天再看看。

确实要刷新，总算刷出来了
