### ISSUE TITLE
🍷  功能需求：Side主题，顶部搜索框下，增加一排快捷图标，自由从收集网址中添加，快速访问

### ISSUE THREAD

**Issue by setdiaoyong** [xjh22222228/nav#79]
![image](https://user-images.githubusercontent.com/62551864/108106397-dab50a80-70c8-11eb-8936-e363f0a8fb2d.png)

**Comment by setdiaoyong** [comment]
如果不好实现，也可手动添加，登录后在最后一个，给一个加号图标，手动添加，如果这一排不够，能够继续支持上下翻页，或者展开，这样可以增加很多个，就更好了

**Comment by xjh22222228** [comment]
没理解这个需求。

**Comment by setdiaoyong** [comment]
> 没理解这个需求。

应用场景:
以Nav导航页做浏览器主页，有一些需要快速打开的网址，就可以像上面描述的那样添加在搜索框下面（始终显示），上面的数字是不同网址的图标（也可以在后面增加一个展开的按钮，可以查看多行），点击就能快速跳转到需要访问的网址，就像https://www.jianfast.com/ 

![image](https://user-images.githubusercontent.com/62551864/108190495-f9f57b80-714c-11eb-8f39-b6395e201e46.png)


 或
 https://github.com/linuxserver/Heimdall  等主页项目。
![image](https://user-images.githubusercontent.com/62551864/108190431-e518e800-714c-11eb-88e8-c54052ddd0de.png)

**Comment by xjh22222228** [comment]
能不能这样：在添加网址的时候加一个开启条件，如果开启了就显示在顶部。

**Comment by setdiaoyong** [comment]
> 能不能这样：在添加网址的时候加一个开启条件，如果开启了就显示在顶部。

赞，是的，这样更好

**Comment by setdiaoyong** [comment]
> 能不能这样：在添加网址的时候加一个开启条件，如果开启了就显示在顶部。

可能还有一个排序的问题。

**Comment by setdiaoyong** [comment]
> 能不能这样：在添加网址的时候加一个开启条件，如果开启了就显示在顶部。

可能还有一个排序的问题。

**Comment by setdiaoyong** [comment]
> 能不能这样：在添加网址的时候加一个开启条件，如果开启了就显示在顶部。

可能还有一个排序的问题。

> > 能不能这样：在添加网址的时候加一个开启条件，如果开启了就显示在顶部。
> 
> 可能还有一个排序的问题。

登录后，在页面上手动拖动，排序？

**Comment by setdiaoyong** [comment]
> 能不能这样：在添加网址的时候加一个开启条件，如果开启了就显示在顶部。

可能还有一个排序的问题。

> > 能不能这样：在添加网址的时候加一个开启条件，如果开启了就显示在顶部。
> 
> 可能还有一个排序的问题。

登录后，在页面上手动拖动，排序？

**Comment by xjh22222228** [comment]
功能已出，看看是否需要调整。

**Comment by setdiaoyong** [comment]
> 功能已出，看看是否需要调整，排序后面再加。

标题导致的图标间距不均一，是否可以标题，使用鼠标触及图标，就弹出显示。

![image](https://user-images.githubusercontent.com/62551864/108395166-78871180-7250-11eb-8d1e-78d8dae8c286.png)

**Comment by setdiaoyong** [comment]
> 功能已出，看看是否需要调整，排序后面再加。

当前翻页后，图标未添加到顶部，搜索栏，下方

![image](https://user-images.githubusercontent.com/62551864/108395471-c6037e80-7250-11eb-9040-d015493cd88e.png)
目标
翻页后，图标是否可以添加到顶部，搜索栏，下方

**Comment by setdiaoyong** [comment]
> 功能已出，看看是否需要调整，排序后面再加。

置顶图标，未来也可以支持分类，如工作，娱乐，新闻，等，然后直接分类置顶，每个分类以呼出下拉tab的形式，进行展示。
![image](https://user-images.githubusercontent.com/62551864/108458112-ecf09d80-72ae-11eb-9fd6-f29c071fdb5d.png)

**Comment by setdiaoyong** [comment]
> > 功能已出，看看是否需要调整，排序后面再加。
> 
> 置顶图标，未来也可以支持分类，如工作，娱乐，新闻，等，然后直接分类置顶，每个分类以呼出下拉tab的形式，进行展示。
> ![image](https://user-images.githubusercontent.com/62551864/108458112-ecf09d80-72ae-11eb-9fd6-f29c071fdb5d.png)

还可以在这排分类的第一个，增加一个默认分类，历史记录，记录排名靠前的最近访问历史

**Comment by setdiaoyong** [comment]
顶部快捷图标已支持
