### ISSUE TITLE
bug申报：展开与收起第三级列表，图标每次都从文字图标到图片，加载一遍，卡顿，降低了首屏渲染的效果

### ISSUE THREAD

**Issue by setdiaoyong** [xjh22222228/nav#82]
bug描述
20210217 16:47，通过pull request更新到最新，感觉比以前卡顿，发现其中展开与收起第三级列表，图标每次都从文字图标开始加载，然后转到加载图片，每次展开第三级列表，都加载一遍，明显展开列表有卡顿，降低了首屏渲染的效果，但不知道是不是与之前的不样导致的。

**Comment by setdiaoyong** [comment]
首屏加载也比以前慢了

**Comment by setdiaoyong** [comment]
有个css文件加载慢，不知道是不是我个人的原因
![image](https://user-images.githubusercontent.com/62551864/108180544-ded13e80-7141-11eb-9623-e133c83d7afa.png)

**Comment by xjh22222228** [comment]
改进了展开收起，首屏加载可能是你的原因。

**Comment by setdiaoyong** [comment]
> 改进了展开收起，首屏加载可能是你的原因。

好的，可能我现在用的都是从浏览器书签中传进入的，不知道是浏览器本身，还是我装了浏览器插件的原因，还能为每个网址加载一个缩略图图标，格式是data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAB3ElEQVQ4jY2TP2hTYRTFf/clD1LBJCaBoHVJbCpC0CGIdIhkLOiiOLSOUtvRURw6OYgUCiIIleDg4CS46NZBdAgipVCQElMTKoHwQGNipSY88q5Dkudr8iKe6eM795xz7/dHGMHMzMqcaO8ByGVABtsK+k4lcG9vb6PkrR8WkMncSqOBRyhXR02PQHiN9O5UKs+qrkEmvXwF9AVC+J/iIZSfIDcr1adv5Gxq6bxjyAcg9F/iv+gYjl4KxOO5x8CFqGmznPqCIUr99zFfxVzsG9dP1Sn/CtNxAkFEEgZoHqCQsFic3mc9u03UtMfEUdNmPbvN4vQ+hYQ1nCUfVCQJYHVDNDr9KVZnP/GycZpSM+Em3zhZd3mrGxochSQlc+a2jiadO97m4okmhXg/6e33JB9/xNg9iNCyzSOdBUdbbdkmpWaC3YOIa/D8a2pM6DVQPO/Ba/SklnHXE6CGoNZEVgXVMW8XgloGamz6kVHTJhtukQ23fG9lkL9piDprQGeUy0WazCcbzCcb5CJNP3lH1FkzyrXijoougB562a12DKs7hdWdYqsdG40+VNGFcq244w6YTq9kAuI8BK5NHLqPVz017larGxXwOf3Z1FJeDe77fWdxWP1cK7731v8BAFGxisGcnWIAAAAASUVORK5CYII=

导入到nav，也能显示图标，虽然不清晰。
![image](https://user-images.githubusercontent.com/62551864/108181310-b433b580-7142-11eb-98df-8d5f037159b9.png)

可能这个是我这里的原因。

**Comment by xjh22222228** [comment]
缩略图标是浏览器每个书签默认有的
