### ISSUE TITLE
🗻 性能优化：logo图标，在切换目录过程中，有时会重新加载，页面会有些卡顿

### ISSUE THREAD

**Issue by setdiaoyong** [xjh22222228/nav#84]
版本：
20210218 00:38 最新main 分支
下图中的 1，2为多次点击不同一级目录切换，过程中，有两次重新加载了logo。
![image](https://user-images.githubusercontent.com/62551864/108237236-a69e2000-7182-11eb-914e-51b124599e0d.png)

**Comment by setdiaoyong** [comment]
确实多次点击，会重新加载logo图标

![image](https://user-images.githubusercontent.com/62551864/108239253-a69f1f80-7184-11eb-92d3-7586bcd14349.png)

**Comment by xjh22222228** [comment]
已修复多次加载。

**Comment by setdiaoyong** [comment]
收集的网址的图标，如果存在大量无法访问的情况，如https，原始资源删除了，导致页面切换，直接卡住，是否可以，缩短判断加载时间，超出一定加载时间，就用立刻用自动图标。毕竟导航站的立足点就是搜索，快速切换，浏览，查询到要用的。毕竟，丢链的情况很正常。

切换时，卡顿很明显
![image](https://user-images.githubusercontent.com/62551864/108532867-47234a00-7313-11eb-9034-f6479de0205b.png)








**（未来可以加上在搜索，或记录点击网址的频率，自动排序，或者增加一个栏，进行历史回顾，然后能够以访问频率排序，以及推荐相似网址等功能）。**

**Comment by setdiaoyong** [comment]
上传了自己的，没有https的限制，切换不卡
