### ISSUE TITLE
BUG申报：最新main分支，登录后，在页面删除收集的网址，会多删除很多个

### ISSUE THREAD

**Issue by setdiaoyong** [xjh22222228/nav#85]
版本：
20210218 02:21的main分支

在官方https://nav3.cn/  用自己的token登录，然后在页面删除一个收藏的网址，会删除很多个。

操作过程
1、登录后，在前端页面删除一个网址（下图已删除过两次）
![image](https://user-images.githubusercontent.com/62551864/108249342-ed464700-718f-11eb-84c3-ea21f8902aec.png)

2、立刻缩减了一大半图标，页面底部网址数目还没变

![image](https://user-images.githubusercontent.com/62551864/108249569-31d1e280-7190-11eb-8e13-f35fdd60ff12.png)

3、刷新页面后，页面底部网址数目变成当前剩余的
![image](https://user-images.githubusercontent.com/62551864/108249604-3bf3e100-7190-11eb-8d4b-691dc46176d6.png)

**Comment by xjh22222228** [comment]
已修复。

**Comment by setdiaoyong** [comment]
已测试，暂时未发现问题
