### ISSUE TITLE
🗻 性能优化：在切换黑暗/明亮页面时，不仅多次重载logo，而且存在网络加载延迟，导致页面部分黑暗

### ISSUE THREAD

**Issue by setdiaoyong** [xjh22222228/nav#87]
问题描述：
在切换黑暗/明亮页面时，不仅多次重载CSS，而且存在网络加载延迟，导致页面部分黑暗
演示过程：
1、打开 https://nav3.cn/#/side?https:%2F%2Fnav3.cn%2F%23%2Flight=&q=&id=1&page=0
2、关闭打开黑暗模式，存在延迟
![image](https://user-images.githubusercontent.com/62551864/108396761-2b0ba400-7252-11eb-82fe-47bbb8e9c4db.png)
3、浏览器调试界面，显示
![image](https://user-images.githubusercontent.com/62551864/108397130-9d7c8400-7252-11eb-90ad-b760cfb6139a.png)

问题分析
可能是在打开与关闭黑暗模式时，多次加载logo导致

**Comment by setdiaoyong** [comment]
fix（87）部署后测试，页面切换黑暗模式，在左侧列表部分存在延迟，
开启黑暗
![image](https://user-images.githubusercontent.com/62551864/108530098-31605580-7310-11eb-9dee-3806fbe8b464.png)



关闭黑暗
![image](https://user-images.githubusercontent.com/62551864/108530106-33c2af80-7310-11eb-8621-ecff3d8aa09a.png)

**Comment by xjh22222228** [comment]
已减少延迟， 重绘还是会导致一点延迟。

**Comment by setdiaoyong** [comment]
嗯，确实好多了
