### ISSUE TITLE
🗻 性能优化：目录切换，定位问题

### ISSUE THREAD

**Issue by setdiaoyong** [xjh22222228/nav#88]
最新main分支，切换二级目录，定位是根据上一次浏览二级目录的定位的，导致额外的操作，感觉以前版本是对每一个目录记录上一次访问定位的，但是感觉最新main变了。

访问后，翻页至页面中间
![image](https://user-images.githubusercontent.com/62551864/108408461-074f5a80-7260-11eb-9de6-d18af57ff95d.png)

切换到下一个二级目录，定位就变成了页面最底部，可能是上一个页面长度长，中间定位，也比第二个长，导致浏览的不方便
![image](https://user-images.githubusercontent.com/62551864/108408646-467dab80-7260-11eb-9f80-98256c5fc106.png)

优化设计：

1、是否可以在后台，或nav.config.ts设置，除了首屏展示的目录，其他三级目录都是默认合并的

2、记录每个二级目录的上一个浏览定位，再次切换到的时候，为上一次定位，但是刷新页面后，就全变成默认的合并状态

**Comment by aifact** [comment]
fix: side scroll top
2a1329e
已测试，暂无问题
