### ISSUE TITLE
🐛  bug申报：页面描述，在编辑的对话框中，对超长英文字符，不进行换行处理

### ISSUE THREAD

**Issue by setdiaoyong** [xjh22222228/nav#92]
![Snag_7a5ec45](https://user-images.githubusercontent.com/62551864/108451774-5e761f00-72a2-11eb-959d-e2aa9b4698ef.png)

在编辑界面就不能处理长串英文字符内部的换行，但能处理中文与长串英文字符的换行，以及长串英文字符空格后的自动换行
![image](https://user-images.githubusercontent.com/62551864/108452340-49e65680-72a3-11eb-9adb-60669bf49265.png)

**Comment by setdiaoyong** [comment]
fix(#92) 在编辑对话框中，希望能支持，手动输入的回车键，进行人工编排

**Comment by setdiaoyong** [comment]
fix(#92): word break as pre 
已测试，基本没问题，有个地方还需要考虑一下，就是中文与长的超出的英文，在编辑里面自动换行，但是在页面上未回车换行。只有添加回车键，页面就换行，可能统一一下，更好。
![image](https://user-images.githubusercontent.com/62551864/108601919-2a9e1500-73da-11eb-8b4a-abcbcc0d4b0e.png)
添加回车键后，页面换行
![image](https://user-images.githubusercontent.com/62551864/108602104-27575900-73db-11eb-9ac7-622da5274870.png)

**Comment by xjh22222228** [comment]
已保持统一。
