### ISSUE TITLE
💻界面美化：自定义一级目录标题前的图标，使用阿里等开源图标API，直接输入特定名称，展示图标

### ISSUE THREAD

**Issue by setdiaoyong** [xjh22222228/nav#95]

**Comment by xjh22222228** [comment]
[https://github.com/xjh22222228/nav/blob/main/nav.config.ts#L39](https://github.com/xjh22222228/nav/blob/main/nav.config.ts#L39)

**Comment by aifact** [comment]
已测试，可添加，未发现问题

**Comment by aifact** [comment]
就是名称支持范围，可能要在README.md 中说明一下

**Comment by aifact** [comment]
有一个不算问题的小问题，就是一级标题加了图标后，文字与二级标题同列了，不过，把二级标题全加上，就没问题了
![image](https://user-images.githubusercontent.com/79238945/116688258-04ec4800-a9e9-11eb-8f8f-8f8bd9aaabd6.png)
