### ISSUE TITLE
🐛  bug申报: 收藏网址为非正常页面，nav无法处理，导致页面自动添加的图标不显示，算不算判断网址访问性的功能？

### ISSUE THREAD

**Issue by setdiaoyong** [xjh22222228/nav#97]
下图此网址是：https://tcc.taobao.com/cc/json/mobile_tel_segment.htm?tel=13333333333
浏览器访问为
![image](https://user-images.githubusercontent.com/62551864/108529013-fd386500-730e-11eb-99ca-c27a61eced94.png)

在nav无法显示
![image](https://user-images.githubusercontent.com/62551864/108529032-03c6dc80-730f-11eb-8ce7-e5e2fe80c7fe.png)

缩减成https://tcc.taobao.com/cc/json/mobile_tel_segment.htm
浏览器访问显示：
![image](https://user-images.githubusercontent.com/62551864/108529110-193c0680-730f-11eb-8647-fbc846e035b8.png)

在nav任无法显示。

是不是上线了网页联通性，或者网页可访问性的检测

**Comment by xjh22222228** [comment]
无此问题。

**Comment by setdiaoyong** [comment]
可能是我浏览器加载的问题
